### ISSUE TITLE
Couldn't run IPFS commands in Command Prompt

### ISSUE THREAD

**Issue by rayswchiu** [ipfs/ipfs-docs#1029]
Worked before but broken after a IPFS data migration from c:\ to d:\
running on Windows 10

**Comment by johnnymatthews** [comment]
If you're looking for support, checkout with the [Discord](https://discord.com/invite/KKucsCpZmY) server, or the [Discuss Forums](https://discuss.ipfs.io/). Folks in those channels are better suited to help with support issues.
