### ISSUE TITLE
File Entries Gone After Data Migration

### ISSUE THREAD

**Issue by rayswchiu** [ipfs/ipfs-docs#1030]
Brute force migration from c:\ to d:\ , now all file entries gone.
Total "Block" size on new location is intact, but it doesn't show on the IPFS files page (i'm using IPFS Desktop v2.15)
Any chance to get the file entries back?

**Comment by johnnymatthews** [comment]
If you're looking for support, checkout with the [Discord](https://discord.com/invite/KKucsCpZmY) server, or the [Discuss Forums](https://discuss.ipfs.io/). Folks in those channels are better suited to help with support issues.
