### ISSUE TITLE
Distinguish between Desktop vs CLI move install workflow

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1033]
Ref. https://docs.ipfs.io/how-to/move-ipfs-installation/

## Problem

CLI commands and IPFS Desktop use case mixed together. 

What works in CLI and standalone daemon is confusing Desktop users into breaking their setups via manual copy and paste:
https://discuss.ipfs.io/t/ipfs-files-directory-couldnt-load/13505/4?u=lidel

Manual  copy is not enough for IPFS Desktop:
- :anger: It has additional configuration around repo location (`ipfsConfig.path` in  `~/.config/IPFS Desktop/config.json` on Linux) that is not mentioned on the page. 
- :anger:  Desktop app has special GUI for moving that pointer  (IPFS Desktop's tray menu → Advanced → Move Repository Location) and it is also not mentioned on the  page 

## Solution

- Separate command line / standalone daemon from IPFS Desktop
- Make IPFS Desktop section aware of :anger:  (ideally with screenshots)
- Document symlinks  as alternative way of moving repo that does not require changes to any config files and can be easily undone  (https://discuss.ipfs.io/t/ipfs-files-directory-couldnt-load/13505/10?u=lidel)

**Comment by Annamarie2019** [comment]
On https://docs.ipfs.io/how-to/move-ipfs-installation/, CLI commands and IPFS Desktop use case mixed together. This is causing Desktop users issues. We need to separate the Desktop install workflow out. See lidel's suggestion above.

**Comment by johnnymatthews** [comment]
Just need to add in the symlink stuff here and then we're done.
