### ISSUE TITLE
[CONTENT REQUEST] (add your title here!)

### ISSUE THREAD

**Issue by DarkSynx** [ipfs/ipfs-docs#1034]
Windows 11
"C:\Program Files\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe" daemon

**Comment by johnnymatthews** [comment]
It looks like you need general support, not a docs update. Head over to the [Discuss IPFS forums for help](https://discuss.ipfs.io/)
