### ISSUE TITLE
Linking to domain - followed tutorial, ENS content record issue, fails to load site

### ISSUE THREAD

**Issue by stanchiang** [ipfs/ipfs-docs#1039]
I'm going through the IPFS "websites on ipfs" tutorials to set up a website via IPFS and ENS.
a repo of the files is here (the files copy pasta and a terminal command log file with my IPFS and IPNS ids): https://github.com/stanchiang/Random-Planet-Facts

so far I followed the tutorials and on the brave browser (v1.35.103) I can reach the html content at:
`ipfs://QmZNmGfwHY25cotW51cMechh7UQoHLP3Uf7HnnwGiiv1mH`
`ipns://k51qzi5uqu5dlrdku25yzvq26f3v6hml9litxahfwwggkc6429op1tr9kitov2`
I also purchased `stanstan.eth`

my issue is with the content record. 
the instructions say to "Set the Content text box as the CID of your website, prefixed with ipfs://"
but after I do that with my `ifs://QmZN...` and go to `stanstan.eth.link`, 
I get the error `ipfs cat /ipns/stanstan.eth/: could not choose a decoder: no decoder registered for multicodec code 114 (0x72)`
additionally if I go to `stanstan.eth/`, I get a `403 forbidden` with a `Cloudflare` right below it.

I'd like to be able to set the proper content record so that I can view the tutorial project html via my .eth URL.

separately, I would like to set up an `IPNS://` link, not a `IPFS://` one so that I don't have to pay gas every time I want to make an update

I'm new to all this so I appreciated any help

**Comment by johnnymatthews** [comment]
Two things:

1. You added `ifs://QmZN...` to your DNS records. That should be `ipfs://QmZN...`. Can you double check you entered the correct address.
2. I'm getting 504 timeout errors when I try to go to the CID you referenced. I also took at look at your ENS details and the CID referenced there is `ipfs://bafybeifd7mrqwpekl6z5qqrcszdczoau4sktrilrbod67ocnqnl53digia`. Again, can you double check that _that_ CID is correct.
3. Lastly, did you host your site on Pinata? If not, the node you're hosting your website on is likely offline, meaning there isn't a _server_ to resolve this website.

**Comment by stanchiang** [comment]
thanks I had not set up piñata.

follow up question, so far I think I will need to update the content record in ENS each time I want to update the webpage. it doesn't seem like piñata currently supports IPNS hosting. if I want to avoid updating content records each time I want to publish an update, do I basically need to just find another host that supports IPNS?

**Comment by johnnymatthews** [comment]
I'm not sure if Pinata _now_ supports IPNS, [but you should take a look at Fleek!](https://docs.ipfs.io/how-to/websites-on-ipfs/introducing-fleek/) It makes using IPFS & Filecoin to host websites _waaay_ easier. They also support [ENS domains](https://fleek.co/ens-domains/)!
