### ISSUE TITLE
Clarify when CLI chooses a node automatically and when you choose one

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#1044]
Now that IPFS Desktop doesn't add ipfs to path anymore, users who used both CLI and UI from their Desktop install have to go install the CLI separately. (IPFS Desktop install now detects and prompts users to do this)

However, it's not clear from the CLI install docs that it can detect and use an existing node. For example I figured I'd have four IPFS nodes running at any point in time: daemon from CLI, daemon from IPFS Desktop (unless I configure it to use external binary) and Brave release and nightly.

But according to @lidel , the CLI actually can just use any node you've got running.

This should be clear in the installation docs. Maybe a "which one do I need" type of section?

**Comment by lidel** [comment]
Brain dump of what we should document.


Key takeaway: add "Remote Client" and "Local Daemon" use cases to docs at https://docs.ipfs.io/install/command-line/ 

- "Local Daemon" is process started via `ipfs daemon` (already present).
  - It will create `$IPFS_PATH/api` file with address of RPC API
- "Remote Client" is `ipfs` CLI command that uses RPC API to talk to the daemon
   - One can install standalone CLI client independently and use it to talk to IPFS Desktop node or Brave one
   - When `ipfs` command  is executed without parameters, it will  see if `$IPFS_PATH/api` file exists and connect to the address listed there
      -  If  `$IPFS_PATH` is  in default location (e.g. `~/.ipfs` on Linux),  then it will "just work" and `ipfs` CLI client will talk to locally running  `ipfs daemon` without any additional configuration
      -  If not, user can pass `--api <rpc-api-addr>` or set environment variable `IPFS_PATH` to point at a directory with `api` file of existing daemon instance
         - Most common examples:
             - IPFS Desktop users can install CLI tools and `.ipfs/api` file  should be picked up automatically, if not, a custom port can be specified via `ipfs --api /ip4/127.0.0.1/tcp/<port> id`
               - For example, Brave RPC API runs on port 45001, so CLI can talk to Brave daemon via `ipfs --api /ip4/127.0.0.1/tcp/45001 id`
             - There is a trick to do  `mkdir -p ~/.ipfs && echo "/ip4/<ip>/tcp/<rpc-port>" > ~/.ipfs/api` to avoid passing `--api` every time.
