### ISSUE TITLE
IPFS Documentation

### ISSUE THREAD

**Issue by giselflorez** [ipfs/ipfs-docs#1056]
I agreed to update and now it doesn't work anymore!!  It is in a loop of restarts, where the download & restart notification keep popping back up to restart even though I keep doing it. I'm using 10.15.7 Catalina on Mac & had no issues prior  Please help thanks

**Comment by TheDiscordian** [comment]
@giselflorez afraid you need to do one-time manual update: https://discuss.ipfs.io/t/fix-for-ipfs-desktop-0-19-update-restart-issues-on-macos/13500?u=lidel

It should be safe to override old DMG with new one, or uninstall and reinstall.

**Comment by giselflorez** [comment]
Is there a step by step explaining like a child? Lol these things are not my strongpoint.. thank you so much
