### ISSUE TITLE
IPFS Desktop app on Mac won't update. 

### ISSUE THREAD

**Issue by augustfr** [ipfs/ipfs-docs#1059]
Ipfs desktop app has gotten itself in some loop where it wants to update, and when I open the app it says 'Update Downloaded. Update for version 0.20.0 downloaded. To install the update, please restart IPFS Desktop.' so I click the restart button but then it never manages to install it. It'll then let me run my node again for a little while but not long after will turn it off and prompt me to install the update and restart the app again. Can't seem to get it out of this loop.

If I uninstall the app entirely and restart it will I still have all of my content saved on my local node? I have over 11gb so I don't want to uninstall it if it'll lose all of the different files I have.

**Comment by lidel** [comment]
@augustfr afraid you need to do one-time manual update: https://discuss.ipfs.io/t/fix-for-ipfs-desktop-0-19-update-restart-issues-on-macos/13500?u=lidel
