### ISSUE TITLE
Command-line

### ISSUE THREAD

**Issue by yeehi** [ipfs/ipfs-docs#1071]
Save the current working directory into a temporary variable:

`$GO_IPFS_LOCATION = pwd`

On windows, step four here results in "invalid command error".
Perhaps it would be better to include code in the installer to put ipfs onto the path, and offer an alternative to not do so.

**Comment by johnnymatthews** [comment]
> On windows, step four here results in "invalid command error".

Are you using PowerShell?

**Comment by johnnymatthews** [comment]
Gonna close this due to inactivity.
