### ISSUE TITLE
⚠️⚠️⚠️ The public website is being used for phishing!!!

### ISSUE THREAD

**Issue by baywet** [ipfs/ipfs-docs#1083]
Hello there,
I've just received a phishing attempt (documents scanned etc...) on my inbox with a link to

```
https://ipfs.io/ipfs/QmNyhhmCMMKkbd1nFPrBkJXYXwb19g4ohowJabCYCh6ZsC?filename=microsoftonline-authentication.htm#vibiret@microsoft.com
```

I thought I'd let you know so you can take this page down and rotate credentials. Thanks for looking into this!

**Comment by johnnymatthews** [comment]
Forwarded this issue to the security team. Thanks for raising.

**Comment by baywet** [comment]
thanks for the prompt answer and takedown!
