### ISSUE TITLE
Define Peer and Swarm in Docs

### ISSUE THREAD

**Issue by walkerlj0** [ipfs/ipfs-docs#1093]
In searching Docs, I didn't find a clear definition of what a peer is (what defines it and what behaviors/ features can a peer have)

I also think it would be helpful to have a clear definition of w swarms - how the peers in a swarm are determined, how the communication and searching is done (and different from DHT)  they cryptographic keys used, when & how peers in a swarm are determined and maintained.

**Comment by TMoMoreau** [comment]
Taylor*, very common mistake so don't worry about it :) Feel free to refer to me as T Mo, that's what most people do lol.

As for this issue, I will work in a link to the glossary from the "Beginners guide" doc I wrote, that seems like a good start. I also feel the glossary should be more pronounced and visible from anywhere on the docs.

**Comment by Annamarie2019** [comment]
Hi @walkerlj0 and @TMoMoreau I'm triaging this issue. I've been wanting to understand more about swarms too, so I agree this would be great to address. There are definitions in the glossary, but they're very light, as they should be in a glossary, and there is also recently a little more information on peers added to the nodes page, which even has links to its behavior/features: [Nodes](https://docs.ipfs.io/concepts/nodes/), but it doesn't address how peers behave in swarms.

Issue #294 addresses a solution to being able to see glossary terms in search. (We should get to this soon.) 

However, I don't think that Swarms are addressed in the doc, and Lindsay has some great suggestions as to what a page on Swarms could answer. So here's how I see this going:

Create a page on Swarms and Peers to answer Lindsay's suggestions: 
- a clear definition of Swarms and Peers (as members of swarms)
- how the peers in a swarm are determined, 
- how the communication and searching is done (and different from DHT) 
- the cryptographic keys used, 
- when & how peers in a swarm are determined and maintained. 
- add a link to the peers bullet point on [Nodes](https://docs.ipfs.io/concepts/nodes/), saying something like: "To learn more about how peers behave in swarms, see....[The new page].
- add a link to peer and swarm in the glossary to [The new page].

How's that summary?

**Comment by schomatis** [comment]
I think much of this could be leveraged form the libp2p docs to avoid duplication. On the unfortunate "swarm" term (very ingrained in the stack), it has now been [rebranded](https://github.com/libp2p/docs/blob/769946de144b3c0d242778948ac3bf685ab64619/content/concepts/transport.md#supporting-multiple-transports) as "switch", which is basically the transport layer.

**Comment by Annamarie2019** [comment]
@TMoMoreau I defer to @walkerlj0 on this. I would have the same questions. (I just spoke with Lindsay and she's pretty swamped with presentations for the next week.)

**Comment by walkerlj0** [comment]
@TMoMoreau Hmm, lets see
- I think you are accurate when you say nodes are done in the DHT is correct
- By the cryptographic keys used, I think this was early on and I was having trouble understanding that difference between IPFS and Filecoin. Now that I understand things better, I know there is not cryptography in IPFS

This was an early question written by me, so I was just spitballing questions, thanks for answering!

**Comment by TMoMoreau** [comment]
Closing this issue as while I was working on it I realized that most of this info is already in the docs, or is irrelevant to IPFS. I think the only thing that isn't explained in the docs already is how peers in a swarm are determined.
