### ISSUE TITLE
[CONTENT REQUEST] (add your title here!)

### ISSUE THREAD

**Issue by LAMBSTHOMAS** [ipfs/ipfs-docs#1100]
JE N4ARRIVE PAS A FAIRE UN DON POUR LE CANCER SUR MON TELEPHONE PORTABLE

**Comment by TheDiscordian** [comment]
This repo is for docs related issues with IPFS (preferably in English), if your issue really is a docs related issue, please feel free to format your issue in a more understandable way, and re-submit. As it stands though, I don't see how this relates to IPFS in any way.
