### ISSUE TITLE
Configure a node

### ISSUE THREAD

**Issue by LAMBSTHOMAS** [ipfs/ipfs-docs#1101]
Je n'arrive plus a vendre quoi que ce soit sur le site de leboncoin.

Mon site facebook est bloqué aussi par des robots je pense, je n arrive plus a avoir de conversation avec mes amis.

**Comment by TheDiscordian** [comment]
This repo is for docs related issues with IPFS (preferably in English), if your issue really is a docs related issue, please feel free to format your issue in a more understandable way (specifically highlighting how it relates to this repo), and re-submit. As it stands though, I don't see how this relates to IPFS in any way.
