### ISSUE TITLE
Explain that migration must be done 1 version at a time.

### ISSUE THREAD

**Issue by Dialga** [ipfs/ipfs-docs#1110]
A issue exists in the migration tool https://github.com/ipfs/fs-repo-migrations/issues/139 that was closed without a fix making it impossible to migrate across multiple versions in one command, this unfixed bug should be a documented behaviour for any future passerby's who encounter it and do a search for "ipfs migration:  failed to download migrations:". Documentation should state migration must be done 1 incremental version at a time, not in one command.

**Comment by johnnymatthews** [comment]
The FS repo migrations are designed to be ran all at once, and should not need users to run them individually. If you're having consistent problems, I recommend raising an issue in https://github.com/ipfs/fs-repo-migrations, or creating a [discussion using the Discussions tab](https://github.com/ipfs/fs-repo-migrations/discussions/landing).
