### ISSUE TITLE
Document /container-init.d for Docker

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1114]
Update  IPFS Docker documentation at https://docs.ipfs.io/how-to/run-ipfs-inside-docker/ to include content removed in 
Ref. https://github.com/ipfs/go-ipfs/pull/6577/commits/9935863156671795966ab6f1e98602f8bf5a8f60 + @lidel's suggestion from https://github.com/ipfs/go-ipfs/pull/6577#discussion_r847337159

**Comment by thattommyhall** [comment]
I did a folder of examples https://github.com/ipfs-shipyard/go-ipfs-docker-examples, happy to help with documenting a few exemplar use-cases

**Comment by guseggert** [comment]
That'd be great!
