### ISSUE TITLE
Create automation script to update project version numbers across repos.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#1128]
Throughout this repo we reference specific version numbers for things like Go-IPFS and IPFS Updater.

![image](https://user-images.githubusercontent.com/9611008/165761685-2d5d4d3b-7ed3-42a2-823a-36604714a2aa.png)

The problem is that where there's updates to these applications, we have to manually go through this repo and update any references. It'd be nice if we had a script that:

1. Knew which pages to look at.
2. Found version numbers in those pages.
3. Checked to see if they were the latest version of the relevant apps/programs.
4. Updates version numbers where necessary.

We can use this issue to discuss the best way of creating this script.

**Comment by mrodriguez3313** [comment]
Just had a question on who would run the script periodically? Would it be automated through a github action in this repo, would it be an automation on some server hosted by PL, or would someone, run the script locally and then push the changes as a pr? 
<sub>The last option seems useless though as I mention it...<sub>

As I see it, (quickly glanced through the docs) the pages that would need to be altered in the case of a version update, would be those in "/ipfs-docs/docs/install" is that correct? Before talking about the script, there could be a Markdown hack that we could use to make this easier. ["variables" in Markdown](https://www.brianchildress.co/variables-in-markdown/#:~:text=The%20idea%20is%20pretty%20simple,later%20in%20the%20same%20document.) 

So the whole process would look something like: 
1. We manually replace each version number with a variable in markdown and declare the variable at the top of the page somewhere. 
2. Script would just have to search for that variable in bash or python
3. Check against respective repositories or dist.ipfs.io directory, either tags/releases/ or somewhere in code that defines version (ex: [ipfs-update/config.go](https://github.com/ipfs/ipfs-update/blob/e942f3259dc18ab139e3e1659d3d2c5416ab1ac3/config/config.go#L7)
4. Update the one "variable" in the markdown file

This way it still keeps the portability aspect and the script does not have to go parse the whole document. The changes would be minimal to each doc site

**Comment by johnnymatthews** [comment]
> Would it be automated through a github action in this repo

Yeah this is likely the best option.

> ["variables" in Markdown](https://www.brianchildress.co/variables-in-markdown/#:~:text=The%20idea%20is%20pretty%20simple,later%20in%20the%20same%20document.)

Well this is cool! But I wonder if it'd work within codeblocks:

````
Lorem ipsum:

```shell
wget https://ipfs.io/downloads/ipfs-updater-1-18-10.dmg
```
````

Your process seems logical. We'd probably be able to use the GitHub api to check releases for each major repo (Go-IPFS, IPFS Updater, etc).

**Comment by johnnymatthews** [comment]
Ok nice, so something like:

```shell
curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ipfs/go-ipfs/releases/latest | jq ".tag_name"
```

Gives us:

```shell
"v0.12.2"
```

Then we just need some funky regex to run on certain pages to find and replace. This python should work:

```python
import re
regex = r"v\d{1,2}\.\d{1,2}\.\d{1,2}"

test_str = ("---\n"
	"title: Command-line\n"
	"description: Using IPFS through the command-line allows you to do everything that IPFS Desktop can do, but at a more granular level since you can specify which commands to run. Learn how to install it here.\n"
	"current-ipfs-version: v0.12.2\n"
[...]
)

subst = "\"v0.12.2\""
result = re.sub(regex, subst, test_str, 0, re.MULTILINE)

if result:
    print (result)
```

Haven't tested this though.

**Comment by mrodriguez3313** [comment]
It did work, but I had to remove the `[...]` bc I was getting this error. 
```
$ python3 scripts/docs-updater.py
scripts/docs-updater.py:4: SyntaxWarning: str indices must be integers or slices, not ellipsis; perhaps you missed a comma?
  test_str = ("---\n"
Traceback (most recent call last):
  File "scripts/docs-updater.py", line 4, in <module>
    test_str = ("---\n"
TypeError: string indices must be integers

```

Then I changed `subst=v0.12.0` just to see if it did anything and it did :thumbsup: and it returned:
``` 
---
title: Command-line
description: Using IPFS through the command-line allows you to do everything that IPFS Desktop can do, but at a more granular level since you can specify which commands to run. Learn how to install it here.
current-ipfs-version: "v0.12.0"
```

I can try extending this to a given page.

**Comment by johnnymatthews** [comment]
I've added the script to PR https://github.com/ipfs/ipfs-docs/pull/1130. Just need to link it up to GitHub actions and we're good to go! Should probably get a Python wiz to review it to (I'm just a lowly docs guys; programming is not my forte).

**Comment by mrodriguez3313** [comment]
lol now worries. I program well in python, but stackoverflow is our best friend too 😅

**Comment by lidel** [comment]
I think automation for go-ipfs was added in https://github.com/ipfs/ipfs-docs/pull/1081 by @laurentsenta  :+1: 

But we are missing that for ipfs-cluster (so it still has to be updated manually like in https://github.com/ipfs/ipfs-docs/pull/1160).

@laurentsenta would IPDX have time to add similar automation for ipfs-cluster?

**Comment by laurentsenta** [comment]
Sure,

@mrodriguez3313 @johnnymatthews thanks for looking into this,
What about I review the script you shared, and maybe merge it with the CI code that does the version update for go-ipfs (https://github.com/ipfs/ipfs-docs/pull/1081/files)?

**Comment by BigLep** [comment]
Thanks @laurentsenta .  Please proceed with any path that reduces the manual steps here :). Thank you!
