### ISSUE TITLE
Fix broken links in Chat App doc

### ISSUE THREAD

**Issue by Annamarie2019** [ipfs/ipfs-docs#1137]
[Create a Simple Chat App](http://docs.ipfs.io.ipns.localhost:8080/how-to/create-simple-chat-app/#how-it-works) has about 8 broken links and several that go to questionable destinations or just need some tweaking, like opening in a new tab or fixing the display text.

Here is a spreadsheet of the broken links: [ChatAppBrokenLinks](https://docs.google.com/spreadsheets/d/1u3-Jz_OkToJ43GYK0AvTraht2knVqcEMCw1M6p_5qVA/edit?usp=sharing)

This app was edited, so I'll compare the links to what's in [the original blog](http://blog.ipfs.io.ipns.localhost:8080/2021-06-10-guide-to-ipfs-connectivity-in-browsers/) to make sure they didn't get lost in translation. Then I'll take a shot at what I think they should link to and ask @TheDiscordian for the rest (especially for instructions for using WebRTC-Star...that's the most important).

**Comment by Annamarie2019** [comment]
@TheDiscordian Can you help me with these links from the Simple Chat App:

In the [WebRTC section](https://docs.ipfs.io/how-to/create-simple-chat-app/#webrtc-star):
- native setup: There's a link at the bottom that goes to:  https://github.com/libp2p/js-libp2p-webrtc-star#rendezvous-server-aka-signaling-server , but I don't see any instructions there. Where are the instructions to host your own WebRTC star node. (Get a 404 error from your original blog: https://blog.ipfs.io/2021-06-10-guide-to-ipfs-connectivity-in-browsers/)
- docker: also get a 404 error from the original blog
In the Getting Code section:
- latest version of js-ipfs: [this one here](https://cdn.jsdelivr.net/npm/ipfs/dist/index.min.js) .... goes to an actual page of code.

Thanks

**Comment by BlocksOnAChain** [comment]
@Annamarie2019 what do you need to merge this?

**Comment by BlocksOnAChain** [comment]
@TheDiscordian can you review and close this, sir?
