### ISSUE TITLE
Spotted a typo error in IPFS website

### ISSUE THREAD

**Issue by dchidindu5** [ipfs/ipfs-docs#1138]
While going through the https://ipfs.io/ website, I spotted a typographical error in the **HOME PAGE** under the section **"HOW IPFS WORKS"**.

> The indefinite article **"a"**  should be used instead of **"an"** because the word following it is starting with a consonant.

Below is the screenshot of the section that needs to be corrected.
![IPFSerror](https://user-images.githubusercontent.com/18760267/167146362-7e8551a6-518d-4ebc-b12c-2380974829a8.PNG)

**Comment by johnnymatthews** [comment]
Thanks for flagging! I've just submitted https://github.com/ipfs/ipfs-website/pull/127  to fix this.
