### ISSUE TITLE
Multi-page website

### ISSUE THREAD

**Issue by xor256** [ipfs/ipfs-docs#1145]
How add link inside web?

For example I have 6 file
index.html
colors.css = for whole site
img/graphics.png = for every web page
arch.html
2022/01.html
2022/index.html = archiwum of 2022

from arch i need go to index and 2022/01.html
from 2022/01.html i need go to index, arch etc.

**Comment by johnnymatthews** [comment]
I'm not quite sure what you're asking. If you want to link from one page to another, simply add the title of that page in an `<a>` link. 

Here's a snippet taken from the example site:

```html
<p id="output_p"></p>
<h2><a href="about.html">About this website</a></h2>
<script>
```

The `about.html` link is what'll take you to the page you want to go to. If you're still looking for support, head over to the [IPFS Discuss forums](https://discuss.ipfs.io/). Issues in the repo are for docs issues only, not support tickets.

**Comment by xor256** [comment]
`<a href="about.html">`

ok , how writing this reference deep files?
2022/01.html
how writing about? what writing in this same file css file?

all my questions is about trouble with adressing ../../ etc

**Comment by xor256** [comment]
@johnnymatthews you not undestand my question
please dont close this issue

**Comment by johnnymatthews** [comment]
> If you're still looking for support, head over to the [IPFS Discuss forums](https://discuss.ipfs.io/). Issues in the repo are for docs issues only, not support tickets.
