### ISSUE TITLE
Update docs to reflect  Relay V1 (server) removal from go-ipfs 

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1146]
We need to  update all places that mention `EnableRelayHop` –   Relay V1 server was removed from go-ipfs 0.11 and now requires running a separate binary.

See details in:
-   [go-ipfs v0.11.0 Release Notes](https://github.com/ipfs/go-ipfs/releases/tag/v0.11.0)
  - Relay V1 can be still provided by this standalone binary: https://github.com/libp2p/go-libp2p-relay-daemon#minimal-config-file / https://dist.ipfs.io/#libp2p-relay-daemon

The most important is to update "browsers connectivity" tutorial by @TheDiscordian: 

1. https://blog.ipfs.io/2021-06-10-guide-to-ipfs-connectivity-in-browsers/
2. https://docs.ipfs.io/how-to/create-simple-chat-app/

(We seem to already document v1 and v2 in https://docs.ipfs.io/concepts/nodes/#types)

**Comment by lidel** [comment]
@TheDiscordian as you are the original author of the tutorial, would you have time to update it?
My next 2-3 weeks are pretty packed, and I won't be able to do this any time soon.

**Comment by TheDiscordian** [comment]
@lidel I'd love to, I plan to have this updated by Friday.

**Comment by lidel** [comment]
@TheDiscordian  this is probably a bad question to ask at 2AM, but since all peers use the same webrtc signaling server, and they can post their own multiaddr to the same pubsub channel, why do we need the [Python script](https://gist.github.com/TheDiscordian/51962fea72f8d5a5c3bba79dd7009e1c)  for advertising on pubsub on their behalf?

**Comment by TheDiscordian** [comment]
@lidel I missed this until now, the reason for the pubsub is for the relay connections (IE: Cannot punch for WebRTC). Node A connects to Relay, Relay advertises Node A, Node B connects to Relay, Relay advertises Node B, Node A now has a path to Node B, connecting them together via Relay.

**Comment by ElPaisano** [comment]
@BigLep @lidel can you help Johnny and I determine if this is still relevant? 

From https://docs.ipfs.tech/concepts/nodes/#relay, it looks like we still mention relay v1

**Comment by ElPaisano** [comment]
Removing the `P1` label, as the team doesn't seem to be pressing this issue. Will keep in backlog until I hear back.

**Comment by ElPaisano** [comment]
Since https://docs.ipfs.io/how-to/create-simple-chat-app/ has been removed as part of the js-ipfs cleanup, this is no longer relevant. Closing.
