### ISSUE TITLE
[ABUSE] on a subdomain

### ISSUE THREAD

**Issue by kernrot** [ipfs/ipfs-docs#1149]
Please check this subdomain of your project:
https://bafybeib2oea6zbbfvmr4amk2pp4yxkwknm2gglzhdd4vbaknuwfbqqomqq.ipfs.dweb.link

**Comment by johnnymatthews** [comment]
What's the concern here? Your comment doesn't really explain much. Closing.

**Comment by kernrot** [comment]
a Phishing-site hosted via this projects domain:
"ipfs.dweb.link"

**Comment by johnnymatthews** [comment]
Ah, ok. Thanks for clarifying. The page doesn't actually load for me. 

![image](https://user-images.githubusercontent.com/9611008/168707817-8d85cf88-0ee0-44fa-b5cd-032a62d5f055.png)

Either way, I've passed it off to abuse@ipfs.io. If you come across any further issues like this, please forward them to that email.
