### ISSUE TITLE
Docs project setup troubleshooting details

### ISSUE THREAD

**Issue by lbliii** [ipfs/ipfs-docs#1162]
Hello! My name's Lawrence and I'm applying to a technical writing role at Protocol Labs. While trying to locally deploy this project I ran into an error that seems related to newer Node.js versions. I suspect this is true for Node.js 17+, but I'm only using 18.0.0.

My suggestion is to maybe add a troubleshooting subsection on the README, under **Project set up**.   Below is a quick writeup, but feel free to revise/place this anywhere that makes the most sense. 

**Note**: There's quite a few solutions out there (and I'm not 100% sure mine is the best one), but this solution was the simplest without requiring a downgrade. 

---

### Troubleshooting 

Having some trouble getting set up with our documentation? Review some of these common errors and their solutions.

#### Digital envelope routines initialization error 

The following error message may display for contributors using Node.js version 18.0.0 when attempting to locally deploy this project for the first time:

##### Error message

```bash 
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
##### Solution 

1. Open a terminal. 
2. Navigate into the `ipfs-docs` project.
3. Run the following command:
   ```bash
   export NODE_OPTIONS=--openssl-legacy-provider
   ```
4. Run `npm start`.

**Comment by TMoMoreau** [comment]
Added troubleshooting section to the read me containing this error and solution. Thanks!
