### ISSUE TITLE
Update the Minty tutorial to help Windows user.

### ISSUE THREAD

**Issue by edwardbits** [ipfs/ipfs-docs#1200]
Hey 
I want to mint an NFT using IPFS and minty, but the tutorial doesn't explain how to do it on Windows, if it's even possible without another operating system.  You may need to go into a little more detail as to the system requirements for minting NFTs on Windows, maybe.  Could you tell me how to do just that?  Thanks, sincerely...

**Comment by johnnymatthews** [comment]
This'd be a nice addition. Unfortunately, it's not super high priority right now. If any community members want to talk up this issue though, any PRs would be really appreciated!

**Comment by edwardbits** [comment]
Sorry, some of my keys are expired, I'm unable to decrypt your message, I believe.
Thanks, Edward

Sent with Proton Mail secure email.

------- Original Message -------
