### ISSUE TITLE
Host multipage website on IPFS

### ISSUE THREAD

**Issue by ireney2022** [ipfs/ipfs-docs#1210]
I saw the same issue has already been brought up and closed; however, as a resolution had not be reached, I am bringing up the issue again. 

I tried doing the single-page website and multipage website, following the steps outlined in the tutorials:
https://docs.ipfs.io/how-to/websites-on-ipfs/single-page-website/#set-up-a-domain
https://docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/#prerequisites

But when I copied and pasted the links into my browser (I tried Chrome, Firefox and Safari), I just got lines of code. I removed all extensions from Chrome and I never put any extensions on my Safari browser. 

Here is a screenshot of the multipage website in Chrome:

<img width="742" alt="Screen Shot 2022-07-22 at 8 56 01 AM" src="https://user-images.githubusercontent.com/98928666/180334835-4b362579-1fad-4f39-aab5-1ca72841a80a.png">

Thank you in advance for your assistance!

**Comment by johnnymatthews** [comment]
> But when I copied and pasted the links into my browser

Which links are you trying to use?

**Comment by ireney2022** [comment]
Thank you for responding to my query. 

I am referring to the links that are generated by following: 
1. the instructions on “Host a single-page website on IPFS” (https://docs.ipfs.io/how-to/websites-on-ipfs/single-page-website/#install-ipfs-desktop), under the heading “Add your site,” in steps 5-6; and
2. the instructions on “Multi-page website” (https://docs.ipfs.io/how-to/websites-on-ipfs/multipage-website/#prerequisites), under the heading “Add files to IPFS,” in steps 4-5.

Thanks again!

**Comment by johnnymatthews** [comment]
Sorry for the delay. I couldn't replicate your problem, but I'm running Ubuntu right now. I'll see if I can run through stuff on a Mac.

**Comment by ireney2022** [comment]
Thanks for getting back to me. Yes, I believe I have saved the file properly. Yes, “links that are generated” = clicking on the 3 dot menu. I really don’t know what I am doing, so I’m attaching images for you to see.

<img width="1175" alt="Screen Shot 2022-08-03 at 9 49 14 PM" src="https://user-images.githubusercontent.com/98928666/182613437-f3439479-177d-4692-bb6c-a95e36fb1349.png">
<img width="714" alt="Screen Shot 2022-08-03 at 9 51 57 PM" src="https://user-images.githubusercontent.com/98928666/182613451-726e0a55-f3c2-488b-99f5-29bf96455c0e.png">

Thanks again for your help!

**Comment by johnnymatthews** [comment]
Sorry for the delay. I'm having a hard time figuring out what's going wrong for you here. In that 2nd screenshot, when you double-click on any of the `.html` files, what happens? It looks like they're formatted correctly, and your computer should just open `.html` files like any normal webpage.

**Comment by ireney2022** [comment]
Okay, here it is... Thank you for your help. I really do appreciate it!

https://user-images.githubusercontent.com/98928666/184817616-55e9fdcc-de0a-4819-a9cb-1b126d519f35.mov

.

**Comment by johnnymatthews** [comment]
I'm gonna grab another engineer to take a look at this, because it isn't a situation I've seen before.

**Comment by TheDiscordian** [comment]
Heya! Happy to try to help. @ireney2022  Could you please:

1. Share the CID you're working with (I've used OCR to grab it, but just in case)
2. Upload / pin the content somewhere so it's available to me (this can be via [web3.storage](https://web3.storage) or [Pinata](https://pinata.cloud) for example)

This way I can work with exactly what you have, and try to figure it out. It looks quite odd as it really seems like you've done everything correctly.

**Comment by TheDiscordian** [comment]
@ireney2022 Looks like whatever editor you used copied all the formatting of the text, instead of the characters themselves. Something like VSCode should help with this problem, I've heard Sublime is popular on Mac as well.

**Comment by johnnymatthews** [comment]
I'm gonna close this, since it looks like we've got a solution to the problem. @ireney2022 if you're still running into issues, I suggest posting your problem in the [IPFS Forum](https://discord.gg/ipfs), or join the [IPFS Discord](https://discuss.ipfs.tech/).

**Comment by ireney2022** [comment]
Thank you @TheDiscordian! Yes, VSCode did help :)
