### ISSUE TITLE
Add alternate pinning services to the Websites on IPFS section.

### ISSUE THREAD

**Issue by dawnkelly09** [ipfs/ipfs-docs#1214]
https://docs.ipfs.io/how-to/websites-on-ipfs/single-page-website/#pinning-files

In reviewing this demo on hosting a single page site, I noticed the pinning files section lists only Piñata as a pinning service provider. I would like to suggest this section be updated to add web3.storage and nft.storage as pinning service options which are based more closely to our ecosystem. If you agree, I am happy to assist with this update if you would like to assign me to this issue. Thank you!

**Comment by johnnymatthews** [comment]
Absolutely! This tutorial was created way back before we had other pinning-service options. PRs welcome!

**Comment by dawnkelly09** [comment]
I'm now wondering if this should be left as is since the tutorial demos using Pinata. I am thinking though we should add web3 storage & nft storage to the pinning services section this tutorial refers users to if they want more info on pinning service options: https://docs.ipfs.tech/concepts/persistence/#pinning-services (take a look at the Pinning services section). 

I'm thinking info on web3 & nft storage below those bullet points about use cases for pinning and then keep the "some available services" list at the bottom. 

If team is in agreement, I'll open the PR there instead.

**Comment by dawnkelly09** [comment]
Issued closed with merging of PR #1224
