### ISSUE TITLE
Update the link to `Add your site` section in `Websites on IPFS` tutorial.

### ISSUE THREAD

**Issue by mas268ga** [ipfs/ipfs-docs#1216]
Link to 'add your site' (https://docs.ipfs.io/install/how-to/websites-on-ipfs/single-page-website/#add-your-site) needs updating?

**Comment by TMoMoreau** [comment]
Either this has been fixed, or I'm confused about where this specific broken link is.

**Comment by johnnymatthews** [comment]
Yeah, I can't see what link is broken here. Closing.
