### ISSUE TITLE
A-ADS partnership proposal for IPFS

### ISSUE THREAD

**Issue by MargotAADS** [ipfs/ipfs-docs#1233]
Dear IPFS's team,

I'm Margot from [A-ADS](https://a-ads.com/?utm_source=direct_sale). This is a cryptocurrency advertising network that allows large websites to earn bitcoin by placing advertising banners.

Sites that work with us earn up to hundreds of thousands of dollars a month from advertising thanks to our technology, which opens up extra earning opportunities:

- increased income due to the high demand for your site by advertisers + high CPM from $24 and up (in the Premium Crypto category);
- attracting direct advertisers on your site due to the self-served technology of our banners;
- affiliate percentage of advertisers' spending referred to A-ADS;
- additional income by reaching our CPA advertisers' goals.

 
Now we are actively looking for and connecting Premium Partners who could profitably monetize their traffic with A-ADS.
Moreover, after analyzing your [site](https://ipfs.tech/) and out of our experience and long-term partnerships, we see great perspectives that could truly shoot out within our cooperation.

I need to mention that our transparency and privacy policy excludes JavaScript, intrusive pop-ups and the collection of users’ personal data.

Could we set up a call, so we can share all the benefits of working with us?
Kindly let me know your thoughts and a good time for our 20 minutes meeting.

PS: Unfortunately, I did not find direct contacts to invite you to our Premium Program as a Publisher in another way, but I would be grateful, if you would forward this proposal to the responsible partnerships development specialist for further detailed discussion of our possible cooperation.

Cheers,
Margot Kochneva, Partnerships Development Manager
m.kochnevaз[@]aads.com

**Comment by TMoMoreau** [comment]
Sorry, we are not interested.
