### ISSUE TITLE
Add context to each item in academic-papers.md

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#1247]
@yiannisbot suggestion extracted from https://github.com/ipfs/ipfs-docs/pull/1242#issuecomment-1217732613:
> It's a good idea to add (in parentheses at the end of the paper title?) where the paper was published together with the year. For the whitepaper, this can be "Original IPFS Whitepaper" or something similar.

**Comment by TMoMoreau** [comment]
This is being addressed in PR #1414
