### ISSUE TITLE
Link to web resources more/dedicated resources page

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/ipfs-docs#1249]
Related: https://github.com/ipld/ipld/issues/234

Many tools like https://cid.ipfs.tech and https://dag.ipfs.io are scarcely mentioned throughout IPFS's and IPLD's documentation, they don't appear prominently or frequently anywhere, which is a shame because these tools are often the most useful for troubleshooting and teaching people how both protocols work.

To solve this, not only should the documentation link to these resources more often, but, there should be a dedicated page which links to all IPFS/IPLD resources to make searching for them easier.

**Comment by TMoMoreau** [comment]
I like this, just off the top of my head, I'm not sure where these links could easily fit in. If you have a good idea on where these links would fit best, feel free to open a PR with your suggestions. :)

**Comment by Winterhuman** [comment]
A **Troubleshooting** page under https://docs.ipfs.tech/how-to seems like the best place, then you can walk through all the possible problems and which websites to use to verify.

e.g. "If you get an error saying your CID is invalid, check it with https://cid.ipfs.tech. After that ..."

**Comment by Winterhuman** [comment]
Oh hold on, https://docs.ipfs.tech/concepts/content-addressing/#cid-inspector actually does link to the CID inspector (and https://explore.ipfs.io too), I've just never noticed. I wonder if this is just a layout issue and people don't spot the links amongst the blocks of text

**Comment by Winterhuman** [comment]
Admittedly, it seems that all the links in https://docs.ipfs.tech are quite hard to spot, maybe having underlines under all the links by default would make them easier to see amongst text (and then have a hover style which makes the link bold or something). I imagine this is documented in a style guide somewhere

**Comment by Winterhuman** [comment]
Just to compress the last three comments I have left:

- Turns out https://docs.ipfs.tech/how-to/troubleshooting already exists, which is what I'd suggested.
- Some pages do in fact link to https://cid.ipfs.tech and other resources.
- But for some reason, I didn't spot them; I'm finding it hard to navigate the docs for some reason.

**Comment by TMoMoreau** [comment]
Closing this issue for now as it seems the issue has solved itself. If you think of other ways we could improve the docs, please open another issue and we'll be happy to take a look. :)
