### ISSUE TITLE
Recent releases page is out of date

### ISSUE THREAD

**Issue by mishmosh** [ipfs/ipfs-docs#1250]
There is a [recent releases page](https://docs.ipfs.tech/install/recent-releases/#go-ipfs-0-10) page in IPFS Docs > Install. It was last updated Oct 2021 with go-ipfs 0.10. We're now at kubo 0.14.

It should either be updated & a process identified for keeping it up-to-date, or removed entirely.

Thoughts @TMoMoreau @jennijuju @johnnymatthews @2color @aschmahmann @lidel @BigLep?

**Comment by johnnymatthews** [comment]
Hmm, that's odd. [I thought we removed that ages ago](https://github.com/ipfs/ipfs-docs/pull/717)...

I agree, let's rip it out.

**Comment by TMoMoreau** [comment]
I agree as well, there is already a link to https://dist.ipfs.tech/ in the command-line install doc and also in the updater doc.

**Comment by johnnymatthews** [comment]
PR made. @mishmosh since you opened this issue, I'll wait for your thumbs up and we can get this merged!
