### ISSUE TITLE
[EPIC] Kubo v0.15 Release

### ISSUE THREAD

**Issue by jennijuju** [ipfs/ipfs-docs#1261]
**Target Ship Date:** Shipped - https://github.com/ipfs/kubo/releases

List of issues that are for Kubo 0.15 release:
- [ ] Blake 3 support
- [ ] Fx options plugin
- [ ] `$IPFS_PATH/gateway` file

**Comment by lidel** [comment]
@jennijuju   ? :cat2: 

We have CI automation that bumps version in docs and opens a PR when there is a new release.
For 0.15 it was https://github.com/ipfs/ipfs-docs/pull/1263 (already merged). 

Or is this about something else?

**Comment by TMoMoreau** [comment]
@lidel this is meant for me to keep track of other things that need documenting with the 0.15 release, the [gateway redirects](https://github.com/ipfs/specs/pull/290) for example.

**Comment by lidel** [comment]
Ack.  fysa redirects (https://github.com/ipfs/kubo/pull/8890) did not land in 0.15, hoping to include them in 0.16

**Comment by TMoMoreau** [comment]
@lidel, just to confirm I understood correctly what you said in the Triage call, these things don't need to be documented?

**Comment by jennijuju** [comment]
@lidel  - could you please whether the items outlined by Tmo require documentation or anything else you think we should be working on for the 0.15 releasE?

**Comment by lidel** [comment]
I think we are good, and this issue can be closed:
- 0.15 did not have anything that would require new docs, or changing any pre-existing docs we have. 
  - no need to write docs about `$IPFS_PATH/gateway`: we need to finalize specs at https://github.com/ipfs/specs/pull/280 first
