### ISSUE TITLE
Consolidate the 2x Contributing sections

### ISSUE THREAD

**Issue by mishmosh** [ipfs/ipfs-docs#1266]
There are currently 2 "contributing" sections in IPFS Docs, and 90% of the content overlaps:

https://docs.ipfs.tech/project/contribute/
https://docs.ipfs.tech/community/contribute/ways-to-contribute/

We should consolidate to 1.

**Comment by TMoMoreau** [comment]
I wasn't aware that the https://docs.ipfs.tech/project/contribute/ existed. Agree we should consolidate them into one.

According to the [plausible analytics](https://plausible.io/docs.ipfs.tech/pages), https://docs.ipfs.tech/community/contribute/ways-to-contribute/ gets more traffic, so I propose removing the contributing page from the `Project` section in favour of the `Community` contributing section.

**Comment by TMoMoreau** [comment]
@ElPaisano is going to try and tackle this as a first issue when he gets the chance. :)

**Comment by ElPaisano** [comment]
Hello the PR for this is  https://github.com/ipfs/ipfs-docs/pull/1279
