### ISSUE TITLE
_redirect, end user documentations for gateway _redirect

### ISSUE THREAD

**Issue by jennijuju** [ipfs/ipfs-docs#1273]
we want to add a sub page under `websites on IPFS`
![image](https://user-images.githubusercontent.com/42981373/188703238-1e9c631c-5890-4c10-8e83-ad1525f91cbc.png)

**Comment by jennijuju** [comment]
(on how to create a subpage, may refer to [this PR](https://github.com/ipfs/ipfs-docs/pull/1193/files)

**Comment by jennijuju** [comment]
We are expecting the first draft to be opened by EOW

**Comment by jennijuju** [comment]
@TMoMoreau is this done?

**Comment by TMoMoreau** [comment]
@jennijuju Yeah this is done. I'll close it now. :)
