### ISSUE TITLE
Sites fails after starting IPFS-desktop 0.23.0

### ISSUE THREAD

**Issue by glenndk** [ipfs/ipfs-docs#1277]
After installing (IPFS-Desktop-0.23.0.dmg) and enabling it, from instantly to after a few minutes, some sites/web-pages won't respond properly in the web browser Firefox (with Adblock Plus, Ghostery, NoScript, uMatrix) at the same time Google Chrome (with uMatrix) fails the same sites - e.g.:
https://da.wikipedia.org/wiki/InterPlanetary_File_System
https://github.com/ipfs/ipfs-desktop/releases
https://downdetector.com/
https://docs.sophos.com/esg/sixm-android/help/en-us/index.html

System: Updated MacOS 10.15.7 (19H2026). Hardware: MacBook Pro (15-inch, Mid 2012), 2,3 GHz Quad-Core Intel Core i7. RAM: 8 GB 1600 MHz DDR3. Installed Sophos Home Premium.

(I have also tried to restart the PC after installing IPFS-desktop - same problem)

When web-access failed the dns-reply was ok:
$ nslookup ipfs-search.com
Server:		10.xx.0.1
Address:	10.xx.0.1#53
Non-authoritative answer:
Name:	ipfs-search.com
Address: 146.70.80.218
$ 

$ nslookup downdetector.com
Server:		10.xx.0.1
Address:	10.xx.0.1#53
Non-authoritative answer:
Name:	downdetector.com
Address: 104.18.1.148
Name:	downdetector.com
Address: 104.18.0.148
$ 

Ping was also ok while failed web-access:

$ ping ipfs-search.com
PING ipfs-search.com (146.70.80.218): 56 data bytes
64 bytes from 146.70.80.218: icmp_seq=0 ttl=55 time=17.408 ms
64 bytes from 146.70.80.218: icmp_seq=1 ttl=55 time=11.200 ms
^C
--- ipfs-search.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 11.200/14.304/17.408/3.104 ms
$ ping downdetector.com
PING downdetector.com (104.18.1.148): 56 data bytes
64 bytes from 104.18.1.148: icmp_seq=0 ttl=57 time=12.277 ms
64 bytes from 104.18.1.148: icmp_seq=1 ttl=57 time=11.097 ms
^C
--- downdetector.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 11.097/11.687/12.277/0.590 ms
$ 

Se attachments.

Firefox:

![220910 kl  18 12 36 UTC1](https://user-images.githubusercontent.com/48173331/189492264-06280a06-67f8-42cd-9020-a1e06d9c3e25.png)

Google Chrome:

![Skærmbillede 2022-09-10 kl  19 03 03](https://user-images.githubusercontent.com/48173331/189494048-ce799b35-f495-410f-8661-0cf7afc261ee.png)

**Comment by TMoMoreau** [comment]
Hi @glenndk, is this still an issue for you? I'm no engineer but this seems like unusual behaviour.

If this is still an issue for you, please open a help topic on https://discuss.ipfs.tech/ if you haven't already. You can also ask in one of our IPFS chat channels on Discord/Matrix/Slack here: https://docs.ipfs.tech/community/chat/#discord

As this is not an issue with the docs themselves, I'm going to close this issue and wish you the best of luck in solving your problem.
