### ISSUE TITLE
Kubo HTTP API docs for `get` may be missing default TAR behavior

### ISSUE THREAD

**Issue by mrd0ll4r** [ipfs/ipfs-docs#1285]
Hey!

I stumbled upon this today: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-get lists the output as `text/plain` and does not say anything about the `archive` flag being enabled by default. Using kubo `v0.14.0`, I believe it is enabled by default.

The [Go IPFS API client](https://github.com/ipfs/go-ipfs-api/blob/master/shell.go#L386-L399) unpacks the response through tar, without setting any extra options in this regard, which makes me believe it's set by default.

Interestingly, the Go client also sets a `create` flag, which is undocumented. Does this exist? If yes, what does it do?

**Comment by guseggert** [comment]
See https://github.com/ipfs/ipfs-docs/issues/1215
