### ISSUE TITLE
Document how to connect browser nodes with Kubo nodes using WebTransport

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs-docs#1286]
## Done Criteria
A user can learn about to enabling connectivity between Chromium browser nodes with other implementations like Kubo with WebTransport.

## Why Important
We're unlocking great functionality here, but we need to ensure users can discover it, and know how to get started so the impact can be realized.

## Notes
1. There is lots of work going around WebTransport, getting it into libp2p (both JS and GO), and exposing it in IPFS.  This issue captures the docs.ipfs.tech portion of it.  Implementation issues:
   - https://github.com/ipfs/kubo/issues/9289
   - https://github.com/ipfs/kubo/issues/9292
   - https://github.com/libp2p/go-libp2p/issues/1717
   - https://github.com/libp2p/js-libp2p-interfaces/pull/292
2. Ideally we should be pointing out to other documentation sources as much as possible and not duplicating.  We do need to cover the IPFS-specific portions.  For example, https://github.com/libp2p/website/issues/154 will be relevant to point users for them to learn more.  
3. An executable ipfs-example is going to go a long way here.  Please coordinate with @2color or other developer advocates on how we tell this story.

**Comment by lidel** [comment]
JS is WIP: https://github.com/libp2p/js-libp2p-interfaces/pull/292
I don't think this can be worked on until we have both JS and GO shipped as opt-in in stable Kubo and JS-IPFS releases.

**Comment by mishmosh** [comment]
There isn't any other mention in docs of browser nodes being paired with longer-running nodes. This is an architecture we'd like more developers to understand and perhaps use.

When we're ready, a tutorial/example would fit nicely into How-Tos > IPFS in the browser: https://docs.ipfs.tech/how-to/

**Comment by BigLep** [comment]
@ElPaisano : we can document about WebTransport today.  #9724 is about WebRTC which is an additional transport from the browser.

I think there is enough information about this today, but there are also demos getting created now for IPFS Thing which will help make this clear.  @aschmahmann and @SgtPooki will be able to help here.  Lets pick this up after IPFS Thing 2023.

**Comment by BigLep** [comment]
@TheDiscordian : I know you have done work in and around this space?  Is drafting something here, something you'd be interested in starting?  I think even getting an outline together that myself and others could contribute towards would help.

**Comment by lidel** [comment]
There is an explainer in https://connectivity.libp2p.io/#webtransport that could be reused here, what is missing are code examples.

Caveat: I suspect this is soft-blocked by https://github.com/protocol/bifrost-infra/issues/2142  and/or  https://github.com/ipfs/kubo/pull/9877 (or we need to introduce TLS cert to remove need for `/certhash`):
- webtransport address announced by Kubo  have `/certhash` components  which change every 14 days, so we can't hardcode them in webapps like we can with peerid alone
  - means we need to lookup peer to learn new `/certhash` on fresh or failed connect attempt (knowing IP and port is not enough)
- Kubo does not announce own `/webtransport` addrs to IPNI, only DHT, and DHT lookup/walk in browser is still a bit too expensive (we need delegating routing, native walk would be used only as a fallback).
