### ISSUE TITLE
[CONTENT REQUEST] c-ipfs implementation

### ISSUE THREAD

**Issue by ftyers** [ipfs/ipfs-docs#1287]
Could you add https://git.agorise.net/agorise/c-ipfs to the list of implementations?

**Comment by TMoMoreau** [comment]
Relevant issue: https://github.com/ipfs/ipfs-docs/issues/1360

Plan is to split the implementations page into 2 sections. Legacy/deprecated and actively maintained implementations.

**Comment by ElPaisano** [comment]
Echoing Johnny's comment here:

Looks like c-ipfs no longer maintained. So, Ill add this to https://docs.ipfs.tech/concepts/ipfs-implementations/#inactive. If this is incorrect, please comment on the linked PR

PR https://github.com/ipfs/ipfs-docs/pull/1554#issue-1658133735
