### ISSUE TITLE
Update incorrect link from /basics page to CLI interfaces

### ISSUE THREAD

**Issue by keshiba** [ipfs/ipfs-docs#1301]
**Problem**: 
The "/basics" page has a broken link under the "Command Line" section which takes you to a non-existent page.

![image](https://user-images.githubusercontent.com/62872563/194720239-7a128878-0168-4802-ae09-a0eedea2fe6f.png)

![image](https://user-images.githubusercontent.com/62872563/194720179-7fd54b39-42f7-4739-b920-eef1e93b3913.png)

**Comment by keshiba** [comment]
The only relevant page I could find for CLI interfaces is located at ./go/command-line.md.

Would this be a viable fix ?
![image](https://user-images.githubusercontent.com/62872563/194720463-a257486c-1bbf-4f33-ac7e-97f0f6d9764f.png)

**Comment by TMoMoreau** [comment]
Hi, it seems that link is supposed to point to https://docs.ipfs.tech/basics/go/command-line/

@ElPaisano is already working on a PR to fix broken links ( #1306 ), I'll make sure this one gets in that PR as well. Thanks for bringing this to our attention.

**Comment by TMoMoreau** [comment]
Closing as fixed, the large PR to fix links, mentioned above, has been merged. Thanks!
