### ISSUE TITLE
<%

### ISSUE THREAD

**Issue by Donasela2019** [ipfs/ipfs-docs#1303]

**Comment by TMoMoreau** [comment]
Closing, no information provided. If you have an issue or suggestion for the IPFS Docs, please open a new issue with as much information as possible.

**Comment by Donasela2019** [comment]
@Donasela2019

**Comment by Donasela2019** [comment]
**[](gh pr checkout 2) **

**Comment by Donasela2019** [comment]
[ ] 
Duplicate of #
