### ISSUE TITLE
Add documentation for deleting/re-downloading IPFS

### ISSUE THREAD

**Issue by kobieaw** [ipfs/ipfs-docs#1313]
I would love to see some type of documentation about how to fully delete any ipfs file from my local machine and then redownload to take care of any issues

**Comment by kobieaw** [comment]
Like in a FAQ about common ways to solve a problem with your ipfs node. I fixed it. But a "cd into the /.ipfs file and then do rm -rf on the FILE NAME" would be helpful. And then link back to the IPFS getting started

**Comment by ElPaisano** [comment]
@2color any thoughts on this?

**Comment by 2color** [comment]
I think there's a misunderstanding here about how a file related to blocks. 

When a file is added to IPFS, it's chucked into blocks which are added to a local IPFS repo and also pinned so it's not garbage collected.

Hence, deleting a file is a matter of removing a pin (https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-pin-remote-service-rm) and running garbage collection (https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-repo-gc)

**Comment by kobieaw** [comment]
Thanks @2color

**Comment by ElPaisano** [comment]
Thank you for taking the time to submit this issue. Triaging issues here. It looks like this was more of a support question, which 2color appears to have answered. If not, please reopen this issue and clarify. Thank you.
