### ISSUE TITLE
Hyperlink leading to a non-existing page (Basics / IPFS in Golang)

### ISSUE THREAD

**Issue by htasevsk1** [ipfs/ipfs-docs#1325]
![image](https://user-images.githubusercontent.com/43993526/201496076-7531f7af-b90a-482c-9342-a666cf13f1d0.png)

The [install Kubo with the CLI](https://docs.ipfs.tech/basics/install/command-line/) hyperlink leads to an 404 page.

**Comment by TMoMoreau** [comment]
Thanks for bringing this up, the page exists (https://docs.ipfs.tech/install/command-line/), the link behind the text is wrong. We currently have a large PR in progress to fix broken links (PR #1306)

We'll make sure this gets fixed.

**Comment by TMoMoreau** [comment]
The fix link PR mentioned above has been merged. Closing this as completed.
