### ISSUE TITLE
Add Free/OpenBsd install instructions

### ISSUE THREAD

**Issue by ChangingStack** [ipfs/ipfs-docs#1326]
Both OpenBsd and FreeBsd seem to be official distributions, with both having officially provided binaries, as can be be seen with the [v0.16.0](https://github.com/ipfs/kubo/releases/tag/v0.16.0) release.

As such would it be possible to add installation instructions to the command line only install page, seen [here](https://docs.ipfs.tech/install/command-line/#official-distributions).

To do so, the linux instructions can just be copied, with the url used needing to be changed and "sudo" being replaced by "doas".

Thanks

**Comment by ChangingStack** [comment]
Also the same should be done for the [ipfs-update](https://docs.ipfs.tech/install/ipfs-updater/#install-updater) tool.

**Comment by ElPaisano** [comment]
Hi @ChangingStack 👋 I'm one of the tech writers.

I was just starting work on a refactor of the command line install page, and included the FreeBSD and OpenBSD instructions there. It would be great to get your feedback on https://github.com/ipfs/ipfs-docs/pull/1342

**Comment by ElPaisano** [comment]
closed by https://github.com/ipfs/ipfs-docs/commit/731931c8c4db4c39191c07643eeb405663a993ed
