### ISSUE TITLE
Update pinning documentation

### ISSUE THREAD

**Issue by cypt4** [ipfs/ipfs-docs#1352]
For add\ls\remove methods:

1) There is possibility to [add](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-pin-add)/[rm](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-pin-rm) several CIDs using arg parameter : arg=cid1&arg=cid2..
2) For the [ls method](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-pin-ls) return value differs ex:
`{"Keys":{"QmNwbd7ctEhGpVkP8nZvBBQfiNeFKRdxftJAxxEdkUKLcQ":{"Type":"recursive"},"QmPQdVU1riwzijhCs1Lk6CHmDo4LpmwPPLuDauY3i8gSzL":{"Type":"recursive"},"QmPbxeGcXhYQQNgsC6a36dDyYUcHgMLnGKnF8pVFmGsvqi":{"Type":"recursive"},"QmPe1MqnkrZGD8uv2gjtNPr9UmkaixHMAbWXJwuegvKeL3":{"Type":"recursive"}}}} `

**Comment by lidel** [comment]
- This is similar to https://github.com/ipfs/ipfs-docs/issues/1480#issuecomment-1435763233 
- tldr docs are generated by https://github.com/ipfs/ipfs-docs/tree/main/tools/http-api-docs and it should be solved there

**Comment by ElPaisano** [comment]
RE Lidel's comment that this concerns https://github.com/ipfs/ipfs-docs/tree/main/tools/http-api-docs, which are generated from the Kubo docs, looks like this can be closed
