### ISSUE TITLE
Fix spelling errors found by Vale

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1354]
Wrote a bash script to run [vale](https://vale.sh/) with a minimal spell checking configuration against the main branch as of commit 3bc07b91126dbe10fe438002742328fcff8635ef

the spreadsheet with the results of the script is [here](https://docs.google.com/spreadsheets/d/1-9a5uQN0UGwL2A8MfSeAa9jvAzgAQkfrL7BB3KZ2M00/edit?usp=sharing)  (LMK if you can't access this)

Here's what I'm hoping we can do:
1. Open the spreadsheet
2. Look through each set of results (grouped by .md file)
3. Fix any actual spelling errors in a separate PR
4. For any of the words flagged that you are certain are not actually spelling errors but special PLN words lol, create a list of the words we need to update _accept.txt_  with. You can see version of _accept.txt_ that I used in this vale run by clicking on the link below (LMK if you can't access it). Note that _accept.txt_ supports regex.
5. For any words flagged that you're not sure about, add those to a separate list for us to discuss. 
6. Add each list as a comment on this PR
7. Once the results have been completely reviewed and we've created a list of words that need to be added to _accept.txt_, I'll update said file in https://github.com/ipfs/ipfs-docs/pull/1339 

**Vale config used:**
_accept.txt_
https://gist.github.com/ElPaisano/581d3a489c1e840d7aa9f80e2eb25866

_.vale.ini_
```
StylesPath = styles

Vocab = ipfs-docs-vocab

IgnoredScopes = code, tt

[*]
BasedOnStyles = Vale
```

_parse-spelling.sh_
```
#!/usr/bin/env 

for file in $(find ~/projects/ipfs-docs/docs/ -name "*.md")
do
	echo " "
	vale --config ~/.vale.ini --output line "$file" 
	echo " "
done
```

**Comment by TMoMoreau** [comment]
Hey @ElPaisano, I'm going through the spreadsheet and fixing any actual typos, also keeping track of any words that need to be added to the `accept.txt` file in the same spreadsheet. https://docs.google.com/spreadsheets/d/1-9a5uQN0UGwL2A8MfSeAa9jvAzgAQkfrL7BB3KZ2M00/edit#gid=1717557733

**Comment by TMoMoreau** [comment]
Also, PR for the fixes here: https://github.com/ipfs/ipfs-docs/pull/1358

Should I do one PR for each file, or one big PR for all the fixes?

**Comment by ElPaisano** [comment]
@TMoMoreau thanks for doing that.

I made a few comments in https://docs.google.com/spreadsheets/d/1-9a5uQN0UGwL2A8MfSeAa9jvAzgAQkfrL7BB3KZ2M00/edit#gid=1717557733

> Should I do one PR for each file, or one big PR for all the fixes?

One big PR is fine, just try and make each commit specific to a file i.e. each commit should fix typo(s) in one file only.  Easier to match the vale results that way. You can squash the PR when you push

> Quick question about Vale as well, does vale care about capitalization when it checks accept.txt?

It does. For example, you have to explicitly tell vale that both "ipfs" and "IPFS" are valid. The accept.txt file supports regex though, so it's manageable

**Comment by ElPaisano** [comment]
> Hey @ElPaisano, I'm going through the spreadsheet and fixing any actual typos, also keeping track of any words that need to be added to the `accept.txt` file in the same spreadsheet. https://docs.google.com/spreadsheets/d/1-9a5uQN0UGwL2A8MfSeAa9jvAzgAQkfrL7BB3KZ2M00/edit#gid=1717557733

@TMoMoreau looked at the spreadsheet but I don't see the list of words that we need to add to `accept.txt` anymore. Did you move it (or am I looking at the wrong spreadsheet)? I thought the list was in this spreadsheet?

**Comment by TMoMoreau** [comment]
Closing, completed. #1358
