### ISSUE TITLE
Need better Linux Packages support. (RPM, AppaImage etc..)

### ISSUE THREAD

**Issue by agompel** [ipfs/ipfs-docs#1355]
**Linux :** 

1. Please add .rpm based packages, working on redhat/fedora, (open)Suse, Mandrake Properly done that represent the bulk of the world Linuxes uses on file servers, science etc...
2. Ideally happimage, may be useful too : works on all Linuxes, a bit bulky though.
3. Containers : At this time (Dec-2022) too many of them, needs some consolidation, or ?

**Note :** 
Fedora and RedHat based are the favorite of Software technical people, MATE desktop for the same reason (Robust & frugal).

Thanks for the attention,

**Comment by TMoMoreau** [comment]
Hi @agompel! Correct me if I'm wrong, but this seems to be a request to have Kubo (go-ipfs) support more Linux distros, and not a request to update or change any of the current IPFS documentation. Could you please give more details of what you are requesting?

If this is a request to expand Kubo support to more Linux distros, please create an issue at https://github.com/ipfs/kubo/issues.
