### ISSUE TITLE
Reorg implementations page into 2 separate lists

### ISSUE THREAD

**Issue by TMoMoreau** [ipfs/ipfs-docs#1360]
Plan is to reorg the implementations page into two separate lists, one list at the top for actively maintained implementations, and another list below that to act as a sort of "grab bag" of legacy or deprecated implementations. Currently, all of the implementations are listed together.

https://docs.ipfs.tech/basics/ipfs-implementations/

**Comment by TMoMoreau** [comment]
What are we considering "active" when it comes to these implementations?

@2color would you consider Auspinner still "active"?

**Comment by 2color** [comment]
I wouldn't really consider it active. But it still works.

I think maybe setting the criteria of activity in the last 6 months might be a good bar for this

**Comment by ElPaisano** [comment]
@TMoMoreau can you link the PR for this?

**Comment by TMoMoreau** [comment]
No PR yet, will link it when it's up. PR will be up shortly.

**Comment by TMoMoreau** [comment]
@ElPaisano PR #1456
