### ISSUE TITLE
Update ipfs-update content

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1366]
EDITED

Re-scoped yet again based on triage of this issue, other site changes that have occurred in the last few months

1. Let's keep https://docs.ipfs.tech/how-to/ipfs-updater/ and https://docs.ipfs.tech/install/command-line/ separate, as they are separate things. ipfs-update is very Kubo-specific, so it helps to learn Kubo basics before learning about ipfs-update. A guide for a tool like ipfs-update makes most sense where it currently is given the existing site structure.
1. Point users to ipfs-update at the end of [https://docs.ipfs.tech/install/command-line/ ](https://docs.ipfs.tech/install/command-line/) as a logical follow up now that they know how to install Kubo manually.
1. Rewrite https://docs.ipfs.tech/how-to/ipfs-updater/ for general cleanup and to clarify a few points. Also, reformat it to look like the rest of the page i.e. tab boxes by OS

**Comment by TMoMoreau** [comment]
@ElPaisano Any new thoughts about this?

**Comment by ElPaisano** [comment]
@TMoMoreau yep just updated the description, take a look. What do you think of the proposal?

**Comment by ElPaisano** [comment]
https://github.com/ipfs/ipfs-docs/pull/1555 addresses thi
