### ISSUE TITLE
Rewrite introduction page to better capture what IPFS is

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1368]
From @2color 

> IPFS is not a storage solution. Instead, it's a set of protocols for routing and transferring content-addressed data (IPLD).
>
> Unfortunately, this misconception is kept alive by [our very own introduction docs page](https://docs.ipfs.tech/concepts/what-is-ipfs/)

Full comment here https://github.com/ipfs/ipfs-docs/pull/1363#discussion_r1047049575

This will be addressed in the docs reorg and migration, but we should ideally address this beforehand by making some basic edits to intro page so that we are accurately conveying what IPFS is (and isn't)

**Comment by ElPaisano** [comment]
@TMoMoreau will make a PR for this.

**Comment by TMoMoreau** [comment]
Closing this issue in favour of this new one: #1434
