### ISSUE TITLE
Outdated "Build with OpenSSL" recommendation for lowpower profile

### ISSUE THREAD

**Issue by Arlodotexe** [ipfs/ipfs-docs#1378]
In [this](https://ipfs.io/ipfs/QmTgDofBjgS88zsUAXBj22WUkdng4XFTyNJt46izMboB2p/install/command-line/#system-requirements) document, under the section "Kubo on resource-constrained systems", it recommends rebuilding with OpenSSL before using the `lowpower` profile.

![image](https://user-images.githubusercontent.com/9384894/208003134-eeeadf62-419b-4382-b61f-d98509cbe0a9.png)

**Comment by Arlodotexe** [comment]
cc @Jorropo

**Comment by ElPaisano** [comment]
@Arlodotexe thanks for submitting this issue. 

Could you give some more context? Does the recommendation for resource constrained systems to install OpenSSL and rebuild Kubo manually before initializing with the lowpower profile no longer apply? Is a step incorrect? Please clarify

**Comment by Jorropo** [comment]
@ElPaisano this is only relevant if you are running an RSA peer id which are not default since sep 2020 and can actually make your system slower.

**Comment by ElPaisano** [comment]
@Jorropo thanks for the clarification. I based those instructions on what was previously in the docs, so I guess those instructions are really outdated.

To address this, I opened https://github.com/ipfs/ipfs-docs/pull/1383 and set you as the reviewer. Can you take a look and lmk if the copy change addresses this? If there's more changes needed, please comment on the PR. Thanks.
