### ISSUE TITLE
404ing link on case-study-snapshot.md , not sure where it should go

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1381]
Line 106 of case-study-snapshot.md has a link https://github.com/snapshot-labs/snapshot-hub/blob/master/src/helpers/schema.sql that is 404ing. So, either need to remove / rewrite this copy so that it doesn't reference said link, or figure out where the link should go.

A search of the repo yields https://github.com/snapshot-labs/snapshot-hub/blob/master/src/graphql/schema.gql. Wondering if this is the right link and it just got moved?

```
> **Note:** Even though MySQL is used for querying, all data stored on MySQL is available on IPFS. [Tables in the database schema](https://github.com/snapshot-labs/snapshot-hub/blob/master/src/helpers/schema.sql) have an `ipfs` field holding the IPFS CID.
```

**Comment by 2color** [comment]
We can just remove the link. Looks like it was removed from the repo
