### ISSUE TITLE
https://docs.ipfs.tech/how-to/peering-with-content-providers/#protocol-labs incorrectly lists 3 `nft-storage` addresses

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1394]
Issue reported by @2color 

The last 3 entries in https://docs.ipfs.tech/how-to/peering-with-content-providers/#protocol-labs incorrectly list 3 `nft-storage` addresses. These should, at a bare minimum, be removed from this table. 

Suggestion:

Create table under https://docs.ipfs.tech/how-to/peering-with-content-providers/#nft-storage header, populate said table with contents in https://github.com/nftstorage/nft.storage/blob/main/PEERS plus the nft.storage addresses listed in the last 3 rows of https://docs.ipfs.tech/how-to/peering-with-content-providers/#protocol-labs. Should also verify that all addresses listed in https://github.com/nftstorage/nft.storage/blob/main/PEERS plus the 3 incorrectly listed under the Protocol Labs header actually still work and are valid

**Comment by ElPaisano** [comment]
@2color lmk if I captured this issue correctly. What do you think about the suggested fix? Was based on yours and Johnnys convo

**Comment by 2color** [comment]
Looks good. Regarding the Protocol Labs ones, I'm waiting for an answer from the Netops team: https://github.com/protocol/bifrost-infra/issues/2254

**Comment by ElPaisano** [comment]
Who would be a good contact for the nft.storage team? Or a suggested slack channel @2color
