### ISSUE TITLE
/api/v0/key/export doesn't exist

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/ipfs-docs#1397]
Kubo apparently doesn't have an `/api/v0/key/export` endpoint (even though it'd be *incredibly* useful): https://github.com/ipfs/kubo/issues/8327#issuecomment-893450924

Docs entry: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-key-export

**Comment by TMoMoreau** [comment]
So, should `/api/v0/key/export` be taken out of the docs completely? Or would it be better to leave it in there, but add a note saying that it doesn't have an endpoint and will always fail.

**Comment by TheDiscordian** [comment]
@TMoMoreau I think it should be omitted from the RPC API, as it doesn't appear to be a part of the RPC API.

**Comment by TheDiscordian** [comment]
Maybe we should just omit everything with `NoRemote: true`: https://github.com/ipfs/kubo/blob/e550d9e4761ea394357c413c02ade142c0dea88c/core/commands/keystore.go#L172

**Comment by TMoMoreau** [comment]
@lidel do you have any thoughts about this issue?

**Comment by hacdias** [comment]
@TMoMoreau I think that changing this can be done by adding a `|| cmd.NoRemote` to this line: https://github.com/ipfs/ipfs-docs/blob/main/tools/http-api-docs/endpoints.go#L101. That will ignore all the endpoints that are not available as a remote RPC command.
