### ISSUE TITLE
Vuepress is now in maintenance mode

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1419]
Per https://github.com/vuejs/vuepress#status, Vuepress, the current ipfs-docs site generator, is now in maintenance mode.

So, we should probably decide on a new static site generator to migrate to, and do it sooner rather than later

**Comment by johnnymatthews** [comment]
Just leaving a comment here to say: although it's kinda annoying that VuePress isn't going to be update much anymore, it's not going to explode or completely fall apart at anytime soon. Maintenance mode is exactly that, the project is just gonna get maintenance updates -- we can still rely on the project to exist, and apply security updates where necessary.

TLDR: we don't have to migrate away from VuePress right this second. We've got a some time.
