### ISSUE TITLE
Add Pin Files page/section to Getting Started section which shows how to pin a file using Web3.storage

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1421]
As a next step after the reorg currently in progress https://github.com/ipfs/ipfs-docs/pull/1405, add Pin Files page/section to Getting Started section which shows how to pin a file using Web3.storage

Todo: Figure out 
- what content lives in this new page/section
- should this be a page or a section with multiple pages
- what are the goal(s) of this page / section i.e. how does it help the reader / what problem does it solve?

**Comment by ElPaisano** [comment]
@2color created this issue as discussed, lmk if this is accurate

**Comment by 2color** [comment]
<img width="262" alt="Screenshot 2023-01-30 at 6 31 42 PM" src="https://user-images.githubusercontent.com/1992255/215550852-4e3235c9-ce22-43a5-b722-9f1ad1a19260.png">


I would put this a new Publish category in the getting started section and, under it, add a new page — "Publishing to IPFS with a Pinning Service" 

The goal for the reader should be:
- Get the user to import a file via the UI
- Get a CID (Content addressing — permanent address) for the file
- Load the CID from multiple gateways to demonstrate content addressing

It should give a user a quick win in the shortest time.
