### ISSUE TITLE
[CONTENT REQUEST] How to setup port forward with kubo

### ISSUE THREAD

**Issue by Jorropo** [ipfs/ipfs-docs#1424]
This is a somewhat involved task which can trip even experienced network enginers because it's not as easy as it seems.
Here is the outline of the page (please make it better, info is great but not my writings :D )

# Why doing this ?

Having a reachable node is a critical part for people being able to download content from your node.
If you are behind a NAT such as for residential network, other nodes on internet cannot directly talk to you, we need to "open a port" from your :
We have multiple ways for this to happen automatically.
- Upnp (notes to writers: add link to wikipedia upnp page)
  This is a magic solution where Kubo does the portforward magically for you, that is not supported and or enabled by default on many routers.
- DCUTR Holepunching (notes to writers: add link to libp2p holepunching docs and or blog post)
  This is a trick where your router gets confused and accepts connections even tho it shouldn't, however all connections must all go through a relay first (which add ~5s delay when someone connects to you, when a direct connection is established performance is as normal) and this does not have 100% success rate (different routers models react differently).

If your router does not have UPNP or you want better reliability and performance than what DCUTR provides, you will need to setup a manual portfward.
This process have two steps:
1. Open a Port from the outside internet to your internal kubo node.
    This will make your node "physically" reachable however is not good enough to be reachable on the IPFS network.
2. Configure `Swarm.AppendAnnounce` (notes for writers: link to kubo's config documentation file) Kubo field.
    This is a list of addresses that other nodes will try to contact you with, this allows other nodes on the network that the port forward you created in step 1 exists.

# 1.

(notes to writers: Sadly this part is router dependent but they all look the same, either link some great tutorial somewhere, give some googling tips (`how to open port with XXX router` where `XXX` is your ISP), ...)

You need to select an outside port (use 4001 if you don't know what to pick) and redirect both tcp and udp traffic to your local machine port 4001.
You will need two informations from this step, 1. your public IP address, 2. some outside port you have choosen.

# 2.

Add thoses configs to the kubo config:
```json
"AppendAnnounce": [
  "/ip4/1.2.3.4/tcp/12345",
  "/ip4/1.2.3.4/udp/12345/quic",
  "/ip4/1.2.3.4/udp/12345/quic-v1",
  "/ip4/1.2.3.4/udp/12345/quic-v1/webtransport",
]
```
Where `1.2.3.4` is your public IP address, and `12345` the port you've choosen.
Then restart kubo, you should be reachable.
(notes to writers: add a link to something like ipfs check where users can see if the outside port is indeed open)

**Comment by ElPaisano** [comment]
@Jorropo looking over this now, thanks for creating

**Comment by ElPaisano** [comment]
Hey @Jorropo long story short, looks like we have a page that explains some of this info. I created an initial PR to update it with this info https://github.com/ipfs/ipfs-docs/pull/1425. Can you take a look? I have a few questions
