### ISSUE TITLE
Peering with content providers: Protocol Labs and NFT.storage addresses are invalid

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs/ipfs-docs#1429]
...and they also don't seem to be in use anymore:

```
ipfs dht findpeer QmUEMvxS2e7iDrereVYc5SWPauXPyNwxcy9BXZrC1QTcHE QmNSYxZAiJHeLdkBg38roksAR9So7Y5eojks1yjEcUtZ7i <...>
<no output>
```

Could someone from the infra team please provide a way to get the authoritative addresses? i'd like to link to the ipfs.io provider to make my content quicker to load

**Comment by ShadowJonathan** [comment]
cc @mikeal, since i saw you adding these in https://github.com/ipfs/ipfs-docs/issues/754

**Comment by TMoMoreau** [comment]
@ElPaisano I'm going to leave this issue up, as it seems we still need to find the authoritative addresses for both PL and NFT.Storage.

If I'm wrong in this assumption, feel free to close.

**Comment by ShadowJonathan** [comment]
Nah that's fine, thank you

**Comment by ElPaisano** [comment]
@johnnymatthews I can take this one

**Comment by ElPaisano** [comment]
https://github.com/ipfs/ipfs-docs/pull/1395 (merged) seems to address this, so I'm closing this out. Please reopen if that's the case

**Comment by ShadowJonathan** [comment]
@ElPaisano #1395 was meant to remove the incorrect addresses, yes, but I opened this issue to find the correct addresses again, especially the PL ones.
