### ISSUE TITLE
Audit and rewrite Concepts page for libP2P

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1431]
Epic: https://github.com/ipfs/ipfs-docs/issues/1432

Tasks:

- [ ] Read through https://docs.ipfs.tech/concepts/libp2p/
- [ ] Note any of the following:
       - Outdated content
       - Incorrect content
       - Missing content
       - Confusing  / misleading content
       - Broken links / links that should probably go somewhere else
       - Anything else that can be improved
- [ ] Create PR to fix issues found during audit

**Comment by ElPaisano** [comment]
One bit thing is here is to make sure we are using the same language as the updated libp2p site

**Comment by ElPaisano** [comment]
@DannyS03 can you link the PR for this once you kick it off?

**Comment by ElPaisano** [comment]
Hey @DannyS03 when you have a sec, can you add a milestone to this PR based on when you think you'll have it done by?

![image](https://user-images.githubusercontent.com/113373882/214724719-4ca784f7-31b4-4220-a143-c20e1f258a21.png)

This is part of trying to estimate and keep track of what updates will land when, and makes https://github.com/ipfs/ipfs-docs/projects/8 easier to parse. IDK if these will be useful in the long run, but I'd like to give them a try

**Comment by DannyS03** [comment]
hey @ElPaisano, sure - added the already created milestone for this week (will open a PR tomorrow).

**Comment by ElPaisano** [comment]
> hey @ElPaisano, sure - added the already created milestone for this week (will open a PR tomorrow).

Thank s @DannyS03 corrected the dates there, hopefully PRs in this milestone are not open until 1/20/27 😅

**Comment by ElPaisano** [comment]
Hey @DannyS03 doing monday morning triage for open issues - any updates on this one?

**Comment by DannyS03** [comment]
Hey @ElPaisano, sorry, finishing this up today.

**Comment by ElPaisano** [comment]
no worries at all, thanks for writing this @DannyS03. Can you add me as the copy review for the PR once it's ready?

**Comment by ElPaisano** [comment]
@DannyS03 sorry we didn't get to discuss this in the ipfs docs working group, lmk if you need anything / have updates
