### ISSUE TITLE
Add videos about apps from IPFS camp to the usage ideas & examples page to showcase advanced app architectures using IPFS

### ISSUE THREAD

**Issue by 2color** [ipfs/ipfs-docs#1441]
## Background
There's a broad category of apps that use parts of IPFS as part of an advanced p2p architecture that usually combines decentralised identity building blocks and so on.

Examples include Bluesky, Minnter, Subconscious, Satellite, Berty, and Disco Chat. (by no means exhaustive)

-- 

## Proposal

Add a new page, or restructure the now mostly outdated [Usage ideas & examples](https://docs.ipfs.tech/concepts/usage-ideas-examples/) to include some of these projects with video embeds from IPFS Camp ([201 playlist](https://www.youtube.com/watch?v=lU751rXQcjI&list=PLuhRWgmPaHtRP0kfWyDuod_kVHE-5dGGL), [satellite](https://www.youtube.com/watch?v=baqWhUACUAg))

Ideally, we'd also include some copy and diagrams, but an initial pass can be a collection of all such advanced use cases.

**Comment by ElPaisano** [comment]
My vote would be to update the existing https://docs.ipfs.tech/concepts/usage-ideas-examples/ so that we don't keep adding more pages into the docs (since we already have a lot and are trying to prune them down)

**Comment by 2color** [comment]
Yeah I would say that initially we'd add these to the usage examples page so that the page reflects the current state of things. An individual page for each of these in the case studies might require a fair bit of work if it's to meet the current baseline.
