### ISSUE TITLE
rust-ipfs is no longer maintained, update docs 

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1447]
It appears that [rust-ipfs is no longer maintained](https://github.com/rs-ipfs/rust-ipfs#project-status---alpha-not-maintained), so we should probably remove mentions of it from the docs accordingly. 

## Note

https://github.com/ipfs/ipfs-docs/pull/1446 (currently in progress) removes at least one mention of rust-ipfs

**Comment by ElPaisano** [comment]
@TMoMoreau changed a few labels:

- I think this is something we should do since the project is definitely no longer maintained
- I don't think this should take multiple days, I would estimate hours

I think this could be addressed in a single PR:
- [ ] Search for all links to the project repo and all instances of `rust-ipfs` 
- [ ] In most cases, can probably remove the link. In some cases, maybe just update the description to let the reader know the project is no longer maintained - the link or mention in the context of the page it's in should be helpful in determining what needs to be done

**Comment by TMoMoreau** [comment]
@ElPaisano Good call, unsure what I had in mind when I selected days instead of hours. Opened a PR to update the most obvious mention of `rust-ipfs`. #1451 

There's likely to be more, I'll crawl around to find out and add them to the same PR when found.

**Comment by ElPaisano** [comment]
> @ElPaisano Good call, unsure what I had in mind when I selected days instead of hours. Opened a PR to update the most obvious mention of `rust-ipfs`. #1451
> 
> There's likely to be more, I'll crawl around to find out and add them to the same PR when found.

@TMoMoreau cheers thanks for taking this on

**Comment by TMoMoreau** [comment]
Note that the most recent comment on that PR points out that it will be useless once I'm finished with this issue: #1360 which I have now started on.
