### ISSUE TITLE
Phishing issues

### ISSUE THREAD

**Issue by marinsagovac** [ipfs/ipfs-docs#1455]
There are phishing scams on your sites to steal cpanel passwords from users.

There are trying to redirect to url shortener and it redirects to IPFS for stealing password.

A developers uses to create phishing sites and try to steal password.

Please where can I send mail for abuse issue on your site?

Thank you.

Mail looks like:

some@email.ltd  removal from  ltd.com  server has been approved and initiated,

Due to ignorance of the last verification warning. Removal will occur in exactly 48 hours (28 Jan 2023)   from now (25 Jan 2023)
 We recommend that you do any of the below and protect your mailbox 

CONTINUE REMOVAL  - this links goes to IPFS on Phishing and steal password (cpanel like site, phishing site)
CANCEL REMOVAL - same URL as above

**Comment by TMoMoreau** [comment]
Please send a report of this abuse to abuse@ipfs.io
