### ISSUE TITLE
Rewrite "Simple chat app" tutorial

### ISSUE THREAD

**Issue by 2color** [ipfs/ipfs-docs#1459]
## Background 

The impressive peer-to-peer chat app guide that @TheDiscordian created is no longer functional for several reasons:
- bug in the [Circuit Relay V1 daemon](https://github.com/libp2p/go-libp2p-relay-daemon/issues/18)
- https://github.com/libp2p/js-libp2p-webrtc-star/ is no longer maintained

Both impose severe impediments on browser-to-browser connectivity with libp2p — which, as it stands, is currently unsupported https://github.com/libp2p/js-libp2p/issues/1462.

## What can we do?

Informing readers about the limitation is vital here — let's ensure we set the right expectations. 

May be helpful to link to the [libp2p connectivity page](https://connectivity.libp2p.io/) for this.

**Comment by 2color** [comment]
> The guide is useful, but it's not really useful today because the things it talks about don't really work anymore.

My suggestion would be to remove it for now (with a heavy heart because it was such a great example). We still have it on the blog, but by being in the docs, we're setting users up for failure. 

In the mid-term, I'd suggest we follow the work on Helia and CircuitRelayV2 for browser-to-browser connectivity. Once we have some more tooling to do browser-to-browser connectivity maybe we can overhaul the guide.

**Comment by ElPaisano** [comment]
Step 1: Suggestion is to remove this tutorial
Step 2: @TMoMoreau to sync with @TheDiscordian about new tutorial, blog post

**Comment by ElPaisano** [comment]
@TMoMoreau I think that Step 1 (remove the outdated tutorial, and maybe add a redirect somewhere so that it doesn't just 404) should be done as soon as possible, since it's outdated. Is that something you think you can get to today? Then, can work on Step 2 a little more leisurely

**Comment by ElPaisano** [comment]
Suggestion:
- add banner about tutorial being "archived"
- Remove from main site navigation but don't delete
- Redirect away from this page for the moment

**Comment by ElPaisano** [comment]
Update: https://github.com/ipfs/ipfs-docs/pull/1466 should address Part 1 of this, so we can just leave the tutorial as is for the moment.

**Comment by TMoMoreau** [comment]
With step 1 of this issue finished, I added new labels for step 2.

- [x] Add banner/warning to the current tutorial indicating that it is outdated.
- [ ] Create new tutorial that will actually work if someone tries to follow it.

Unsure about the priority of the second step at the moment, this can be discussed here or in a sync.

**Comment by 2color** [comment]
Closing this in favour of https://github.com/libp2p/universal-connectivity/issues/1
