### ISSUE TITLE
IPFS for JavaScript (js-ipfs)

### ISSUE THREAD

**Issue by whAkira** [ipfs/ipfs-docs#1464]
Nothing works, you need to find fix on every code piece

```
import { create } from 'ipfs-http-client'

const client = create() // the default API address http://localhost:5001
```

returns

```
cause: Error: connect ECONNREFUSED ::1:5001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5001
  }
}
```

**Comment by 2color** [comment]
It sounds like you've had a frustrating experience. However, we need more information to help you. Moreover, flaming and using an abusive tone is not in the spirit of our [Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md#friendly-harassment-free-space). 

Please update the description of this issue with some more context on what you are trying to do, the problem you are facing, and reproduction information.

FYI, The [`ipfs-http-client`](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client) is intended as a client for a long running js-ipfs node. In your case you need to also have have js-ipfs node running, i.e. `ipfs daemon`.
