### ISSUE TITLE
[DOCS ISSUE] (ipns not working)

### ISSUE THREAD

**Issue by srem1** [ipfs/ipfs-docs#1474]
I publish my site and it is not apear in network.
for example 
https://ipfs.io/ipns/k51qzi5uqu5dltd25mh4mbpenvt48ogf896tmzwps60sdsifmh6jbsi5nc432x

it resolve ipfs but ipfs.io not show it.

**Comment by ElPaisano** [comment]
@srem1 thank you for submitting an issue to the ipfs-docs repository. I'm sorry to hear that you are having trouble publishing and resolving a site with IPFS.

The ipfs-docs repository Issues are generally for documentation-specific issues. I will go ahead and close this issue, and direct you to [the instructions for getting technical support and help in the IPFS forum](https://docs.ipfs.tech/community/#get-technical-support-and-help), which should provide the quickest resolution to your issue.
