### ISSUE TITLE
Host a single-page website on IPFS -> Content Security Policy block external resources API

### ISSUE THREAD

**Issue by yoyorasco** [ipfs/ipfs-docs#1481]
I have a HTML with JS code that calls the OpenWeatherMap API. After uploading to IPFS and pinning with Pinata, when I access the gateway link with CID, I get this error in the web console:

Content Security Policy: The page’s settings blocked the loading of a resource at http://api.openweathermap.org/data/2.5/weather?q=Jakarta&appid=1b848da3daeeb21c80e6626b77a67cbd&units=metric&lang=en (“default-src”).

Can someone help me resolve this?
Thank you.

**Comment by 2color** [comment]
Hey @yoyorasco,

See [this docs page](https://docs.ipfs.tech/community/#get-technical-support-and-help) on the best way to get help. The TL;DR is that the docs issues aren't the place for help, but you can ask on the [IPFS Forum](discuss.ipfs.tech)
