### ISSUE TITLE
Pin files

### ISSUE THREAD

**Issue by rayswchiu** [ipfs/ipfs-docs#1486]
i have a very simple question: when i removed a folder with pinned files in it, do all the pinned files get garbage collected?

**Comment by 2color** [comment]
Hey @rayswchiu,

See [this docs page](https://docs.ipfs.tech/community/#get-technical-support-and-help) for the best way to get help. The docs issues aren't the place to ask for help. You can ask on the [IPFS Forum](https://github.com/ipfs/ipfs-docs/issues/discuss.ipfs.tech).
