### ISSUE TITLE
Add documentation troubleshooting / investigation tools

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1491]
From @mishmosh and @2color:

We need to add in documentation on various troubleshooting/investigation tools like CID checkers, etc.. List is below:

[IPLD Explorer](https://explore.ipld.io/)
[IPFS check](https://check.ipfs.network/)
[CID inspector](http://cid.ipfs.tech/)
IPFS [Gateway Checker](https://ipfs.github.io/public-gateway-checker/)
[DAG builder visualiser](https://dag.ipfs.tech/)
[CAR Builder](https://car.ipfs.io/)
https://github.com/laurentsenta/pl-diagnose/
[PL Diagnose tools](https://pl-diagnose.on.fleek.co/) (edited)

![image](https://user-images.githubusercontent.com/113373882/218886690-95ed4d1d-6231-47e3-b34c-4e04fabbd73c.png)

**Comment by mishmosh** [comment]
Thanks for turning this into an issue @ElPaisano. Maybe it can live in the **Reference** section, under a new 2nd-level section called **Troubleshooting Tools** or **Diagnostic Tools**? (If that's not too long.)
