### ISSUE TITLE
Content addressing and CIDs

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-docs#1492]
## Description 

it would be nice if the https://docs.ipfs.tech/concepts/content-addressing/#cid-conversion page had instructions on how to parse a CID. 

### Problem statement

I have a CID, `bafyreihnpl7ami7esahkfdnemm6idx4r2n6u3apmtcrxlqwuapgjsciihy`, and I am able to determine it's codec, multibase, multihash, etc, but I want to access the raw content stored within this CID. How do I do that?

### Other resources

https://proto.school/anatomy-of-a-cid/04 has some information about the structure of a CID, and how you can "unwrap" a CID, but doesn't give explicit instructions and most steps in the process have to be deduced.

**Comment by 2color** [comment]
Thanks for reporting this! This is something that we've started working on: 
- https://github.com/ipfs/ipfs-docs/pull/1467
- https://github.com/ipfs/ipfs-docs/pull/1476

https://bafybeieedkoyq4lndzqv6sfnqcm67lwklrk7yltfvz6aupnzluoby7ibxi.on.fleek.co/concepts/content-addressing/#cid-versions
