### ISSUE TITLE
kad-dht content routing documentation

### ISSUE THREAD

**Issue by p-shahi** [ipfs/ipfs-docs#1499]
We decided to close https://github.com/libp2p/docs/pull/293 in the libp2p documentation. If appropriate, it should be added here

**Comment by johnnymatthews** [comment]
The PR in question isn't structured enough for an immediate merge into IPFS Docs. I'm going to close this. If, it turns out, that the libp2p team or IPFS team requires something similar to this PR, we can create a new issue to track that.
