### ISSUE TITLE
[OUTDATED DATA] Request on updating latest Snapshot.org metrics

### ISSUE THREAD

**Issue by sscrsh** [ipfs/ipfs-docs#1517]
The metrics in this case study was from August 2022 
https://docs.ipfs.tech/case-studies/snapshot/#ipfs-benefits

As of Nov 2022, Snapshot has registered 11K+ spaces (projects), which covers 95% in the wild DAOs. Can we update their current performance? I'm doing a deep dive about the potential investment inflow into the DAO tooling landscape, would be great to collaborate.

**Comment by 2color** [comment]
Feel free to submit a PR. The source file for the case study is: https://github.com/ipfs/ipfs-docs/blob/main/docs/case-studies/snapshot.md

**Comment by ElPaisano** [comment]
@sscrsh as there has been no response, I am closing this issue. Please reopen if you would like https://docs.ipfs.tech/case-studies/snapshot/#ipfs-benefits updated. As @2color mentioned, you can also create a PR directly. Thank you
