### ISSUE TITLE
How to delete file from IPFS using ReactJs / NodeJs

### ISSUE THREAD

**Issue by sunilaarchik** [ipfs/ipfs-docs#1519]
For a long time, I'm trying to find solutions for How to delete files from IPFS using ReactJs OR NodeJs? but still, I do have not any solutions.

I tried many plugins but not working it.
- https://www.npmjs.com/package/ipfs
- https://www.npmjs.com/package/ipfs-client
- https://www.npmjs.com/package/react-ipfs-uploader
- https://www.npmjs.com/package/react-ipfs

Can you please help me? It is very important for me.

**Comment by 2color** [comment]
IPFS-related questions belong in the [IPFS forums](https://discuss.ipfs.tech/).
