### ISSUE TITLE
Remove outdated implementation status page

### ISSUE THREAD

**Issue by mishmosh** [ipfs/ipfs-docs#1564]
The [project/implementation-status page](https://docs.ipfs.tech/project/implementation-status/) uses the outdated dichotomy of go vs. js impls. Two possibilities:

- Delete this page altogether
- Update and move it to Reference section. The endpoints table seems like a useful structure. If we want to keep that (and update for kubo & other impls), it should probably move to the Reference section.

Thoughts @BigLep @lidel @autonome @ElPaisano?

**Comment by lidel** [comment]
My vote is to remove it -- it creates impression that Kubo CLI / RPC defines what IPFS is. 

Instead, we want to have more specs at https://specs.ipfs.tech and a table that shows which spec is implemented by what (but we need to have more specs in presentable state first).

cc @darobin

**Comment by darobin** [comment]
If we can, I would like to avoid a manually maintained table because it's guaranteed to go stale. We should be driving this from test suite results :)

**Comment by BigLep** [comment]
Completely agreed on removing it.  This seems like an artifact of the "core API" where there was a goal of striving for API compatibility between go-ipfs and js-ipfs.

**Comment by ElPaisano** [comment]
This makes sense 👍 I'll review https://github.com/ipfs/ipfs-docs/pull/1567
