### ISSUE TITLE
Link out to spec site https://specs.ipfs.tech/ after impl page removal

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1569]
Came out of https://github.com/ipfs/ipfs-docs/pull/1567 <- in 1567, we are removing outdated / manually written Implementation status page.

This issue is the followup for that, where we add links out to the spec and call it done

Relevant conversation from 1567

- _Instead, we want to have more specs at https://specs.ipfs.tech/ and a table that shows which spec is implemented by what (but we need to have more specs in presentable state first)._
- _Manually maintained tables are likely to go stale. Things like this should be driven from test suite results._

**Comment by ElPaisano** [comment]
cc @mishmosh @BigLep

**Comment by johnnymatthews** [comment]
> Add links out to the spec and call it done

Due to the general lack of bandwidth across the IPFS team, I'd recommend that we simply link out to the spec site.

**Comment by ElPaisano** [comment]
@johnnymatthews I like the idea of keeping it simple for now by just adding the link in. Later, I do think an automation should be added in though. 

I'll take this issue and add the link in

**Comment by ElPaisano** [comment]
Ok, I'm going to close this for the following reason:

So, for the moment we are still using the manually-created implementations page. We just made another update https://github.com/ipfs/ipfs-docs/pull/1612.  Will reopen if we decide to automate. See https://github.com/ipfs/ipfs-docs/issues/1607#issuecomment-1571325655 for context
