### ISSUE TITLE
Address IPFS on the Web

### ISSUE THREAD

**Issue by yfthomsen** [ipfs/ipfs-docs#1574]
Hello, 

We were asked by the company Vion Food Group to assist with respect to trademark matters in domain or other online issues. Vion Food Group recently became aware that a website hosted by your company is being used to impersonate the official Vion Food Group website. 
The Vion Food Group website can be accessed here https://www.vionfoodgroup.com/en/.

We have reported the phishing urls hosted by your company several times but no actions have been taken. Please investigate them and take down the phishing URLS. 

https://bafybeig5bh4eqnlw5j6dec5icalr4toipbqlpwbetqatlpat6nvjxmatwa.ipfs.dweb.link/ref.html?email=leon.abbitt@vionfood.com 
https://bafybeieuxrulkatdthsofjvrrae2wmbkgiisaas7vbh6tggincquzutjv4.ipfs.dweb.link/?filename=QmYMFgKNZeVMCX3h2CQ2C17iQneaFqYNtsUc5DfF7uZqVQ#max.de.jong@vionfood.com
https://bafybeigbh2hhq6giieo6pnozs6oi3n7x57wn5arfvgtl2hf2zuf65y6z7y.ipfs.dweb.link/?filename=index.html&err=ZZIEBN5O0UOGQDGJP5J&dispatch=81B&id=35BB4165a55b5c0c9C394A0A278cC2#info@vionfood.com

Thank you for your assistance. 

Best regards,

Thomsen Trampedach GmbH

**Comment by johnnymatthews** [comment]
Hi there. Please forward abuse requests to abuse@ipfs.io. Thanks.
