### ISSUE TITLE
404 to "Delegated Content Routing HTTP API spec" link

### ISSUE THREAD

**Issue by lucagiorgino** [ipfs/ipfs-docs#1578]
In Learn more box [Delegated Content Routing HTTP API spec](https://docs.ipfs.tech/concepts/how-ipfs-works/#how-ipfs-transfers-data) link points to https://github.com/ipfs/specs/blob/main/routing/DELEGATED_CONTENT_ROUTING_HTTP.md which returns a 404

**Comment by johnnymatthews** [comment]
Hmm, [looks like it got moved](https://github.com/ipfs/specs/blob/81568284d17844f05a36f478ca98019025bec42b/IPIP/0337-delegated-routing-http-api.md?plain=1#L3):

```
# IPIP-337: Delegated Content Routing HTTP API

Moved to https://specs.ipfs.tech/ipips/ipip-0337/
```

Tasks

- [ ] Update the link referenced by @lucagiorgino to `https://specs.ipfs.tech/ipips/ipip-0337/`.
