### ISSUE TITLE
Subdomains Being Used In Various Levels of Malicious Phishing Attacks

### ISSUE THREAD

**Issue by cknothe-OUC** [ipfs/ipfs-docs#1579]
Our organization has recently received a series of emails in which attackers are performing phishing campaigns via use of subdomains within the ipfs.dweb.link domain.  This campaigns are leveraging the use of IPFS to present what appears as an html file.  Accessing this results in the presentation of a webpage that appears to be an Outlook.com login prompt.  Scrutiny of this further reflects that the attacker is taking information provided by the users and passing it Outlook.com in a man-in-the-middle attack to validate if legitimate, working credentials are supplied by the victim.

Neither IPFS.tech nor your parent Protocol Labs website presents a clear communication mechanism by which organizations such as ours can quickly and securely report abuse of your platform.

We would like to provide additional details of this incident in a private manner.  After review of the open issue log, we suspect issue #1574 is a similar attack on Vion Food Groups in which the attackers are successfully using Vion's company logos to further trick unsuspecting victims into providing credential information.

The matter of malicious phishing abuse by means of your platform requires urgent attention.

**Comment by ExTechOp** [comment]
This is unfortunately a long-standing issue (see eg. #1541) with no clear resolution.
The official abuse reporting email address is abuse@ipfs.io, but the response time with this is quite bad, unfortunately my impression is that someone looks at that when they have some spare time.

**Comment by johnnymatthews** [comment]
@ExTechOp is correct, the abuse reposting email address is abuse@ipfs.io. Unfortunately, this is a matter that only the IPFS legal team is allowed to address. The docs team have no input here.
