### ISSUE TITLE
[DOCS ISSUE] (add your title here!)

### ISSUE THREAD

**Issue by 3SW-nw** [ipfs/ipfs-docs#1592]
I get so much fraud about this ... platform. Nearly every month some great scriptboy try to ditch me. 

It make me so angry, that I do not find any spot to get in touch with this plaform. Seems, that they do not care who is using the platform and for what reason. 

Thank you for supporting hacking and scaming! 

https://ipfs.io/ipfs/bafybeidb665oreh25iwg223tmlgirj2ex6obbrzqqv5i344xackemidanu

**Comment by johnnymatthews** [comment]
Thanks for raising. Please email abuse@ipfs.io with details.
