### ISSUE TITLE
Clarify ipfs desktop release intsructions

### ISSUE THREAD

**Issue by jfalch** [ipfs/ipfs-docs#1595]
there does not appear to be a windows installer for ipfs desktop in [releases directory](https://github.com/ipfs/ipfs-desktop/releases) (..setup.exe), contrary to [docs](https://docs.ipfs.tech/install/ipfs-desktop/#windows).
where can i find a windows installer ? or do i have to use kubo ?

**Comment by ElPaisano** [comment]
@jfalch thansk for taking the time to read the docs and open a helpful issue. Apologies for the confusion here. The new windows release is called `IPFS-Desktop-Setup-0.28.0.exe` and is listed in https://github.com/ipfs/ipfs-desktop/releases near the bottom of the 0.28.0 section. We will update the docs accordingly.

Looking at the ipfs-desktop README, I found this https://github.com/ipfs/ipfs-desktop#windows. Copied out here for your information.

---------------

Windows
Installer: [IPFS-Desktop-Setup-0.28.0.exe](https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.28.0/IPFS-Desktop-Setup-0.28.0.exe)

Chocolatey (community-maintained): choco install ipfs-desktop
Scoop (community-maintained): scoop bucket add extras; scoop install extras/ipfs-desktop
WinGet (community-maintained): winget install IPFS.IPFS-Desktop

**Comment by ElPaisano** [comment]
@jfalch I am closing this issue, as we have not heard back. Please reopen the issue or create a new one if you need further assistance. Thank you
