### ISSUE TITLE
Report IPFS URL Fishing

### ISSUE THREAD

**Issue by eagle00789** [ipfs/ipfs-docs#1603]
In the documentation there is not a single page on how to report fishing/spam links to have them taken down as they can potentially cause a lot of harm like this one i received by mail: https://bafybeifz2pfnhsnc2rj2ygthjzodbb5j3ywje5w72dpi53oimhzc5bucme.ipfs.dweb.link/W3MDX5.htm?email=fuck@you.com <my emailaddress is changed in this url for my privacy>

**Comment by ElPaisano** [comment]
This issue has been forwarded to abuse@ipfs.io. Please reach out to abuse@ipfs.io for further information and assistance on how to report IPFS phishing and spam links, and have them taken down
