### ISSUE TITLE
Add User-Friendly IPFS Implementations on top of "IPFS Implementations" page

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-docs#1606]
Hello! The current IPFS Implementations page contains mostly technical and backend IPFS services. It would be great if we had some indication of less technical implementations/products, such as IPFS Desktop, Brave, etc. More context here: https://github.com/ipfs/boxo/pull/298#discussion_r1198388316

<img width="1254" alt="image" src="https://github.com/ipfs/ipfs-docs/assets/5447088/4004ebfa-7f39-439c-b9a1-307eb7f0176c">

**Comment by ElPaisano** [comment]
Thanks for taking the time to open this issue. Just wanted to update that this is being addressed in https://github.com/ipfs/ipfs-docs/pull/1609.
