### ISSUE TITLE
[CONTENT REQUEST] (Kubo install doesn't work in windows 11 !)

### ISSUE THREAD

**Issue by idoine** [ipfs/ipfs-docs#1641]
https://docs.ipfs.tech/install/command-line/#install-official-binary-distributions

![image](https://github.com/ipfs/ipfs-docs/assets/12686905/827c7d20-1af5-4f2d-b12d-9ed6fd205461)

![image](https://github.com/ipfs/ipfs-docs/assets/12686905/9098257f-b1d0-40e4-8c76-4a930e6ddfcc)

Because windows 11 "about_Execution_Policies" (https://go.microsoft.com/fwlink/?LinkID=135170.), `& $profile` don't work.

Use `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser` before, and it's well

**Comment by johnnymatthews** [comment]
Duplicate of https://github.com/ipfs/ipfs-docs/issues/1640
