### ISSUE TITLE
Content Identifiers (CIDs) not sure what needs to be done moving forward

### ISSUE THREAD

**Issue by surgarshorts** [ipfs/ipfs-docs#1646]
<!--
Hello! To ensure this issue is correctly addressed as soon as possible by the IPFS team, please try to make sure that you describe your suggestion in as much detail as possible. If you have any images or sketches to go along with the suggestion, please include them here.
--
Having trouble understanding what Is going on and what I need to do moving forward & ensuring I'm safe.>

**Comment by surgarshorts** [comment]
Having trouble understanding what needs to be done & ensuring I'm safe

**Comment by ElPaisano** [comment]
Hello, thank you for taking the time to create an issue. 

@surgarshorts we are unclear on how to best help you, as you have not described the issue. Could you please describe in more detail what information you need about CIDs, what is confusing, what you are trying to do, etc.? Once we have that information, we can better assist. Thank you

**Comment by ElPaisano** [comment]
Hello, we are closing this issue, as there has been no actionable request. Please reopen if you need further assistance and have additional information. Thank you.
