### ISSUE TITLE
Nodes

### ISSUE THREAD

**Issue by poulpeIG** [ipfs/ipfs-docs#1647]
The section on "preload nodes", in https://docs.ipfs.tech/concepts/nodes, has disappeared. Is this normal?
I had translated it, but I can't find the original source.

**Comment by ElPaisano** [comment]
Thank you for taking the time to create an issue. We will provide an update shortly.

**Comment by ElPaisano** [comment]
@poulpeIG following up on this issue:

The preload node information was removed from the documentation as part of an ongoing effort to clean up outdated information, especially with the recent [archival of js-ipfs](https://github.com/ipfs/js-ipfs) and introduction of [Helia](https://github.com/ipfs/helia).

However, you can still view old documentation states by looking at previous commits. The preload information you're looking for should be available here https://github.com/ipfs/ipfs-docs/blob/7dd0675eb450ce6ab9517105035a9f035637e8c1/docs/concepts/nodes.md#preload. Please let us know if this helps.
