### ISSUE TITLE
[suggest] info installing desktop apps

### ISSUE THREAD

**Issue by 86ed** [ipfs/ipfs-docs#1648]
re: https://docs.ipfs.tech/install/ipfs-desktop/#windows

It would be super to allow users to know what will be installed in windows outside program files -- for clean uninstallations.

**Comment by ElPaisano** [comment]
Thank you for taking the time to create an issue. We will provide an update shortly.

**Comment by ElPaisano** [comment]
Are you having trouble with the uninstallation process?

**Comment by ElPaisano** [comment]
All files installed with the IPFS Desktop application will be stored in location that you select during the install process.

Additionally, [npmjs.com/package/go-ipfs](http://npmjs.com/package/go-ipfs) will run the version of Kubo for the IPFS Desktop install, resulting in all files normally installed with Kubo being installed as well i.e. `$HOME/.ipfs`.

Please let us know if this answers your question at all.
