### ISSUE TITLE
Incorporate https://specs.ipfs.tech/architecture/principles/ into Concepts

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/ipfs-docs#1674]
## Problem

Currently, our we have a 3 part basic concepts section that includes https://docs.ipfs.tech/concepts/what-is-ipfs/ and https://docs.ipfs.tech/concepts/ipfs-solves/. However, this is lacking important info. https://specs.ipfs.tech/architecture/principles/  describes context and details about characteristics that define IPFS and the various implementations of the protocol. In doing so it defines what is or is not an IPFS implementation. 

## Suggestion 

Rewrite https://docs.ipfs.tech/concepts/what-is-ipfs/ and https://docs.ipfs.tech/concepts/ipfs-solves/ to better reflect the info contained in https://specs.ipfs.tech/architecture/principles/

## Subtasks

- [x] #1152  (nuances of CIDs)
- [ ] #1697 (IPFS implementation principles)

**Comment by Dhruval7878** [comment]
If this issue is not completed yet, then please assign it to me ASAP !
