### ISSUE TITLE
Document delegated routing concept

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs-docs#1752]
In light of https://github.com/protocol/bifrost-community/issues/1 , we should document more the concept of delegating content routing.  Areas to update:

- [ ] Update "delegated routing" glossary item
- [ ] Update https://docs.ipfs.tech/concepts/nodes/#delegate-routing-node
- [ ] Mention someguy
- [ ] Mention https://delegated-ipfs.dev/routing/v1/providers/

**Comment by BigLep** [comment]
@lidel please add if there's other places you think we should update

This is a step in support of https://github.com/ipfs/ipfs/issues/499

**Comment by 2color** [comment]
Just did some testing now to see how https://trustless-gateway.link is supposed to be consumed.

Is appears that it's only supported as a path gateway and that passing `?format=car` as a GET parameter is not supporterd.

Nonetheless, `curl -H "accept: application/vnd.ipld.car" https://trustless-gateway.link/ipfs/bafybeidfqp36qutohidaaapir743mvjefv5ipkbrvqx3li3x6vm47vrdam > site.car` works.

**Comment by 2color** [comment]
Does `delegated-ipfs.dev/routing/v1` currently support IPNS names?

It seems like it doesn't, e.g. `https://delegated-ipfs.dev/routing/v1/ipns/k51qzi5uqu5dlvj2baxnqndepeb86cbk3ng7n3i46uzyxzyqj2xjonzllnv0v8` returns a 406

**Comment by BigLep** [comment]
FYI there is some sort of related content in https://github.com/ipfs/ipfs-blog/pull/640
