### ISSUE TITLE
[DOCS ISSUE] (add your title here!)

### ISSUE THREAD

**Issue by aleith** [ipfs/ipfs-docs#1761]
why am I seeing a giant "=" glyph the size of the an entire 4K screen at the top of this documentation when I open in a desktop browser?! this is the top hit when I search online for documentation for IPFS.

**Comment by 2color** [comment]
Can you please share a screenshot?

**Comment by aleith** [comment]
Hi Daniel

i log several tech issues per week with various developers. sometimes i log
five or more in a single day.

some things for you to consider:
1) there was nothing at all in the pervious email from your org to identify
what issue you were responding to
2)  there was nothing at all in the pervious email from your org to
identify what software application my report was in relation to.
3) there was no link to my original contact with your org so that i might
answer questions 1 and 2 above for myself without bothering you for an
explanation.

please answer questions 1 and/or 2 for me and illl endeavour to provide you
with screenshots.

Best
Alastair

Alastair Leith

+61 432 889 831
Founding Co-Convenor of Renew WA
