### ISSUE TITLE
[DOCS ISSUE] Phishing on the domain?

### ISSUE THREAD

**Issue by jacobmasters** [ipfs/ipfs-docs#1777]
for example:

https://bafybeigzne7wvvnmhs2bmxihqb4pqrjjd33oenlvp5iqw363dvp2wu44cq.ipfs.dweb.link/

**Comment by tobiasoberrauch** [comment]
This is also phishing https://bafybeiekzjgribfsw7vbebcp6mbnniw4g7fb4kjqdrybwmfpvyd5nv4b3e.ipfs.dweb.link/

**Comment by lidel** [comment]
For reports like this, please use abuse email listed on https://ipfs.io/legal/ :pray:
