### ISSUE TITLE
I'm interested in becoming an IPFS node provider. I'm looking for how to start.

### ISSUE THREAD

**Issue by manh-vv** [ipfs/ipfs-docs#1790]
The content of the site is great but I think it is better to guide specific users instead of wide range of users. Thank you for your patience.

**Comment by 2color** [comment]
Thanks for the feedback. We have a number of guides. IPFS Desktop (which includes Kubo), is a good place to start if you want to run a node: https://docs.ipfs.tech/install/ipfs-desktop/.

For any discussions, I recommend joining the [IPFS Forums](https://discuss.ipfs.tech/)
