### ISSUE TITLE
IPFS Implementations: iroh claims not to be an IPFS implementation

### ISSUE THREAD

**Issue by ijsnow** [ipfs/ipfs-docs#1797]
I found [iroh](https://github.com/n0-computer/iroh) on the IPFS implementations list but [their documentation website](https://iroh.computer/docs/ipfs) explicitly says it is not an ipfs implementation, but instead an ipfs system. 

>Iroh is an IPFS system. It uses content identifiers (CIDs). Content addressing is a powerful primitive that belongs at the foundation of the internet.
>
> Iroh is not an IPFS implementation. An implementation of IPFS should be able to interoperate with [kubo](https://github.com/ipfs/kubo) the reference implementation of nearly all [IPFS Specs](https://github.com/ipfs/specs). Iroh can interoperate with kubo by bridging the two technologies, but by default one shouldn't expect to be able to add content to kubo and get it out with iroh, or vice versa.

Should the project be removed for the list? If not, whats the qualification for the term "implementation"?

**Comment by 2color** [comment]
We should have more information on interoperability between implementations. 

The qualification for an implementation is laid out here: https://specs.ipfs.tech/architecture/principles/#ipfs-implementation-requirements

**Comment by 2color** [comment]
Closing this in favour of https://github.com/ipfs/ipfs-docs/issues/1904
