### ISSUE TITLE
Tables appear truncated on the right

### ISSUE THREAD

**Issue by DG12** [ipfs/ipfs-docs#1813]
https://docs.ipfs.tech/concepts/comparisons/#comparing-the-key-features-of-other-solutions-to-ipfs

browser safari and Firefox
Mac OS

**Comment by 2color** [comment]
You should be able to scroll horizontally. I just tried on Safari MacOS
![2024-02-19 12 57 53 pm](https://github.com/ipfs/ipfs-docs/assets/1992255/ca30bc4b-cc5c-4559-b942-0e4517e03f2b)

**Comment by DG12** [comment]
Awkward :-(
 
Depending on widow width, there may be no indication that there are additional scrollable columns.
![image](https://github.com/user-attachments/assets/bd1c3190-cab2-4cd9-83a8-6691f135654e)

**Comment by ELALEMAN007** [comment]
1⁴
1.1.1.1
<[yyyy]>Incómodo :-( Dependiendo del ancho de la viuda, es posible que no haya ninguna indicación de que haya columnas desplazables adicionales. image.png (ver en la web): responda a este correo electrónico directamente, véalo en GitHub o cancele lap suscripción. Está recibiendo esto porque están suscritos a este hilo.


Enviado desde mi Samsung Mobile de Telcel
Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
