### ISSUE TITLE
Typo issue in get-started section

### ISSUE THREAD

**Issue by TTNguyenDev** [ipfs/ipfs-docs#1834]
I've identified a typographical error in the 'Get Started' section, where the word 'than' is duplicated. I recommend removing one to correct this.
https://docs.ipfs.tech/install/#get-started
![image](https://github.com/ipfs/ipfs-docs/assets/42999269/61e3db47-d6e4-4864-9e21-e6f3569f4fab)

**Comment by TTNguyenDev** [comment]
@2color  I would like to handle and solve this issue.

**Comment by 2color** [comment]
PRs welcome

**Comment by TTNguyenDev** [comment]
@2color Can you please review my PR?
