### ISSUE TITLE
Content Identifiers (CIDs): CodeSandbox: Converting between CID versions and encodings

### ISSUE THREAD

**Issue by cernicc** [ipfs/ipfs-docs#1868]
CodeSandbox at https://docs.ipfs.tech/concepts/content-addressing/#cid-conversion is not working.

**Comment by bumblefudge** [comment]
Sorry, can you say more? I tried it in two different browsers and it seems to work just fine in both after clicking the "Open Sandbox" button.

**Comment by 2color** [comment]
I think I had already fixed a bug before you looked at this @bumblefudge. Closing.
