### ISSUE TITLE
IPFS being used for scams and Phishing

### ISSUE THREAD

**Issue by Nubink** [ipfs/ipfs-docs#1880]
Hi, I received an email today claiming that a document had been shared with me.  The link in the email ultimately goes to:
https://bafybeifmtpjnod34eo2l7cpnori44jhki7jexeblpk76dagz6g7jkxgn4e.ipfs.w3s.link/ and then to the .js file stored there

Needless to say, you will want to remove this "user"

Thank you
Gary

**Comment by heyjay44** [comment]
@Nubink thank you for flagging! It is being dealt with.

**Comment by 2color** [comment]
Please report to `abuse [at] ipfs.io`
