### ISSUE TITLE
dark reader extension in chrome makes logo look too big

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/ipfs-docs#218]
<img width="556" alt="Screenshot 2020-05-18 at 16 59 25" src="https://user-images.githubusercontent.com/314190/82234955-02085c80-992a-11ea-8d6c-a0ee105218f0.png">

**Comment by johnnymatthews** [comment]
Could probably fix this issue by creating a dark theme within VuePress, then users don't have to install an add-on in the first place.
