### ISSUE TITLE
Debugging using `collect-profiles.sh` script.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#223]
When debugging issues in Go-IPFS users sometimes have to run the `collect-profiles.sh` script. This script _is not_ included in installions from `dist.ipfs.io`, and it only found within the [`ipfs/go-ipfs` repo](https://github.com/ipfs/go-ipfs/tree/master/bin).

We need to document:

1. How to run this script.
1. What it's used for.
1. When to use it.

We should also discuss whether this script should live in all `dist.ipfs.io` releases. Can we expect all users to know how to navigate GitHub, just to run a debug script?

Right now, this issue will not be addressed this quarter (Q2 2020).

**Comment by Stebalien** [comment]
The debug guide lives in https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md.

If we want to bundle this with go-ipfs, we should just add a special sub command.

**Comment by BlocksOnAChain** [comment]
this is blocked until Go-IPFS RC with dedicated commands goes out: https://github.com/ipfs/go-ipfs/pull/8291
