### ISSUE TITLE
Expand MFS section of "File systems and IPFS" page

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/ipfs-docs#243]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
We need to expand and improve upon the existing [File systems and IPFS page](https://docs-beta.ipfs.io/concepts/file-systems/); information is incomplete and some is out of date.

At the IPFS developer summit in Berlin in July 2018, we had poster-making sessions where people explored various IPFS concepts. Please examine the poster (contacts for its creators can be provided if necessary) and include its information both in the body text of the revised doc, and in a graphic suitable for publishing on the IPFS docs beta site.

![mutable_file_system](https://user-images.githubusercontent.com/74178/43231199-3d0979be-9020-11e8-8f79-17641c5d778a.jpg)

Additionally, please examine the more recent material that has been developed on related topics: 
- [Protoschool course](https://proto.school/#/mutable-file-system)
- [Understanding how the InterPlanetary File System deals with Files](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A), from IPFS Camp

Please both link out to these artifacts in a "further information" section at the end of the doc, as well as incorporate summary/high-level concepts from the artifacts within the doc itself.

Finally, please examine the existing content in the original doc and update any content that may be inconsistent, unclear, or out of date. Please note that the final document should still be organized around the two main areas of MFS and UnixFS.

## Deliverable
An expansion of the original concept doc that fully integrates the considerations outlined above. As a whole, this revised concept doc should answer the following, **supplemented whenever possible by diagrams, videos and/or code examples**:

- **What** is this?
- How does it **relate** to the rest of IPFS?
- What are some **generic use cases** for this — how might it meet a need in someone's project/goal?
- How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not necessarily* use it based on your use case or the current state of the tech.)
- **Where** do you go to learn more?
- What is the **current state** of this concept or technology?

**Content should take the form of a Markdown document, supplemented by diagrams as embedded images.** File locations should be as follows:
- MD content should live here (please make a PR against the existing document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/file-systems.md
- Images can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by realChainLife** [comment]
Hi @johnnymatthews if this is still unassigned I can have a go at it

**Comment by johnnymatthews** [comment]
It's all yours @realChainLife!

**Comment by BlocksOnAChain** [comment]
https://docs.ipfs.io/concepts/file-systems/#mutable-file-system-mfs - done by this page, we should close
