### ISSUE TITLE
Expand IPNS concept doc

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/ipfs-docs#244]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
We need to expand and improve upon the existing [IPNS page](https://docs-beta.ipfs.io/concepts/ipns) in our docs; information is incomplete and some is out of date.

At the IPFS developer summit in Berlin in July 2018, we had poster-making sessions where people explored various IPFS concepts. Please examine the posters (contacts for their creators can be provided if necessary) and include its information both in the body text of the revised doc, and in a graphic suitable for publishing on the IPFS docs beta site.

![ipns](https://user-images.githubusercontent.com/74178/43231278-9125692c-9020-11e8-9e44-82f11a363641.jpg)

![ipns_publish-resolve](https://user-images.githubusercontent.com/74178/43231280-95179938-9020-11e8-9559-6f3d9aff7f10.jpg)

Additionally, please examine the more recent material that has been developed on related topics:
- IPNS [specs](https://github.com/ipfs/specs/blob/master/naming/README.md)
- IPFS camp deep dives on [fast ipns](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/26-fast-ipns.md), [link rot](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/34-ipns-link-rot.md), and [rotating keys](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/16-revocation-rotating-of-ipns-keys.md)
- [The definitive guide to publishing content on the decentralized web](https://medium.com/textileio/the-definitive-guide-to-publishing-content-on-ipfs-ipns-dfe751f1e8d0)
- [What is InterPlanetary Naming System(IPNS)?](https://hackernoon.com/understanding-ipfs-in-depth-3-6-what-is-interplanetary-naming-system-ipns-9aca71e4c13b)

Please both link out to these artifacts in a "further information" section at the end of the doc, as well as incorporate summary/high-level concepts from the artifacts within the doc itself.

Finally, please examine the existing content in the original doc and update any content that may be inconsistent, unclear, or out of date. 

## Deliverable
An expansion of the original concept doc that fully integrates the considerations outlined above. As a whole, this revised concept doc should answer the following, **supplemented whenever possible by diagrams, videos and/or code examples**:

- **What** is this?
- How does it **relate** to the rest of IPFS?
- What are some **generic use cases** for this — how might it meet a need in someone's project/goal?
- How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not necessarily* use it based on your use case or the current state of the tech.)
- **Where** do you go to learn more?
- What is the **current state** of this concept or technology?

**Content should take the form of a Markdown document, supplemented by diagrams as embedded images.** File locations should be as follows:
- MD content should live here (please make a PR against the existing document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/ipns.md
- Images can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by bertrandfalguiere** [comment]
@dzhelezov, are you still working on it? I would like to take this on if you don't plan to work on it anymore.

**Comment by dzhelezov** [comment]
> @dzhelezov, are you still working on it? I would like to take this on if you don't plan to work on it anymore.

Hi sure feel free to take it, but I am not sure about the current status of this issue -- @johnnymatthews put it on hold back in April

**Comment by johnnymatthews** [comment]
Oh wow, I dropped the ball on this one. Sorry about that. Yes this project is back up for grabs! I'll assign it to you @dzhelezov if you're ready? There's some features in Go-IPFS 0.6 that might affect this page. Feel free to email me (address on my [GitHub profile](https://github.com/johnnymatthews/) with any questions).

**Comment by dzhelezov** [comment]
@johnnymatthews I am currently busy with another project so perhaps @bertrandfalguiere can take over. I would be happy to share what I've researched and compiled back in April.

**Comment by johnnymatthews** [comment]
@bertrandfalguiere if you're available it's all yours.

**Comment by bertrandfalguiere** [comment]
@johnnymatthews To be exact, I'll be on vacation Friday and the next week. I will be able to work on it after that, so if someone is available before july 13th, they can have the ticket, otherwise I'll handle it myself. 
@dzhelezov Having your previous work would help, thanks for offering it.

**Comment by dzhelezov** [comment]
Here's a (small) write-up I added to the IPNS page: https://github.com/ipfs/ipfs-docs/compare/master...dzhelezov:master

**Comment by dzhelezov** [comment]
This additional resources may be useful to follow the development of IPNS, but I guess some additional care should be taken to figure out has been actually implemented in IPFS 0.5:

- https://github.com/ipfs/specs/issues/198
- https://github.com/ipfs/go-ipfs/pull/6448
- https://github.com/ipfs/in-web-browsers/pull/150
- https://github.com/ipfs/notes/issues/348
- https://github.com/ipfs-inactive/faq/issues/48

**Comment by realChainLife** [comment]
@bertrandfalguiere are you still working on this? I can give it a go if you're not

**Comment by bertrandfalguiere** [comment]
Yes, still on it. I will ship end of next week, though.

**Comment by johnnymatthews** [comment]
How's this issue going @bertrandfalguiere?

**Comment by BlocksOnAChain** [comment]
we can close since we have: https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli
