### ISSUE TITLE
Disambiguating nodes/peers/instances vs daemons

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/ipfs-docs#245]
The term “node” is used in very different ways in different contexts around IPFS. At the Berlin developer summit, we decided adding a concept doc describing this might be helpful (it would *also* be a good idea to try and avoid using the general term “node” in the future 😛).

Here was the original draft:

> # Node
>
> You might see the term “node” used all over in discussions, issues, and IPFS-related code. It is a very general term, so its meaning depends on context, but you’ll see it used in two main ways around IFPS:
> 
> 1. **IPFS Nodes** (aka IPFS daemons aka DHT nodes) are copies of IPFS that are running on a computer and can exchange data with other IPFS nodes.
>
> 2. **DAG Nodes, UnixFS Nodes, Data Nodes, etc.** are actual pieces of data on IPFS. When you add a file with the `ipfs add myfile.txt` command, it gets broken up into several nodes that each contain a chunk of the file and are linked to each other.

Some concerns:

- Equating an IPFS node and a daemon is not quite correct (an IPFS node doesn’t have to be the only thing running in a process, it might not also have a gateway, etc.). Can we be more accurate without descending into arcana?

- What about **Libp2p Nodes** (kinda like IPFS nodes)?

/cc @Stebalien @hsanjuan who were also in this session

---

Concept docs are concise, high-level descriptions of various core concepts in IPFS. They should strive to answer:

1. **What** is this?
2. How does it **relate** to the rest of IPFS?
3. How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not* use it. *Bitswap* is probably a good example.)
4. **Where** do you go to learn more?
5. What is the **current state** of affairs?

**Comment by johnnymatthews** [comment]
> Node [...] - @Annamarie2019 

Yes. Except, each node isn't running a _copy_ of IPFS. IPFS isn't a blockchain, or something with a specific state. We could both be running IPFS on our machines, and what our nodes contain could be completely different.

> Peer [...]  - @Annamarie2019 

Correct!

> Daemon [...]

A daemon is a [program that runs in the background](https://en.wikipedia.org/wiki/Daemon_(computing)).

> As soon as we add a file to IPFS, is that the point at which we become a node?

No. As soon as the `ipfs` daemon starts, your computer becomes a node - even if you're not hosting any files. Your node is still working with other nodes to figure out where data is stored.

> If I close the IPFS Desktop, does the daemon stop running? - @Annamarie2019 

Yes, but make sure that it's properly closed (right click on the IPFS icon in the status bar and click **Exit**, or whatever it says in MacOS).

> Is there a concept of capacity for a node? - @Annamarie2019 

Do you mean how much data a node can store? Not really, but there are upper limits for various bits and bobs within IPFS. @Lidel can probably clarify though.

**Comment by Annamarie2019** [comment]
I'll take this one. (I'll also take 683 and 334....to really get into nodes.)

**Comment by Annamarie2019** [comment]
In progress....

**Comment by Annamarie2019** [comment]
This issue was resolved with PR [#1031 ](https://github.com/ipfs/ipfs-docs/pull/1031). I included these changed files in that PR before I knew how to properly separate them.
