### ISSUE TITLE
Explain what "Swarms" are in the "Observe peers" section.

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/ipfs-docs#249]
We should have a short concept doc about what a “swarm” is in IPFS.

Concept docs are concise, high-level descriptions of various core concepts in IPFS. They should strive to answer:

1. **What** is this?
2. How does it **relate** to the rest of IPFS?
3. How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not* use it. *Bitswap* is probably a good example.)
4. **Where** do you go to learn more?
5. What is the **current state** of affairs?

**Comment by johnnymatthews** [comment]
[There's a libp2p issue that covers this.](https://github.com/libp2p/docs/issues/33). Closing :)
