### ISSUE TITLE
Explain how IPNS relates to IPFS, and when to use DNSLink instead.

### ISSUE THREAD

**Issue by tmcw** [ipfs/ipfs-docs#252]
From https://github.com/ipfs/docs/blob/master/content/guides/concepts/ipns.md
(VuePress beta equivalent: https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/ipns.md)

> You can also use DNSLink (which is currently much faster than IPNS and also uses more readable names).

This doesn't give a great overview of how DNSLink relates to IPNS: reading this, you would think that it's a better alternative to IPNS. If you instead arrived at the [IPFS for Websites page](https://docs.ipfs.io/guides/examples/websites/) ([beta equivalent here](https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/how-to/host-single-page-site.md)) you'd think that IPNS is a solution for a mutable reference to a site, and DNSLink is a solution for a human-readable reference, and the two combined are the 'ideal' setup for a personal website on IPFS.

**Comment by BlocksOnAChain** [comment]
@lidel  - https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#domain-name-service-dns this should explain it.
