### ISSUE TITLE
Recommend installing IPFS Desktop rather than Go-IPFS directly.

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-docs#253]
IPFS Desktop now installs the `ipfs` command line tool, and has an auto-update mechanism, and has installers for alot of the platforms: https://github.com/ipfs-shipyard/ipfs-desktop#install

We should encourage folks to install desktop as the default, and then have an "setting up a server?" link... which encourages folk to install ipfs-cluster rather than go-ipfs, as we have ansible and docker scripts for cluster, and it is optimised for running on a server out of the box, and a cluster of 1 puts you in a good position for scaling your things later.

See issue ipfs/docs#110 for another potentially good install instruction explainer: how much disk space do different instantiations of IPFS take?

Additionally, let's discuss whether/how to include pointers for "non-official" ways of installing IPFS. This arises from a few stagnant (and, as a result of this issue, closed) PRs in the website repo, including:

- https://github.com/ipfs/website/pull/258 for `brew install` for Mac folks
- https://github.com/ipfs/website/pull/260 and https://github.com/ipfs/website/pull/228 for `snap` for Linux folks

**Comment by johnnymatthews** [comment]
Sorry for digging up an old issue team. What I'm getting from reading the comments here is that we need to:

- Push new users towards installing IPFS Desktop, ideally from the docs.ipfs.io homepage.
- Create a _server install_ section that talks about installing IPFS Cluster.
- Have a command-line install option that touches on installing via Choco, Brew, and Snap (for Windows, macOS, and Ubuntu respectively).

I'm gonna create new issues for the last two points, and this issue can serve to just recommend installing IPFS Desktop for new users.

**Comment by johnnymatthews** [comment]
The [Install section](https://docs.ipfs.io/install/) now clearly splits up each installation option, with IPFS Desktop right at the top. The only remaining task in this issue is to create an installation section for IPFS cluster / server set ups, which is duplicated in #355. Closing this issue.
