### ISSUE TITLE
Expand upon existing FAQ page

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#254]
The barebones FAQ at https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/faq.md needs to be augmented as follows:

- [ ] 1. Incorporating the most important and/or significantly commented items in the "old" FAQ located 
at https://discuss.ipfs.io/c/help/Old-FAQ (warning, there are a lot of them!)

- [ ] 2. When done, close and remove the "old FAQ" section of Discourse

- [ ] 3. Next-level improvements as outlined by @momack2 in her original issue ipfs/docs#213, now closed. These are pasted below:

*I would really like to see us have a usefully organized FAQ about IPFS instead of just linking to this hard-to-parse/search list directly. Would love folks to run with this! Maybe @vasa-develop or @andrewxhill/@carsonfarmer have content from explainers they've created to contribute here?

Other questions I'd like to eventually see answered include:

A better "what is IPFS" answer that has less jargon
How does IPFS work?
How is IPFS different from other file systems?
How are IPFS and Filecoin related?
Is all data added to IPFS permanent?
this confusion comes from the "permanent web" moniker - making people think that all data added is indefinitely persisted by some pervasive storage layer in IPFS, which is not the case.
Can you have private / personal data on IPFS?*

**Comment by johnnymatthews** [comment]
This issue will be addressed in #279.
