### ISSUE TITLE
Automatically test all code examples in this repository.

### ISSUE THREAD

**Issue by Stebalien** [ipfs/ipfs-docs#255]
We have the following line in our release process checklist:

>  Ensure that all the examples we have produced for go-ipfs run without problems

This is simply impossible to achieve manually.

---

We should have doctests like in rust (https://doc.rust-lang.org/rustdoc/documentation-tests.html).

1. All examples in documentation should be clearly marked.
2. Each piece of documentation should include machine readable instructions for testing the documentation (e.g., the environment the document should be tested in). Personally, I'm thinking yaml top matter.
3. We need something that actually _runs_ these tests.

---

For example, every document could start with:

```
---
....
test: testing tool
---
```

We could then have a testing tool iterate over every markdown file, running the appropriate testing tool against each one.

**Comment by johnnymatthews** [comment]
I've added the `need/analysis` tag to this issue. We need to have a look into _how_ this process would work, and if we can add it into CircleCI (or if we'd need to run the tests locally before pushing GitHub).

**Comment by johnnymatthews** [comment]
This is overly ambitious. Instead, when we're showing the reader a code example, we copy it directly from https://github.com/ipfs-examples. Closing.
