### ISSUE TITLE
Review examples in ipfs/website and import any useful docs into this repo.

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-docs#257]
- Examine https://github.com/ipfs/website/tree/master/static/docs and directories/documents contained within for any items that need to be moved to docs VuePress site (note, some of these may be extremely outdated)
- When done, delete the directory in the website repo

**Comment by johnnymatthews** [comment]
- [ ] Review all the examples in the [`ipfs/website` repo](https://github.com/ipfs/website/tree/master/static/docs/examples).
- [ ] Check with Go-IPFS team for relevancy of examples.
- [ ] Copy over useful and relevant examples into this repository.
- [ ] Grammar and spell check as usual.
- [ ] Create PR to delete examples from `ipfs/website`.

**Comment by johnnymatthews** [comment]
All the relevant examples in this issue already exist in docs.ipfs.io. Word on the street is that ipfs.io might be getting a revamp in the near future, so this website repo will likely get seen to. I'm gonna close this issue. :)
