### ISSUE TITLE
Collect Canny data and import it into GitHub issues.

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#260]
- Monitor docs beta features vote implemented under ipfs/docs#319 until sufficient responses gathered
- Use voting results to prioritize building future docs features
- Generate report on the voting results for transparency and future reference

**Comment by johnnymatthews** [comment]
Canny is good, but for the sake of simplicity we're going to keep suggestions within the **[Issues](https://github.com/ipfs/ipfs-docs/issues) tab** using the [`king/suggestions` tag](https://github.com/ipfs/ipfs-docs/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fsuggestion).

I'm changing this issue to grab the data we've collected in Canny and bring it into GitHub.

**Comment by cwaring** [comment]
Stale issue, closing for now.
