### ISSUE TITLE
Migrate Go-IPFS documentation into this repository.

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#262]
- Integrate go-ipfs repo docs content into VuePress site
- Delete GitHub pages' content, but add pointers to new site for those who may have GitHub material bookmarked
- Discuss best way to integrate go-ipfs [docs-related open issues](https://github.com/ipfs/go-ipfs/issues?q=is%3Aopen+is%3Aissue+label%3Adocs-ipfs) into docs team workflow overall (start with adding the go-ipfs repo to the docs WG's ZenHub board and sort issues there accordingly)

**Comment by BlocksOnAChain** [comment]
Outdated issues, we will close it - @lidel
