### ISSUE TITLE
Update the "Make your own IPFS Service" section.

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#263]
The basics tutorial on making your own IPFS service is outdated, and should be cleaned up before beta launch. Please review and amend, but in the beta repo:
https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/how-to/make-service.md

Thanks!

**Comment by johnnymatthews** [comment]
Need to find out:

1. If this documentation is still required.
1. How services work right now.
1. What we should include in the tutorial (needs input from a _services_ expert).
