### ISSUE TITLE
Create a map of how the docs should look, with the "Single-source documentation" project in mind.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#265]
**Note: This issue was opened as a result of the November 2019 close-reading audit captured in ipfs/docs#326.**

As discussed in ipfs/docs#326 under **Content Guidelines**, a next-generation hierarchy was proposed for the overall navigation IA of the docs site:

```text
Home
├────── Getting Started
 Quick-win is the name of the game here. We want the reader to be able to go through this section in less than an hour and come out the other end with a solid idea of what IPFS is, how to use it, and why it's important.
├────── Developer Concepts
 Explain difficult or new things that IPFS addresses. This could be things like how it's different than a regular database, or how Filecoin integrates into IPFS.
├────── Community
 Guides, links, and references to documentation, tools, and services create and maintained by the IPFS community. There should also be support links in here that are directed to places like StackOverflow and the IPFS forum.
├────── Guides
 End to end tutorials that walk a user through achieving a particular goal. That can be as simple as setting up a node, uploading a single file, uploading a whole site, or changing a website's name server so that it points to IPFS.
├────── Tools
 Things you can use to interact with IPFS. These things might not necessarily be 100% useful or necessary all the time, but they're available all the same.
└────── APIs
 IPFS has a bunch of different APIs available to developers for various different implementations. Each API needs a getting started guide, API references, and an examples section.
```

However, implementing this new IA will require significant rewriting of existing content, as well as creating new documents and articles to fill in the holes. A more in-depth map should be created before we start writing and editing content.

Let's use this issue as a holding pen for discussing the timeline and necessary steps for implementing a next-gen navigation IA, starting with generating/improving content [labeled for new content or content enhancement](https://github.com/ipfs/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22OKR+1%3A+Content+improvement%22).

**Comment by johnnymatthews** [comment]
This map was created back in November. I've since found out how deep the IPFS rabbit hole goes, so the map is horribly out of date and need re-drawing.

**Comment by BlocksOnAChain** [comment]
we shouldn’t do this, since we changed the approach after the reorg we did - @johnnymatthews
