### ISSUE TITLE
Create a localization strategy.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#268]
**Note: This issue was opened as a result of the November 2019 close-reading audit captured in ipfs/docs#326.**

Having the docs site in several languages is great for globalization, and improves SEO. However, localization is hard and comes with significant overhead. Every change we make to a document means that the page needs to be translated again. We could cut down this overhead by using a dynamic service like Localize.js, or we can leave users to chose their own translation service.

We should decide:

1. Is localization something we want to tackle this year.
    a. If yes: which solution?
    b. If no: why not?
2. How to support IPFS users regardless of the decision.

**Comment by olizilla** [comment]
As @terichadbourne mentioned, we've already invested in Transifex as our translation system, as documented here https://github.com/ipfs-shipyard/i18n#adding-i18n-to-your-project 

Adding i18n support to vuepress is documented here https://vuepress.vuejs.org/guide/i18n.html

The trick is getting the config right for transifex so it can provide the translated files in the form we need (mostly markdown)

- https://docs.transifex.com/client/config
- https://docs.transifex.com/formats/markdown

The basic flow is 
- import the existing base local files into transifex
- create translation languages in transifex
- _get translating!_
- pull down translations periodically as a given translation for locale reaches a minimum threshold of completion

I'm happy to help guide anyone who wants to work on this!

**Comment by jessicaschilling** [comment]
I'd +1 everything @olizilla says. And FWIW - our translation community is pretty remarkably active!

**Comment by johnnymatthews** [comment]
Speaking to users, the vast majority of non-English speakers use their own browser tools to manage translations. Without committing significant, this will do for now.
