### ISSUE TITLE
Investigate IPFS emulation for try-as-you-go docs

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#270]
Investigate difficulty/rewards involved in
- Adding sandboxing to How-tos in general
- Creating an emulated IPFS CLI for that sandboxing, so users could immediately try what they learn without having to spin up a local instance. (Note: For within-site usage you can use js-ipfs - like what ProtoSchool is doing - with an in-browser node.)

Let's use this issue to discuss and possibly implement.

_Note: This issue was generated as a result of Nov 2019 internal user testing. Background can be found in the [summary](https://hackmd.io/gdRqxFZoRy-U-xB1DHitIA?view) (source: ipfs/docs#315)._

**Comment by johnnymatthews** [comment]
Depending on how simplified we want things to be, we should cheat a little bit here and just have a JS widget _pretend_ to interact with the IPFS network. We could design it in a way that basic commands work and _interact_ with an IPFS node, when in reality all that's happens is the JavaScript is just swapping variables and throwing in a bunch of `setTimeout()` commands.

Having an active console connecting to an actual node could open up a potential attack vector.

**Comment by johnnymatthews** [comment]
I'm gonna close this as out-of-scope for now. While it'd be nice to have, it's not the best use of resources right now.
