### ISSUE TITLE
Add prev/next links in docs site footer, solving for offsite links

### ISSUE THREAD

**Issue by ericronne** [ipfs/ipfs-docs#272]
Currently much of the docs content isn't very well threaded, but upcoming changes (like those proposed by @johnnymatthews in ipfs/ipfs-docs#265) should serve to improve the overall content flow from page to page. In the mean time, users may find it handy to have this secondary/analog method of navigation available. This may be especially true for mobile, where users otherwise have to toggle open a menu in order to browse.

**HOWEVER**, in order to implement this, we must first control for the fact that many left-hand nav links go to external sites. Possible options include:
- Wait to implement this until we (as planned) migrate a lot of go-ipfs and js-ipfs content out of their respective repos and onto the docs site
- Make a docs page for each of these links. That page would include brief info gleaned from the destination content, and of course, the link itself.

### Mockups

**Desktop**
![image](https://user-images.githubusercontent.com/9259185/70184793-2d65fa80-16ae-11ea-9fc7-fe5e5bae9bc3.png)

**Mobile**
![prev-next-mobile](https://user-images.githubusercontent.com/9259185/70184911-74ec8680-16ae-11ea-94e8-1029e168519d.png)

**Svg arrow files**
[Default](https://drive.google.com/open?id=1c-CN5v6-2h6CkEiLv8i7XSxB09CXcQmH)
[Hover](https://drive.google.com/open?id=1KwkQtJ12i4xBQBkjzfUrDaFCXLi8_Qj3) (if we swap art rather than recoloring on hover)

Default arrow color `#Default: #9ad4db`
Hover arrow color `#377f85`

**Comment by johnnymatthews** [comment]
This would still be quite cool to have if we could specify the _before_ and _next_ destinations in the front matter. Having it automatically generated from the sidebar nav is likely to cause a bunch of issues.
