### ISSUE TITLE
Explain how much disk space an initial installation will use.

### ISSUE THREAD

**Issue by mitar** [ipfs/ipfs-docs#273]
Around there where you suggest running daemon, I would appreciate some comment if this would take a lot of disk space or not. As a IPFS beginner, I would suspect that it would start syncing data from others to my computer. Probably it does not do so, but then a statement of encouragement would be cool as well. (Like, no files will be downloaded until you ask for them.)

**Comment by johnnymatthews** [comment]
_Finally_ closed this one in 0d5a8e732d02d6ec1ddfda8655da8258c146a9e6

**Comment by mitar** [comment]
Thanks!
