### ISSUE TITLE
Explain the downgrade procedure for Go-IPFS.

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/ipfs-docs#278]
**What's the subject of the item you're requesting?**

How can users safely downgrade go-ipfs (including reverting migrations)

**What's the content of the item you're requesting?**

Port and update https://github.com/ipfs/fs-repo-migrations/pull/10

**What will the user know how to do after going through this item?**

Downgrading and reverting repo migrations

**Would you be interested in helping create this item?**

No. It should be easy enough for someone to pick up and test. Also, low prio.

**Comment by TheDiscordian** [comment]
This should be helpful for anyone looking to tackle this issue: https://github.com/ipfs/ipfs-update#revert

**Comment by TheDiscordian** [comment]
Oh this is already documented [here](https://docs.ipfs.io/install/ipfs-updater/#downgrade-ipfs), wicked.
