### ISSUE TITLE
Create guides for how IPFS can help with web hosting, academic purposes, and other core goals.

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#295]
## [This issue has a bounty of $400](https://github.com/ipfs/devgrants/projects/1)

**This issue is one of the prioritized recommendations in the [Q1 2020 IPFS Ecosystem Audit](https://github.com/ipfs/community/tree/master/ecosystem-audit) for execution in Q2/Q3 2020. Tagging it with `$auditrecommendation` means it's searchable! See [all tagged issues](https://github.com/ipfs/docs/issues?q=is%3Aissue+%22%24auditrecommendation%22+) in this repo.**

The need: A series of conceptual (not necessarily highly technical) guides for how IPFS can help both with our core goal areas (see this [Airtable](https://airtable.com/shrQoB6LnOSPBo9Yr)) and with some of the top core-goal-related workstreams (see this other [Airtable](https://airtable.com/shr1x1C9ltwh936uH)) identified in our Q1 2020 ecosystem audit.

Audiences for these guides: Relevant to everyone to some degree, but specifically relevant to decision-makers who aren't developers: tech leads, dweb-curious in relevant app areas, c-suiters.

Related, but may be a separate need: some more technical, but still high-level, questions are being tracked in the following document (sourced from Reddit, StackExchange, etc): https://hackmd.io/SGBZ8TAmRhuPgz7yX2JGcQ?view

**Comment by AlexxNica** [comment]
I can work on this one. Could you please elaborate on which goals you're looking to complete with this bounty?

Also, what do you think of breaking these goals into separate bounties? That way I can work on them separately without spending too much time trying to complete the whole issue at once, and enables us to release them sooner.

**Comment by rleddy** [comment]
Sometimes I write articles for cash. Need to make some now.

Is this still something that can be addressed? Noting this is about one year old.

Is this bounty per article? Can one discuss with staff about the choices of what to write next? Where do the article get published? Is someone actively managing this? Is there an editorial process for this? Hoping that parameters can be clear. Articles (or versions) might go into DEV or Smashing, etc. as part of the process. So, should editorial parameters match theirs at times? Should videos accompany articles? Would you pay for a video as well?

Please let me know. Happy to exchange contact info and have live conversations.

Thanks...

**Comment by johnnymatthews** [comment]
This issue is quite old, and no longer reflects the priorities that IPFS, and Protocol Labs as a whole, now has. Closing.
