### ISSUE TITLE
Create a guide/section on using IPFS Update.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#300]
There is currently no documentation for using `ipfs-update` within the `ipfs/docs` repo. There are instructions on the [`ipfs/ipfs-update` repo](https://github.com/ipfs/ipfs-update/blob/v1.6.0/README.md), however. These instructions should be brought into the `ipfs/docs` repo and updated. These docs can go into `docs.ipfs.io/how-tos/ipfs-update/`. The section should cover:

1. Install `ipfs-update`.
1. Use `ipfs-update` to install IPFS.
1. Use `ipfs-update` to update your current IPFS installation.
1. Use `ipfs-update` to downgrade your IPFS installation.
1. Uninstall `ipfs-update`.

**Comment by alexmmueller** [comment]
@johnnymatthews Is this issue still relevant? If so, I could give it a shot.

**Comment by johnnymatthews** [comment]
It is! However, it should probably go in `/install/command-line/` under a `### IPFS Update` header.

**Comment by alexmmueller** [comment]
Alright. I will prepare the requested changes.

**Comment by alexmmueller** [comment]
@johnnymatthews  I made good progress already, but wonder where I can find information on how to uninstall ipfs-update. Can you give me a hint? Thank you!

**Comment by johnnymatthews** [comment]
There are no docs for uninstalling IPFS-Update, that I know of. I'm assuming the process is something like:

1. Remove the `ipfs-update` binary from your system.
1. Remove `ipfs-update` from your `PATH`.
1. Reboot.

But I'll check into this for you.
