### ISSUE TITLE
Rewrite the DHT page using the IPFS blog DHT Deep Dive posts are references.

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/ipfs-docs#302]
Did you find a bug, typo or other issue in an item of IPFS documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs-beta.ipfs.io/concepts/dht/#managing-data

**What's wrong with this page?**
The information in the managing data section is in the wrong place/is misleading.

**What would you like to have changed/amended/fixed in order to make things right?**
It currently says "IPFS nodes use the DHT to advertise which blocks they have, which blocks they want, and which blocks they don't want." and has a nice chart.

The DHT only advertises blocks that a peer has. The business of tracking Have's, Want's, and Don't Want's is really a part of Bitswap.

This section might best be removed or shrunken to state that your IPFS node uses the DHT to tell other people about the content you have so that they can come download it from you.

**Would you be interested in helping fix this page?**
A little swamped right now, but happy to review.

**Is there any other feedback you'd like to share about IPFS docs?**
❤️

**Comment by GraceRachmany** [comment]
I love documenting DHTs and addressing systems. Would love to claim this issue! ! Adin, would you be able to give me some of the inside scoop on how this works and I can do the writeup?

**Comment by johnnymatthews** [comment]
Assigned! These two posts about the DHT might be of use to you @GraceRachmany:

- [The Road to the New DHT](https://blog.ipfs.io/2020-05-19-road-to-dht/)
- [IPFS 0.5 Content Routing Improvements: Deep Dive](https://blog.ipfs.io/2020-07-20-dht-deep-dive/)

**Comment by johnnymatthews** [comment]
It looks like I've misunderstood this issue. We just need to amend the **Managing data** section and replace the _Have_, _Want_, and _Don't Want_ bits with something like:

> IPFS nodes then use Bitswap to advertise which blocks they _have_, which blocks they _want_, and which blocks they _don't want_.

**Comment by GraceRachmany** [comment]
Do you want an explanation of the Have, Want and Don't Have? That is not in the Bitswap document. It's explained in some of the videos but not in the documentation.

**Comment by johnnymatthews** [comment]
I've changed the title of this issue to reflect what actually needs to happen. Work has started on this piece in the `chore/replace-dht-mess-with-bitswap-link` branch. I created the branch before I realized we needed to rework this issue, so please excuse the weird branch name.

**Comment by johnnymatthews** [comment]
Closed in #412 .
