### ISSUE TITLE
Make the sidebar nav collapse in Firefox Preview on Android.

### ISSUE THREAD

**Issue by jayschwa** [ipfs/ipfs-docs#304]
docs-beta.ipfs.io does not collapse the sidebar when using Firefox Preview v4.3.0 on Android 10. This makes the site hard to read and navigate on my Pixel 2 phone. I am using the largest "Display size" and "Font size" in Android's system settings, but changing them to their defaults did not appear to make a difference. This problem does not happen in Chrome.

![docs-beta-firefox-preview](https://user-images.githubusercontent.com/475017/81431015-707d3b80-912e-11ea-8169-c76360d3eea0.png)

**Comment by johnnymatthews** [comment]
Hey @jayschwa, it looks like we've accidentally fixed this somehow. This is what I see in Firefox Android:

![Screenshot_20210422-120156](https://user-images.githubusercontent.com/9611008/115746863-b395e600-a362-11eb-872f-ccee522244b3.png)

Can you confirm if things are working on your end now?

**Comment by jayschwa** [comment]
Looks good on my end as well.
