### ISSUE TITLE
IPFS collab case study

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#313]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
Create a case study centering on an engaged IPFS collaborator org (collaborator details will be supplied upon project kickoff) that meets the following requirements:
- Concentrates on how IPFS serves/meets/solves the needs of one engaged collaborator org
- Depth of technical focus is "engineering manager" level: A reader with expertise in some area of software engineering, but not necessarily deep dweb knowledge (we may wish to supplement this content with more detailed white-paper-style implementation specifics, so please keep this in mind)
- Features high-level, objective callout metrics illustrating how IPFS has solved problems, enabled or contributed goals, saved time/bandwidth/money, etc
- Includes a callout box or similar highlight content indicating...
     - Whether Go or JS implementation is used
     - Which core modules were used "out of the box"
     - What the collab either customized or created from scratch themselves

Please include all of the following elements, since these will be consistent elements should we create additional case studies in the future:
- Call-out quote
- Overview
- "big number" boxes or benefits boxes
- Story with call-out quote
- Solution
- Benefits (long version)
- About IPFS/PL
- Solution info as regular running text (part of their story of how they solve the problem)
- Callout (for comparison between case studies) of whether Go or JS implementation is used; what core modules were used out of the box; and what the collab either customized or created from scratch themselves
- Challenges for which IPFS is a good and/or unique fit
- Future plans for IPFS-relevant parts of the collab's product/service

## Deliverable
A document (.md, .doc, etc) containing the above elements, including an appropriate number of revisions if necessary. If you have any ideas for illustrations/layouts that you had in mind when writing, please make a quick note of those so we are all on the same page!

**Comment by jessicaschilling** [comment]
Giving this issue to @gracerachmany and cc-ing @autonome for context.

(Grace, can you please comment to indicate receipt, and so that I can assign this one to you in GitHub itself?)

@johnnymatthews -- I'll run point on this, but since it'll eventually live in docs, you may just want to keep an eye on activity. 😊

**Comment by jessicaschilling** [comment]
@autonome, can you please send @GraceRachmany contributor contact details so she can get started? Thanks!

**Comment by johnnymatthews** [comment]
Sounds good 👍 . I can help out more after this week.

**Comment by GraceRachmany** [comment]
Check it out! I know how to use GitHub! (This is going to be a first.)

**Comment by jessicaschilling** [comment]
You can thank @johnnymatthews for enforcing the Oxford comma ... I started with AP style but have been broken of the habit! 🤣
