### ISSUE TITLE
Update the docs edit widget to point to the new docs repo

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-docs#333]
The `open an issue`:
![image](https://user-images.githubusercontent.com/618519/83933985-25bd0680-a762-11ea-9156-e8c904de2cf3.png)
sends the user to a 404 because the repo linked is now archived:
![image](https://user-images.githubusercontent.com/618519/83933980-1d64cb80-a762-11ea-8844-b10b64a095d1.png)

Update the widget and all other links to point to the new docs repo

**Comment by johnnymatthews** [comment]
Thanks for catching this one. Looks like we missed one `ipfs/docs` config.
