### ISSUE TITLE
Clear up how to download a file from IPFS using `cat`.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#337]
The [command line quick start](https://docs.ipfs.io/how-to/command-line-quick-start/) has the following section:

> Now, you should be able to get objects from the network. Try:
> ```bash
> ipfs cat /ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ/cat.jpg > cat.jpg
> open cat.jpg
> ```

Using the `cat` utility to get a file called `cat.jpg` can be confusing for readers not familiar with the `cat` utility. We should call the `cat.jpg` file something else, or use another file entirely (a space-related file would be a good fit).

**Comment by jessicaschilling** [comment]
This will singlehandedly ruin my hope that someday someone will make a funny `ipfs cat` t-shirt, but you're probably right.

**Comment by ChaituVR** [comment]
@johnnymatthews you have any other file url to replace this?

**Comment by johnnymatthews** [comment]
[The contribution guidelines recommend space-themed content](https://docs.ipfs.io/community/contribute/code-persona/#the-theme). An image of a planet in our solar system would probably be a good idea. We'd need to make sure that we're allowed to freely use the image ([unsplash.com](https://unsplash.com/) is probably the best place to source royalty-free images).
