### ISSUE TITLE
Add a call-to-action to subscribe to IPFS YouTube channel.

### ISSUE THREAD

**Issue by jennwrites** [ipfs/ipfs-docs#361]
I think it would be useful to direct folks to learn more by subscribing to our YouTube channel.

Here's the link to the channel:
https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew

Referenced in https://github.com/ipfs/website/issues/389 as well.

**Comment by johnnymatthews** [comment]
Happy to include this! It'd be good to have a link from the **Community** section, as well as a section on the homepage. Any particular videos you think would be good to call out @renrutnnej?

**Comment by renrutnnej** [comment]
Our most popular ones (leaving out the highlights + update focused videos) are:

* How IPFS Deals With Files - IPFS Camp Workshop https://www.youtube.com/watch?v=Y_-TWTmF_1I
* Core Course - The Lifecycle of Data in DWeb - https://www.youtube.com/watch?v=fLUq0RkiTBA
* Solving distributed networking problems with libp2p - IPFS Camp Workshop https://www.youtube.com/watch?v=oIMZP7sfFtM
* How IPFS Works - Steven Allen - https://www.youtube.com/watch?v=0IGzEYixJHk

**Comment by johnnymatthews** [comment]
Gonna throw a link to the YouTube channel in the sidebar.
