### ISSUE TITLE
Deleted a file from Pinata, but is still accessible. 

### ISSUE THREAD

**Issue by Freeland90** [ipfs/ipfs-docs#363]
Hello,
I did not upload the file to any other service/machine but Pinata, the file was up there for 2 weeks, I removed it but I can still find the IPFS hash accessible. Does that mean my file got picked up by other nodes? Is there a way to find how many nodes are pining my file? 

Thanks

**Comment by bertrandfalguiere** [comment]
Yes, you file was probably asked by another node. There is no way to know exactly how many nodes have your file. You can estimate the number by using several times ipfs.findprov(CID).

If you have questions of usage with no action to be taken by the developers (bug or request feature), please ask them on discuss.ipfs.io . You can log in with Github in 2 clics.

**Comment by Freeland90** [comment]
Thanks my man.
