### ISSUE TITLE
Clarify OS versions for IPFS desktop and command line availability.

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#365]
For reference, please see https://github.com/ipfs-shipyard/ipfs-desktop/issues/1565#issuecomment-654349731 -- unfortunately, can't migrate this issue straight into this repo as it's in another org.

@tekbear raised the following:

Reading main page and I cannot determine what OS versions you support - perhaps you could fix that if not already covered.
Which versions of Windows OS will run IPFS -desktop and is the answer the same for the command line ?

This is my first look at your project and I think you should be precise about which windows version are supported on your main page - https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/README.md the majority of projects do this. System requirements is a documentation issue that needs fixed by someone on project team.

**Comment by johnnymatthews** [comment]
This is a good point. Let's point out which versions of each OS are supported on the installation pages. Supported Linux distros could be tricky since there are _so many_, but we could just focus on Ubuntu.

**Comment by olizilla** [comment]
For ipfs-desktop there is no obvious reason why it shouldn't work where ever electron works, see: https://www.electronjs.org/docs/tutorial/support#supported-platforms

As for go-ipfs it should work on anywhere a go binary can be compiled for as long the cpu architecture is one of the supported flavours on https://dist.ipfs.io/#go-ipfs

To the best of my knowledge we have not formally defined a commitment to "known to work and formally supported on X platforms". There is a big gap between, our base expectation _it should run pretty much anywhere_ and what we have the bandwidth to test and verify on.

It makes sense to add a "minimum OS" note for ipfs-desktop, but it's less clear what the message should be for go-ipfs.

**Comment by johnnymatthews** [comment]
The fact that IPFS Desktop runs on Electron makes this a whole lot easier then. I imagine users running Go/JS/Rust IPFS are likely more interested in resource requirements (RAM, HDD space, etc) rather than OS specifications.

For this issue, let's say that IPFS Desktop supports whatever Electron supports. This is from the page @olizilla linked:

> ## macOS
> 
> Only 64bit binaries are provided for macOS, and the minimum macOS version supported is macOS 10.10 (Yosemite).
>
> ## Windows
>
> Windows 7 and later are supported, older operating systems are not supported (and do not work).
> 
> Both ia32 (x86) and x64 (amd64) binaries are provided for Windows. Electron 6.0.8 and later add native support for Windows on Arm (arm64) devices. Running apps packaged with previous versions is possible using the ia32 binary.
> 
> ## Linux
>
> The prebuilt ia32 (i686) and x64 (amd64) binaries of Electron are built on Ubuntu 12.04, the armv7l binary is built against ARM v7 with hard-float ABI and NEON for Debian Wheezy.
>
> Until the release of Electron 2.0, Electron will also continue to release the armv7l binary with a simple arm suffix. Both binaries are identical.
>
> Whether the prebuilt binary can run on a distribution depends on whether the distribution includes the libraries that Electron is linked to on the building platform, so only Ubuntu 12.04 is guaranteed to work, but following platforms are also verified to be able to run the prebuilt binaries of Electron:
>
> - Ubuntu 12.04 and newer
> - Fedora 21
> - Debian 8

As for docs like the command-line quickstart, we can say something like "_Hey, you need Go 1.x installed_", or something to that effect.

- [ ] Add OS requirements to IPFS Desktop installation.
- [ ] Add Go requirements to command-line quickstart.

**Comment by olizilla** [comment]
The prebuilt binaries for go-ipfs don't require the user to have go installed. They are self-contained, executable files. 

We currently only build ipfs-desktop for a subset of the architectures we could possibly do... only `amd64` architecture CPUs, so not i32, or any of the arm flavours, so: >= Windows 7 x64, macOS 10.10 (Yosemite) x64,  Ubuntu 12.04 x64.

**Comment by johnnymatthews** [comment]
Nice, thanks @olizilla. I've updated the tasks.

Regarding Go-IPFS: is it correct to assume that if you can _build_ the project and create an executable, it will run? Like, if someone managed to install Go on an Amega and built the repo, could it potentially work?

**Comment by johnnymatthews** [comment]
This issue was closed in #584.
