### ISSUE TITLE
Create pages for implementations of IPFS in popular languages other than the official implementations.

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#403]
Right now we official implementations and places where IPFS is distributed.

We should also have a page or section for language-specific helpers:

* Haskell - https://hackage.haskell.org/package/ipfs-1.1.2
* Python - https://github.com/ipfs-shipyard/py-ipfs-http-client
* ... surely there are more

**Comment by johnnymatthews** [comment]
This is a good idea, and fits quite well into my plan of having an implementations section:

```
/implementations
    /go
    /javascript
    /rust
    /other implementations
        /python
        /haskell
        /lisp*
```

\* Surely someone out there is building Lisp IPFS.

**Comment by johnnymatthews** [comment]
There's a big list of [implementations in ipfs/ipfs](https://github.com/ipfs/ipfs#http-client-libraries), but many of them are out-of-date/inactive. Adding those implementation into this repo won't be particularly useful.
