### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by KattyMan06** [ipfs/ipfs-docs#405]
When I run `curl --output POST "https://ipfs.infura.io:5001/api/v0/get?arg=/ipfs/QmVH87Cs7e1eK4n5yRnstkbMghVCf3skp45ywitWESAvQL"` it return a text document named POST that shows the directory of the file instead of the jpg that I had added to ipfs

I run `curl -X POST -F file=$"/Test/LUNG\ CANCER\ CT\ TEST/tesst.jpg"  "https://ipfs.infura.io:5001/api/v0/add?quieter=true"` to add the jpg file to ipfs

**Comment by johnnymatthews** [comment]
Hi @KattyMan06. Is this a request for support, or did you find some documentation that needs updating/fixing?

**Comment by johnnymatthews** [comment]
Gonna close this one since we didn't get a response from @KattyMan06. Feel free to reopen this issue if you're still having problems.
