### ISSUE TITLE
Stop Prettier auto-formatting tables to be full width of content.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#446]
There's an issue-by-design in Prettier where it will automatically have the table widths in markdown extend to the length of the content. For example:

```markdown
| [Browser Companion](https://github.com/ipfs-shipyard/ipfs-companion) | [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop) | [IPLD Explorer](https://explore.ipld.io/) |
| --- | --- | --- |
| ![The IPFS browser companion in Firefox.](./images/ipfs-companion.png =300x200) | ![The IPFS desktop app running on MacOS with the status tab open.](./images/ipfs-desktop.png =300x200) | ![The IPLD Explorer homepage.](./images/ipld-explorer.png =300x200) |
```

Becomes

```markdown
| [Browser Companion](https://github.com/ipfs-shipyard/ipfs-companion)            | [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop)                                          | [IPLD Explorer](https://explore.ipld.io/)                           |
| ------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------- |
| ![The IPFS browser companion in Firefox.](./images/ipfs-companion.png =300x200) | ![The IPFS desktop app running on MacOS with the status tab open.](./images/ipfs-desktop.png =300x200) | ![The IPLD Explorer homepage.](./images/ipld-explorer.png =300x200) |
```

Looks fine in GitHub when text-wrapping isn't enabled, but it becomes a mess when it is:

![image](https://user-images.githubusercontent.com/9611008/92611705-6eb7b600-f28f-11ea-9fbc-da3ce1dd6768.png)

I'm pretty sure there's an option in Prettier to disable extending the table to fit the contents _if_ the contents goes over a certain number of characters.

**Comment by cwaring** [comment]
I think this behaviour has changed in the [recent version of prettier](https://github.com/prettier/prettier-vscode/issues/762), try reinstalling your deps with `npm ci` and lmk if that fixes it.

**Comment by johnnymatthews** [comment]
Ah, so looks like we just need to add `"proseWrap": "never"` to `package.json`.

**Comment by johnnymatthews** [comment]
This isn't really an issue anymore. Closing :)
