### ISSUE TITLE
Host a Git-style repo

### ISSUE THREAD

**Issue by jamiehewitt15** [ipfs/ipfs-docs#456]
When following the Git-style repo tutorial, I have successfully uploaded my repo to IFPS with `ipfs add -r .` However, when I try to download it with `git clone` I am getting the error message below. 

Is anyone able to help me with this? I'm not sure what I have done wrong.

```
git clone http://localhost:8080/ipfs/QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq
Cloning into 'QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq'...
fatal: unable to access 'http://localhost:8080/ipfs/QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq/': Failed to connect to localhost port 8080: Connection refused
```

**Comment by johnnymatthews** [comment]
Hmm, that's odd. Just to double check, can you make sure that you've got an IPFS daemon running? Either using Go-IPFS or IPFS Desktop.

This tutorial is fairly old (in IPFS terms), so it likely needs a revision. I'll run through today to make sure nothing's completely broken.

**Comment by johnnymatthews** [comment]
Never mind! It's because the URL structure changed. So instead of

```bash
git clone http://localhost:8080/ipfs/QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq
```

It should be

```bash
git clone http://QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq.ipfs.localhost:8080/
```

Give that a try. I'll change the tutorial :)

**Comment by jamiehewitt15** [comment]
Thank you for your help @johnnymatthews I really appreciate it. Although, unfortunately there is still an issue here. 

If I run:
`git clone http://QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq.ipfs.localhost:8080/`

I get the following error message:
`fatal: unable to access 'http://QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq.ipfs.localhost:8080/': Could not resolve host: QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq.ipfs.localhost`

However, I have managed to get it working by running:
`git clone http://127.0.0.1:8080/ipfs/QmYgyahQoikJEbZEkiubwxm16xjCAZs2RUd1qfuus2Zyeq`

I have got the daemon running. Could the issue be due to the fact that I'm running the commands on windows?

**Comment by johnnymatthews** [comment]
It's unlikely this is a _Windows_ issue. Do you know which version of IPFS you're running? You can find out by running `ipfs --version` in a terminal:

```bash
$ ipfs --version

ipfs version 0.6.0
```

**Comment by jamiehewitt15** [comment]
I'm running ipfs version 0.6.0

I think the problem must be due to the redirect, as it worked fine when I requested from the IP address. I think it might be related to this issue: https://github.com/ipfs/go-ipfs/issues/7527

**Comment by johnnymatthews** [comment]
Ah, I think you're right. I'm gonna leave this issue as closed for now then.
