### ISSUE TITLE
Case studies: Holding pen for new subjects

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#487]
This issue is a holding pen for future [case studies](https://docs.ipfs.io/concepts/#examples-and-case-studies) to include on the docs site. (Individual case studies will be worked in their own issues.) Please feel free to comment and nominate more!

Note: As of October 2020, this series is temporarily on hold until we get some time/space out from Filecoin mainnet launch; anticipating that we'll see some focus shift in new IPFS implementers as a result, and want to cover any changes adequately!

- Actyx ([nominated from forums](https://discuss.ipfs.io/t/new-case-study-likecoin-a-decentralized-publishing-ecosystem/9192/2))
- Peergos ([nomination](https://discuss.ipfs.io/t/new-ipfs-case-study-fleek/9016))
- DTube ([nomination](https://discuss.ipfs.io/t/new-ipfs-case-study-fleek/9016))

**Comment by yyd106** [comment]
I want to nominate [Crust Network](https://crust.network), a blockchain based decentralized IPFS pinning service powered by Polkadot technologies.

## Use Cases:
1. [**Uniswap**](https://app.uniswap.org), has enabled decentralized deployment of websites by integrating [Crust Network](https://crust.network) into [Uniswap's release workflow](https://github.com/Uniswap/uniswap-interface/blob/main/.github/workflows/release.yaml). More details of this integration is in [Decentralized Uniswap Interface Hosting on IPFS](https://medium.com/crustnetwork/decentralized-uniswap-interface-hosting-on-ipfs-18a78d1209ac).

2. The same integration was later realized by [**Polkadot**](https://polkadot.network/), the [PolkaApps](https://dotapps.io/) is now hosted on Crust Network decentralized. 

For each release of Uniswap Interface and Polakdot Apps, their frontend replicas will be distributed into 100+ IPFS nodes in Crust Network.

## About Crust

**GitHub URL**
https://github.com/crustio/crust

**Docs URL**
https://wiki.crust.network/en

**Additional context**
Now Crust is running preview network Maxwell and got 1000+ nodes joined in to provide IPFS storage (https://telemetry.polkadot.io/#list/Crust%20Maxwell).

**Comment by jessicaschilling** [comment]
@yyd106 - are you a representative of Crust? If so, would you mind filling in the quick survey [here](https://airtable.com/shrjwvk9pAeAk0Ci7) — it would be good to get Crust included in a new IPFS ecosystem directory that we're currently building. Thanks!

**Comment by yyd106** [comment]
Sure, Thanks @jessicaschilling. I submitted the survey, waiting for the follow up contact.

**Comment by jessicaschilling** [comment]
Thanks, @yyd106! Confirming it was received and will be added to the ecosystem directory for release later this quarter. Keep an eye on IPFS social media and blog.ipfs.io for word when it's launched 😊

**Comment by yyd106** [comment]
Cool, thanks for you support! On the other hand, we are more concerned about contributing to the "case study" mentioned earlier. We would like to contribute two articles, one on how Uniswap uses IPFS to deploy DApp Interface from a third-party perspective, and the other on how Crust provides decentralized Pinning Service based on IPFS.

**Comment by yyd106** [comment]
Cool, Thanks a lot!
We are also interested in contributing to "case study" section as we have previous mentioned. Specifically, we would like to contribute two articles. One from a third-party perspective is on how Uniswap deploys DApp Interface using IPFS, and the other is on how Crust provides decentralized pinning services based on IPFS.
We will compose both articles in the “case study” format and submit for review after we finish.

**Comment by yyd106** [comment]
@jessicaschilling I created a PR #783 to put Crust into the case studies as previous mentioned.

**Comment by jessicaschilling** [comment]
Thanks, @yyd106 — going to refer that PR to @johnnymatthews since he's the owner of the docs site!

**Comment by yyd106** [comment]
Hi @jessicaschilling , 
Recently we have published another IPFS-based open source project named "Encrypted IPFS" (https://github.com/crustio/encrypted-ipfs). It is a pure technical project without any cryptocurrency. It is to provide an encrypted storage layer of IPFS that supports a customized encryptor so that underlying IPFS objects can be stored in an encrypted way.
We wish to contribute it to IPFS community and invite more developers to contribute as well. We plan to tweet and publish it in our technical channels (discord), and if you could help retweet that would be great! Kindly let us know if it is OK, then we can go to tweet and publish.

**Comment by TMoMoreau** [comment]
We're no longer following this initiative, closing.
