### ISSUE TITLE
Explain how to share CIDs of files that are constantly updating.

### ISSUE THREAD

**Issue by atopal** [ipfs/ipfs-docs#495]
This is a thought based on the conversation here: https://www.reddit.com/r/ipfs/comments/j84j15/ipfs_paradox_cant_find_the_answer_anywhere/

DNSLink doesn't come up in that conversation (which seems to be the preferred way?). The docs mention the issue in multiple places, eg. [concepts/p2psharing/ipns/](https://docs.ipfs.io/concepts/ipns/) and [How-tos/Websites on IPFS/Link a domain](https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/). Maybe it would be useful to address that common problem higher up in the hierarchy?

**Comment by johnnymatthews** [comment]
Here's the original question from Reddit (just in case it gets deleted over there):

> say I have a website hosted on IPFS, how do I publish my current website ipfs hashes on that website so that people can help pin the files? - [Eastlondonmanwithava](https://www.reddit.com/r/ipfs/comments/j84j15/ipfs_paradox_cant_find_the_answer_anywhere/)

Here's a vaulable reply from [DavidBurela](https://www.reddit.com/r/ipfs/comments/j84j15/ipfs_paradox_cant_find_the_answer_anywhere/g8995uq/):

> You mentioned you are using ENS. You can direct your users to pin your site via that e.g. `ipfs pin add /ipns/Eastlondonmanwithava.ETH`
>
> You could even direct them to pin individual pages by putting their relative path in, e.g. `ipfs pin /ipns/Eastlondonmanwithava.ETH/about.html`. Although that may not include any images that page links to.
>
> As long as are updating ENS with your website's root hash, it should all work fine.
>
> Side note, this is actually how I direct my VMs to pin my blog. I just have a cron job running every 15 minutes, that just runs `ipfs pin add /ipns/blog.DavidBurela.eth`

**Comment by BlocksOnAChain** [comment]
I believe we have the info listed here: https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli
