### ISSUE TITLE
Configure a node unclear formulation "around the country"

### ISSUE THREAD

**Issue by LudwikJaniuk** [ipfs/ipfs-docs#514]
I would just like a clarification on the last paragraph. 

> The Bootstrap config array specifies the list of IPFS peers that your daemon will connect to on startup. The default values for this are the 'ipfs solarnet' nodes, which are a set of VPS servers distributed around the country.

Around which country? Or do you mean around the world?

**Comment by johnnymatthews** [comment]
Correct, looks like that's a long buried error. Thanks for bringing it up! #519 closes this issue.

**Comment by LudwikJaniuk** [comment]
Thank you for fixing it and being responsive!
