### ISSUE TITLE
Explain how nodes interact over a private network.

### ISSUE THREAD

**Issue by padmanabhak** [ipfs/ipfs-docs#521]
I am not sure if the windows ipfs and linux ipfs versions have to be the same for private cloud to work. It seems like windows version and linux version numbers are different and not sure if they are compatible.

Documenting the private cloud setup and compatibility will help.
thx

**Comment by johnnymatthews** [comment]
Just out of curiosity, what are you trying to do with IPFS @padmanabhak?

**Comment by padmanabhak** [comment]
Have setup a private ipfs linux bootstrap.Windows and Linux ipfs are nodes on the private network.

Sent via the Samsung Galaxy Note9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
