### ISSUE TITLE
[DOCS ISSUE] (add your title here!)I quit before beginning

### ISSUE THREAD

**Issue by nomaga** [ipfs/ipfs-docs#528]
Hello,
I was very interested in IPFS till I discovered : 1) It uses GO (google) 2) It uses github (microsoft) 3) It uses Snap on linux.
Too bad :( I'm outta here.

**Comment by johnnymatthews** [comment]
If you're looking for a discussion on these points, [the forum would be a better place](https://discuss.ipfs.io/).
