### ISSUE TITLE
Augment privacy concept guide with more detailed topics

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-docs#560]
We've got https://docs.ipfs.io/concepts/privacy/ as a very high-level guide to IPFS and privacy aimed toward IPFS newcomers (this is linked to from Brave's node prefs). Let's augment it with a more detailed guide to IPFS, privacy, and suggestions/pointers for mitigating potential privacy concerns. Suggestions:
- Break out into additional page(s), so as not to make the high-level guide overwhelming
- Augment with some sort of (possibly flowchart-based) visual guide to IPFS and privacy (see https://github.com/ipfs/ipfs-docs/pull/554#pullrequestreview-548644037 for thoughts), and possibly include a simplified version of that in the high-level guide as well

**Comment by BlocksOnAChain** [comment]
https://docs.ipfs.io/concepts/privacy-and-encryption/#enhancing-your-privacy - this should be closed by using the provided link
