### ISSUE TITLE
[DOCS ISSUE] Personal storage basics

### ISSUE THREAD

**Issue by craigallan** [ipfs/ipfs-docs#590]
Hi. Here are some questions I cannot find answers for. No doubt others will be interested too. Perhaps add to the docs answers to these questions...

1. Donate to the Cause - As in BitTorrent, does ipfs use local storage on my machine for random files (or pieces) placed by random strangers? 
2. Pay for Play - Can I limit the use of my rather expensive storage space? 
3. Pay for Play - I only have metered bandwidth - so can I throttle ipfs bandwidth used by random strangers?
4. Under arrest - Am I legally liable for the content random strangers place on my machine - like child porn for example?  
5. Tragedy of the Commons - Can I (or anybody) use ipfs as a private gigantic limitless storage resource? 
6. Crud creation - Does ipfs clean up untouched (abandoned) files (or pieces) - if not who pays for the storage they waste? 
7. Resilience - Does ipfs keep multiple copies of files (or pieces) - and if not, what happens if the one copy is corrupted or lost?
8. Crud creation - If I change a few bytes and regularly hit ^s to save changes, as one does, does that auto-archive a piece of the old version forever - and clog up my (and ipfs)  storage space with that dead one piece per edit?

Ok, that is a start. I'd suggest making those answers up front and clear somewhere on the ipfs.io website.

**Comment by johnnymatthews** [comment]
> Donate to the Cause - As in BitTorrent, does ipfs use local storage on my machine for random files (or pieces) placed by random strangers?

[No](https://docs.ipfs.io/concepts/privacy/#controlling-what-you-share)

> Pay for Play - Can I limit the use of my rather expensive storage space?

[Yes](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#datastorestoragemax).

> Pay for Play - I only have metered bandwidth - so can I throttle ipfs bandwidth used by random strangers?

There is no _built-in_ way to do this with any of the IPFS releases. However, it's a good idea! Why not raise an issue in the [Go-IPFS repo](https://github.com/ipfs/go-ipfs/issues)? 

> Under arrest - Am I legally liable for the content random strangers place on my machine - like child porn, for example?

I think you misunderstand how IPFS works. Like your first question, IPFS does not turn your computer into a remote node for other users. You select what data you would like to store.

> Tragedy of the Commons - Can I (or anybody) use ipfs as a private gigantic limitless storage resource?

If you were to convince every user that is running an IPFS node that they should share your data, potentially. But in realistic terms, no. Again, each node chooses what it wants to store. 

> Crud creation - Does ipfs clean up untouched (abandoned) files (or pieces) - if not who pays for the storage they waste?

Yes. The term you're looking for is [garbage collection](https://docs.ipfs.io/concepts/glossary/#garbage-collection).

> Resilience - Does ipfs keep multiple copies of files (or pieces) - and if not, what happens if the one copy is corrupted or lost?

No. If a block of data becomes _corrupt_, it will have a different CID from when it was not corrupt. If another node is hosting the original block, your IPFS node can request that block. Take a look at [content addressing](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats).

> Crud creation - If I change a few bytes and regularly hit ^s to save changes, as one does, does that auto-archive a piece of the old version forever - and clog up my (and ipfs) storage space with that dead one piece per edit?

Take a look at [File systems and IPFS](https://docs.ipfs.io/concepts/file-systems/#mutable-file-system-mfs).
