### ISSUE TITLE
Add an explanation of what each profile does in the "Available profiles" section.

### ISSUE THREAD

**Issue by Kaezon** [ipfs/ipfs-docs#604]
Currently, the "Available profiles" section of default-profile.md simply enumerates valid IPFS profiles.
Could it perhaps be expanded to include some explanation of what each profile is, or else link to a document which does?

**Comment by johnnymatthews** [comment]
Just to check we're on the same page, [are you referring to this section](https://docs.ipfs.io/how-to/default-profile/#available-profiles) @Kaezon ?

**Comment by Kaezon** [comment]
Correct. That's the one.

**Comment by johnnymatthews** [comment]
## Tasks

- [ ] Write a single sentence defining what each of the [profiles listed in /how-to/default-profile](https://docs.ipfs.io/how-to/default-profile/#available-profiles) does.

**Comment by Annamarie2019** [comment]
I'll take this one.

**Comment by johnnymatthews** [comment]
Assigned!

**Comment by Annamarie2019** [comment]
I created a pull request, but I don't think I'm doing it right, bc it isn't showing on the Pull Requests tab. I'm researching and if we meet on this again (or on anything), I shall record.
<img width="1008" alt="#604_Adds explanation of each profile" src="https://user-images.githubusercontent.com/46230706/151884952-21ec52f9-bee8-4b81-95a6-5270a1bbc5b6.png">

**Comment by Annamarie2019** [comment]
submitted as PR #1018

**Comment by Annamarie2019** [comment]
This issue is taken up in https://github.com/ipfs/ipfs-docs/pull/1024 now.
Sorry, we were learning the PR workflow and I did this first directly in the editor, then forked, but #1024 represents the full Branch workflow with both articles involved.

**Comment by Annamarie2019** [comment]
It seems to me that this issue for [default-profiles.md](https://docs.ipfs.io/how-to/default-profile/url) should not be closed yet. [Issue #1024](https://github.com/ipfs/ipfs-docs/pull/1024) addresses it and is still outstanding. 

Sorry for the confusion. It's due to my learning curve for git best practices and the current organization of the ipfs doc.

**Comment by Annamarie2019** [comment]
I fixed the issue with multiple extraneous files coming in by closing old PRs and deleting branches.

I created a new PR: [#1052](https://github.com/ipfs/ipfs-docs/pull/1052)

**Comment by johnnymatthews** [comment]
https://github.com/ipfs/ipfs-docs/pull/1052 has been merged. Can we close this issue now @Annamarie2019 ?
