### ISSUE TITLE
Pin files - ipfs pin doesn't behave as predicted on the page

### ISSUE THREAD

**Issue by dbclinton** [ipfs/ipfs-docs#621]
Hi,
I'm playing with `ipfs pin` and read [this page](https://docs.ipfs.io/how-to/pin-files). Adding a file using `ipfs add` does create a recursive pin as suggested but, on my v. 0.7.0 system at least (running in an Ubuntu 20.04 LXD container), `ipfs pin rm` will successfully unpin it, even without adding `-r`. 
Has IPFS functionality changed since this page was last updated?
Thanks,

**Comment by johnnymatthews** [comment]
Hi @dbclinton, yeah it looks like this functionality has changed but these specific docs weren't updated. I've changed the title and tags to reflect what needs to be done here. Thanks for bringing this up!
