### ISSUE TITLE
IPNS

### ISSUE THREAD

**Issue by adrapper** [ipfs/ipfs-docs#622]
I think I understood the principle of using IPNS, but have a few questions this page has not answered.

My biggest issue is that this is all back in the Terminal and for now I am trying to be an ordinary person and work with GUI products. I know I may end up having to get back into command line work, but if it ends up there, IPFS will only be for the few, never for the world. 

Can I "Publish your Qm hash to IPNS:" as it were or point an IPNS CID to my website CID as I believe we are doing in the IPFS Desktop?

And when we get to Alternatives to IPNS. Is there yet any consensus on what is the very best and most decentralized way to give a static address to a changing website?

**Comment by johnnymatthews** [comment]
> this is all back in the Terminal

Right now, there are no GUI implementation to help folks deal with IPNS, unfortunately.

> point an IPNS CID to my website CID

Yes! In the [Link a domain](https://docs.ipfs.io/how-to/websites-on-ipfs/link-a-domain/#domain-name-service-dns) section of the **Website on IPFS tutorials**, just swap out `SITE_CID` with the address you get from running `ipfs name publish /ipfs/QmaM...`

> Alternatives to IPNS

Some people find [DNS link](https://docs.ipfs.io/concepts/dnslink/#publish-using-a-subdomain) a bit easier to use, but it's a personal preference.
