### ISSUE TITLE
Clarify how the IPFS gateways managed by Protocol Labs deal with legal takedown requests.

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#642]
See this thread: https://www.reddit.com/r/ipfs/comments/ljosj1/does_all_content_published_to_public_ipfs/

There's some confusion about what we mean in that section of docs. Should clarify the OP's question and also address other comments in thread if needed.

**Comment by johnnymatthews** [comment]
Content copy and pasted from the [Reddit post](https://www.reddit.com/r/ipfs/comments/ljosj1/does_all_content_published_to_public_ipfs/), just in case the thread goes missing:

> Does "All content published to public IPFS infrastructure is hosted at the sole discretion of the IPFS team" refer to a backdoor in IPFS that allows central control of what is uploaded and downloaded between 2 consenting peers?
>
> Its a quote from https://github.com/ipfs/community/blob/master/code-of-conduct.md Or does it just refer to what might, for example, be in https://github.com/ipfs/ but not in possible opensource forks of IPFS and the network?
> 

Answers

> Nope, this only applies to "public IPFS infrastructure" such as their public gateways and nodes. So what this means is that if you use the public ipfs.io HTTP gateway, they can blacklist certain CIDs from that gateway if they were required to for legal reasons.
> 
> This doesn't affect any other nodes on the network, and even then you can usually get around it by using a different public gateway.
> 
> It's the same way that you can blacklist any CIDs you don't want from being served on your local node. - Evanito

> I don’t recall seeing any functionality that would allow them to block p2p transfers between two peers. I suspect it’s mainly to protect themselves in case illegal content ended up on their infrastructure - chafey

> I don't really see what they can do besides a blacklist for certain CIDs, that a fork could easily ignore. - Mithrandir2k16

**Comment by johnnymatthews** [comment]
This content is actually already listed in the [IPFS Gateway FAQs](https://docs.ipfs.io/concepts/ipfs-gateway/#frequently-asked-questions-faqs). Closing :)
