### ISSUE TITLE
Clarify Protocol Labs project specific styling guidelines.

### ISSUE THREAD

**Issue by ardunster** [ipfs/ipfs-docs#654]
As I've been going through the IPFS docs, I've been preparing a commit with a number of typo corrections, formatting corrections, etc. I have, for example, been converting all non-code-block cases of ipfs to IPFS, since that seems to be the overall trend in the documentation. 

However, I'm unsure of the preferred style for Go-IPFS and JS-IPFS.  Are they preferred capitalized like that, or lower case like go-ipfs and js-ipfs? I've seen them about equally in both formats in various places throughout. 

Some kind of official preference, possibly included into the Contribution Guidelines, would be helpful! 
Thanks.

**Comment by johnnymatthews** [comment]
> I'm unsure of the preferred style for Go-IPFS and JS-IPFS.

It's a bit of a _hot topic_. Both Go-IPFS and JS-IPFS are the preferred style within this repo. The reasoning for this is that they are both the _names_ of something, similar to how the _Windows 10_ and _Big Sur_ operating systems are capitalized. Currently, their respective repos use the lower-case versions however.

**Comment by ardunster** [comment]
That definitely makes sense to me why the discrepancy would exist. I'm sure it's easy for people writing quickly to not bother with capitalizations, even if capitalization has a more professional and official look more appropriate for documentation.
