### ISSUE TITLE
Add "AppImage" option for IPFS Desktop install.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#672]
The IPFS Desktop repo is now using AppImage as a preferred install option. Due to the issues that Snap can cause with IPFS, we should point readers towards installing the app using the provided `AppImage` file instead. This issue was created because of https://github.com/ipfs-shipyard/ipfs-desktop/pull/1776

## Files

- [/install/ipfs-desktop/](https://github.com/ipfs/ipfs-docs/blob/main/docs/install/ipfs-desktop.md)

## Tasks

- [x] Remove Snap from the [Package manager](https://docs.ipfs.io/install/ipfs-desktop/#ubuntu) section.
- [x] Replace `.deb` with `.AppImage` under the [Ubuntu](https://docs.ipfs.io/install/ipfs-desktop/#ubuntu) section.

**Comment by lidel** [comment]
Sgtm.  Main value provided by AppImage is autoupdates independent from package manager provided by OS.

**Comment by johnnymatthews** [comment]
Merged into staging.
