### ISSUE TITLE
Explain what the Prometheus API is, and add some examples.

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#682]
Implemented originally here: https://github.com/ipfs/go-ipfs/pull/1422

Also something newer here: https://github.com/ipfs/go-metrics-prometheus

**Comment by autonome** [comment]
Some cluster + Prometheus docs, maybe relevant:

https://cluster.ipfs.io/documentation/guides/opencensus/

https://simpleaswater.com/tracing-and-monitoring-ipfs-cluster/

**Comment by AlexxNica** [comment]
I think I can get this one. Do you have more info for the bounty (numbers, tasks)?

**Comment by johnnymatthews** [comment]
I'm not really sure why I threw the `bounty` tag on here, I usually have the tasks fleshed out before I do that. Ah well, here we are. I'm gonna take the bounty tag off for now while I find out _what_ exactly we need to document. I'm assuming it's along the lines of:

1. What Prometheus is/does.
2. How to use it.

Once I've got a task list ready to go I'll tag you again @AlexxNica and you can see if you wanna tackle it. Sound good?

**Comment by AlexxNica** [comment]
@johnnymatthews Perfect! Thank you! 🙌
