### ISSUE TITLE
Create some basic deployment-behind-a-http-front-end configuration examples.

### ISSUE THREAD

**Issue by ribasushi** [ipfs/ipfs-docs#687]
Both novices and experienced administrators would benefit from short samples describing typical deployment of go-ipfs fronted by an authenticating nginx or apache http server.

Novices would benefit from a dramatic reduction of the cognitive overload needed to deploy an IPFS node with a let-sencrypt wss-enabled listener and an exposed 5001 API with the proper basic http access controls.

Experts would benefit from eyeballing such a sample config and going "ok, all of this is as I expect it"  / "oh, this piece here looks odd, I need to read more"

cc @autonome @lidel

**Comment by autonome** [comment]
This is a really common use-case, and gets asked all the time. Yes, please to a detailed step-by-step guide.

**Comment by johnnymatthews** [comment]
This sounds very handy. Would you be interested in creating a draft for this @ribasushi, or tagging someone else that would?
