### ISSUE TITLE
Refactor the "Implementation status" page.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#697]
As mentioned by @lidel and @gozala in #678, the [Implementation status page](https://docs.ipfs.io/project/implementation-status/) could do with a revamp.

First off, it's out of date. We need to go through and check if each feature is available/implemented yet in each product.

Secondly, as [@gozola pointed out in a different thread](https://github.com/ipfs/ipfs-docs/issues/678#issuecomment-793094309), things are a bit more complicated than a simple _X_ has _Y_. Sometimes _X_ has a subset of _Y_, while _Z_ contains a different subset of _Y_.

I don't have enough knowledge or bandwidth to tackle this solo. @Gozala would you be interested in helping out here?

**Comment by Gozala** [comment]
> I don't have enough knowledge or bandwidth to tackle this solo. @Gozala would you be interested in helping out here?

I'd love to, with a caveat that my bandwidth is also limited. Let me know what would be a best way to contribute.

**Comment by DannyS03** [comment]
Updates to follow in the scope of: https://github.com/ipfs/ipfs-docs/issues/1360
