### ISSUE TITLE
Explain how to use IPFS in a private setting (internal network, intranet, etc).

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#703]
Someone asked about this at a hackathon and while there are loads of stuff *not* from us (if you DDG it), there's only a go-ipfs CLI parameter documentation from official project sources AFAICT.

**Comment by johnnymatthews** [comment]
Just so we're on the same page; you'd like to see a guide on how to set up a private/internal IPFS network for use inside an office, or a home media cluster, something like that. Right? Or am I missing the point?

**Comment by autonome** [comment]
There are loads of use-cases. Eg, if you do not want to risk your connection, identity, transfer metadata or communication patterns being tracked on the public DHT, you might set up your nodes to directly connect to each other *only*.

So basically a guide/tutorial for using and deploying this: https://github.com/ipfs/go-ipfs/blob/v0.8.0/docs/experimental-features.md#private-networks
