### ISSUE TITLE
Filesystem CRUD guide with tabbed examples for curl, CLI and API

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#705]
Need a one-stop-shop guide which covers typical filesytem operations: import, add, delete, move, rename, etc which has examples for each of curl, IPFS CLI and our programmatic API via js-ipfs-http-client / js-ipfs.

After #704 I talked with the person about what would've got them unblocked quickly.

> assuming you are aiming for a doc for all purposes, then I would prefer guide that covers the typical operations, with examples in all scenarios (cli, curl, sdk) in a compact form that does not scare the reader (e.g. every example in a box, with tabs for cli/curl/sdk)

> and examples have to be "complete" (e.g. foo.txt, bar.txt and not reference style as they are now) because while the dev is trying to understand IPFS you dont want him to struggle with cli/curl syntax and you can not assume he is an expert on that either.

**Comment by johnnymatthews** [comment]
I agree; this would be super useful to have. This could be bountyable, but we need to flesh out this issue a bit more. Are these all the operations we'd need to document?

1. import
2. add
3. delete
4. move
5. rename

**Comment by lidel** [comment]
I believe this could be picked up when we have `ipfs files add` (https://github.com/ipfs/go-ipfs/pull/8637) in both go and js – having that porcelain and working with MFS directly from the start will be a game changer.
