### ISSUE TITLE
Discover and explain how IPFS + IPNS deal with making changes to a pinned file.

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#712]
get variations on this question, sometimes ipns but also regular ipfs too

https://www.reddit.com/r/ipfs/comments/m94t1j/does_an_ipns_pin_update_itself_automatically_on/

**Comment by johnnymatthews** [comment]
Here's the main question from that thread:

> if I publish a folder (with an IPNS address) from my node1, I pin that folder to the node2 (I suppose you can pin IPNS address?), then I make change to it on the node1 and publish the change, does the node2 will update the content automatically (since it use the IPNS address)?

It's a pretty solid question, and I'm not actually sure of the answer.
