### ISSUE TITLE
Advertise Truffle as an alternative to using Minty in the NFT tutorial.

### ISSUE THREAD

**Issue by dineshshenoy** [ipfs/ipfs-docs#727]
I wanted to add Truffle as another development option for folks who are new to the NFT space.  Can we add this alongside the Minty recommendation?  Many web3 developers from the Ethereum space are famliar with this tool kit.

Truffle (https://www.trufflesuite.com) has developed a set of tools for blockchain applications that can also be used to create an NFT on the Ethereum network backed by IPFS assets.  Check out this Truffle Box (https://www.trufflesuite.com/boxes/filecoin) for more details.

**Comment by johnnymatthews** [comment]
Sorry for the delay in getting to this one @dineshshenoy. What would you like to see here? As far as I know, Truffle helps developers make Ethereum smart contracts and test them locally.

> alongside the Minty recommendation

I guess we could. One of the benefits of using Minty is that it's pretty simple and easy to follow. Truffle has a lot of stuff happening behind-the-scenes that could confuse folks new to blockchain stuff. Saying that, we could add a call out within the Minty tutorial saying something like "_Hey, you can use Truffle for this too, if you know what you're doing._

**Comment by dineshshenoy** [comment]
So there are two benefits two truffle:
1) Existing Ethereum developers who are already familiar with the Truffle product line.  Many of them are new to the Filecoin network and this is a great jump start for that audience.

2) Truffle's simulator is a cool getting-started nerpanet experience.  It's super visual and shows a network creating blocks, sending messages, gas fees, wallets, etc. in a very user friendly way.

#1 is probably the right focus for this page - and I think it's more about awareness that there are other 3rd party tools that can be used here (Truffle and Consensys more broadly have a lot of web3 users). Since there's a FIlecoin specific tutorial - we should share that info.   

Truffle is also a way to path towards production as they become more advanced.

**Comment by johnnymatthews** [comment]
Cool beans, sounds like it'd be useful to point out how to use Truffle alongside Minty. @yusefnapora, did you happen to play around with Truffle during your NFT adventures? If so, how would you recommend we include it in this guide?

**Comment by yusefnapora** [comment]
That's a great idea - I played a bit with Truffle while following along with Pinata's tutorials before I started on Minty. It's great, and the Filecoin box thing is pretty cool as well.

I'll work in a reference in the docs here, and maybe mention it in the Minty readme as well as an alternative to HardHat.
