### ISSUE TITLE
Document language selection

### ISSUE THREAD

**Issue by renzhengwei** [ipfs/ipfs-docs#731]
Document distinguishing language will make users better read and recognize IPFS, such as Chinese, Russian and so on.

**Comment by renzhengwei** [comment]
Maybe we can use Google Web translation ？But it's not particularly accurate.

**Comment by johnnymatthews** [comment]
Issue #268 is a discussion on possible localization strategies. The TLDR is that it's tricky, and requires a lot of effort. Given the resources this docs project has right now, it's low priority.
