### ISSUE TITLE
Example in "what is ipfs" is broken

### ISSUE THREAD

**Issue by andoneN4** [ipfs/ipfs-docs#732]
Hi,

you try to exemplify how ipfs works with 

https://docs.ipfs.io/concepts/what-is-ipfs/#decentralization 
vs
/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Aardvark.html

the former works fine, but the latter doesnt. 

I am convinced, I am doing it wrong, but I cant figure how. Please help

**Comment by johnnymatthews** [comment]
If you are entering `/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Aardvark.html` directly into your browser then you won't actually see anything. You need to use a gateway to view that link:

[ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Aardvark.html](ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Aardvark.html)

But you make a good point. We should point out that to view that link the reader needs to use a Gateway, or other IPFS node.

## Tasks

- [ ] Add a tip after the first Aardvark IPFS link.
- [ ] Explain that to view this page the reader needs to use a gateway such as `ipfs.io/ipfs/` or `cloudflare-ipfs.com/ipfs/`.

**Comment by johnnymatthews** [comment]
Merged into staging.
