### ISSUE TITLE
Collaboration / BrightChain

### ISSUE THREAD

**Issue by JessicaMulein** [ipfs/ipfs-docs#773]
Hi there! I think I have the secret sauce that will get the buy-in that interplanetary needs.
I have started over a number of times over a number of years and am disabled and working full time as well as being a caregiver. I don't have as much time as I want but I think you guys have all the right pieces, and if you can kind of see how to bridge us from here to there, I think IPFS could be the core of the next big thing in crypto/blockchain.

We (you and me) are now creating a new thing called a BrightChain!

https://github.com/The-Revolution-Network/brightChainAPI/wiki/Home

**Comment by johnnymatthews** [comment]
There doesn't seem to be an issue or question here. Closing. Feel free to continue the thread in this issue if there's more to discuss.
