### ISSUE TITLE
Add CI job that checks if CIDs, URIs and content-paths resolve

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-docs#777]
> Inspired by https://github.com/ipfs/ipfs-docs/pull/775

Rough idea: add a CI job that finds CIDs and URIs in text files and checks if they resolve.

Things we could check:
- CIDs (check every word that starts with `Qm` or  [a multibase prefix ](https://github.com/multiformats/multibase/blob/master/multibase.csv)
- content-paths `/ipfs/{valid-cid}` `/ipns/{valid-libp2p-key-or-dnslink}`
  - DNSLink presence should be validated, unless the name ends with `example.com|net|org`
- URIs `ipfs://` and `ipns://` (same rules as for content paths

Ideally:
- check would be run on every PR, but check only modified files
- run once a week and open an issue for every file that has identifier that does not resolve

**Comment by yusefnapora** [comment]
This sounds like a job for [Filecorgi](https://github.com/filecorgi) 😄

We should be able to rewrite IPFS cids & URIs as gateway links and use the existing external link checker that @johndmulhausen wired up.

Plan so far: @johndmulhausen is going to wire up Filecorgi to this repo, and I'll work on the CID checker script.
