### ISSUE TITLE
Pin files

### ISSUE THREAD

**Issue by acul71** [ipfs/ipfs-docs#778]
Hello.
In this page: https://docs.ipfs.io/how-to/pin-files/#local-versus-remote-pinning
following this example:
```bash
echo "ipfs rocks" > foo
ipfs add foo
ipfs pin ls --type=all
ipfs pin rm <foo hash>
ipfs pin rm <foo hash>
ipfs pin ls --type=all
```
#Three kinds of pins
As you may have noticed in the example above, the first ipfs pin rm command didn't work — it should have warned you that the given hash was pinned recursively. 

But the first ipfs pin rm command seems to work it didn't warn me that the file was pinned recursively
My test:
```bash
luca@i5:~/tmp/foo$ echo "ipfs rocks" > foo
luca@i5:~/tmp/foo$ ipfs add foo
added QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy foo
 11 B / 11 B [=======================================================================================================================================================================] 100.00%
luca@i5:~/tmp/foo$ ipfs pin ls --type=all | grep QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy
QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy recursive
luca@i5:~/tmp/foo$ ipfs pin rm QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy
unpinned QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy
luca@i5:~/tmp/foo$ ipfs pin rm QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy
Error: not pinned or pinned indirectly
luca@i5:~/tmp/foo$ ipfs pin ls --type=all | grep QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy
QmRTV3h1jLcACW4FRfdisokkQAk4E4qDhUzGpgdrd4JAFy indirect
luca@i5:~/tmp/foo$ ipfs --version
ipfs version 0.8.0
```

**Comment by johnnymatthews** [comment]
I'm not sure what the issue is here.

> the first ipfs pin rm command didn't work — it should have warned you that the given hash was pinned recursively - @acul71 

The page you linked to reads:

> Objects added through `ipfs add` are pinned recursively by default.

Can you expand on your issue a bit further?
