### ISSUE TITLE
Page of "How is IPFS different from..."

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-docs#779]
* bittorrent
* storj
* arweave
* sia
* filecoin
* dat
* ???

**Comment by atopal** [comment]
Some use case ideas, please feel free to add
1. Very new to space, needs to understand concepts (p2p data transfer, distributed storage, content addressability, etc)
2. Somewhat familiar with concepts, needs to do p2p data transfer, distributed storage, etc.
3. Experienced with concepts, unhappy with current choice, needs to change tech
4.

**Comment by lksbrssr** [comment]
Some ideas for categories along which to differentiate: Total storage capacity, Cost / GB / year, Geographic focus, in operation since YYYY, [feel free to expand]
