### ISSUE TITLE
[DOCS ISSUE] I cannot open IPFS Desktop on Mac

### ISSUE THREAD

**Issue by anthraxblast** [ipfs/ipfs-docs#784]
I opened a prior version of IPFS desktop on Mac about 4 months ago, and it worked fine, but I couldn't reopen that.

I downloaded the DMG again and followed all the instructions (put it in my applications folder), and I'm getting this error (whether I try to open it directly or with Ctrl+Open):
You do not have permission to open the application “IPFS Desktop”.  Contact your computer or network administrator for assistance.

I rechecked that my Mac account is an admin account.

IPFS Version:  0.15.0
Mac O/S:  Big Sur 11.2.2

**Comment by johnnymatthews** [comment]
Oh no! That's not great. Sorry you're having issues, but the [IPFS Discuss Forums](https://discuss.ipfs.io/c/help/13) are a better place to raise support issues. This repository deals with documentation issues.
