### ISSUE TITLE
Update IRC and Matrix Links

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/ipfs-docs#786]
The IRC channels have recently closed and the Matrix channels have been moved from the `matrix.org` homeserver to `ipfs.io`.

**Comment by lidel** [comment]
:+1: 

We need to update https://docs.ipfs.io/community/ and most likely update +rename https://docs.ipfs.io/community/irc to https://docs.ipfs.io/community/chat, as IRC is no longer a reliable.
