### ISSUE TITLE
How to turn an IPFS node into a gateway node.

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/ipfs-docs#788]
I was thinking it might be a good idea to clarify how a user might host their own gateway. It might be clear to some that they can use their go-ipfs node as a public gateway with some configuration, but the concepts/ipfs-gateway write-up doesn't make this explicitly clear. I think it'd be useful to at least make it explicitly clear what software might be used to setup a gateway (or maybe an example setup?).

I thought to ask this because a user asked about how to accomplish this [here](https://matrix.to/#/!gWiVYCURkxIapWZaGy:ipfs.io/%24XOK844bk9t9hVD_OjL4tJlYV8UdcK4VsvQgAyibBxG8?via=ipfs.io&via=matrix.org&via=asra.gr) in #ipfs, and realised that I couldn't seem to locate a resource to point them to that'd offer them immediate clarity.

**Comment by johnnymatthews** [comment]
Good call. Having this doc would be very handy, especially for folks running local hackathons that want an in-house gateway to run things from! I've put the `p2` tag on here for now, but can up the priority if more we find that more folks are requesting it.

**Comment by lidel** [comment]
Topics we should cover:
- [path gateway](https://docs.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) vs [subdomain gateway](https://docs.ipfs.io/how-to/address-ipfs-on-web/#path-gateway) vs dnslink hosting 
- in-depth explainers for common recipes  (https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#gateway-recipes)
- exposing data over HTTP vs running a  gateway for hosting of web apps
    - explaining why origin isolation is important for web app hosting
    - why path gateways are not useful for websites (relative path issues, no origin isolation)
    - setting up wildcard subdomains TLS cert  for subdomain gateway

I'm around for a review/call/chat if someone wants to pick this up.

**Comment by lidel** [comment]
Not to self: this should also include some protips / FAQ with things like using separate domain name to avoid issues described in https://www.notion.so/pl-strflt/Notes-on-Gateway-e811b958674a41bfb52fe46943123fd2
