### ISSUE TITLE
FAQ: How is IPFS and protocol labs funded?

### ISSUE THREAD

**Issue by swedneck** [ipfs/ipfs-docs#789]

**Comment by jessicaschilling** [comment]
@johnnymatthews @johndmulhausen - migrating this issue into docs as we're tidying the old website repo issues in preparation for replatforming. Might be a good inclusion for the FAQ section of docs.

**Comment by johnnymatthews** [comment]
This content isn't really suitable for the docs; developers and builders have very little need for this kind of stuff. Financial and regulatory information is better suited on somewhere like protocol.ai
