### ISSUE TITLE
[CONTENT REQUEST] (django ipfs file upload)

### ISSUE THREAD

**Issue by Sayooj5** [ipfs/ipfs-docs#791]
I am doing my project on a web app by using Django.  I want to upload the files from the project and use ipfs as a database for that. I was not able to find a tutorial for the same. It will be very useful for beginners like me if you add a page for that too.

**Comment by johnnymatthews** [comment]
There's already a decent amount of content relating to IPFS and Django. Found these after a quick search:

1. [StackOverflow](https://stackoverflow.com/questions/39840896/how-can-i-upload-form-field-contents-to-an-ipfs-node-using-django)
2. [Medium](https://python.plainenglish.io/how-i-made-my-django-app-faster-and-safer-with-infura-ipfs-94ee149277be)
3. [Synk.io](https://snyk.io/advisor/python/django-ipfs-storage)

Unfortunately, we don't have the bandwidth to create guides and tutorials for every framework/programming language that IPFS can work with. If there is a significant enough need for a Django + IPFS tutorial, then we can add it into the backlog. But for now, we won't be building this content.

**Comment by Sayooj5** [comment]
But sir these all are from 4 years ago . So it is not working. I am a
beginner in Django and I need help for my engineering project

**Comment by johnnymatthews** [comment]
If you're looking for support, the best place to start is the [IPFS forums](https://discuss.ipfs.io/c/help/13). Unfortunately, [I can't find any other posts relating to Django](https://discuss.ipfs.io/search?q=django%20category%3A13), so you might be the first to ask.
