### ISSUE TITLE
Dead link on: Introducing Fleek

### ISSUE THREAD

**Issue by johncoffee** [ipfs/ipfs-docs#792]
steps:
1. visit https://docs.ipfs.io/how-to/websites-on-ipfs/introducing-fleek/#host-a-site
2. click the link "Check out the Fleek documentation for more information on how to get your domain linked up → "
3. See that the destination url https://docs.fleek.co/hosting/domain-management/ shows an error message "ipfs resolve -r /ipfs/QmWYCZ37PPALRjw3QRw5GSASPTkPmmhqDGiqRSZ4r4pRZQ/hosting/domain-management/: no link named "domain-management" under QmSgyGRMoKrfVZ7d87z8Rk1K3n9sd2CypGvKfhFw4sYWPQ"

:)

**Comment by johnnymatthews** [comment]
Thanks for the catch! Fixed in #793.
