### ISSUE TITLE
Inline code-blocks are not wrapping.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/ipfs-docs#799]
There's a minor bug with the CSS that causes inline-code blocks to _not_ wrap.

1. Go to the [IPNS page](https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli).
2. Scroll down to step 8.
3. Shrink the browser window to about half of your monitor.
4. The code block extends far across the view of the screen:
![Screenshot from 2021-06-14 13-11-15](https://user-images.githubusercontent.com/9611008/121931999-568b3080-cd12-11eb-8e0f-20abaa85bdad.png)

**Comment by yusefnapora** [comment]
@johnnymatthews I think this is the PR that fixed this problem on nft school: https://github.com/protocol/nft-website/pull/84

**Comment by johnnymatthews** [comment]
Nice. Thanks @yusefnapora!
