### ISSUE TITLE
IPNS, explanation needed what is a "k51" key

### ISSUE THREAD

**Issue by kvutien** [ipfs/ipfs-docs#801]
In [step 5](https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli) a comment says "_`k51`... is the key of your IPFS installation_" then later there were several times a mention of `k5` and "key" but a Google on "k51" and on "key of IPFS installation" doesn't give anything.

What is this exactly please? and where in the docs is it explained?

**Comment by johnnymatthews** [comment]
I believe what's happening here is that we're not explains where we're getting `k51...` from:

> 5. Publish your Qm hash to IPNS:
> 
> ```shell
> ipfs name publish /ipfs/QmaMLRsvmDRCezZe2iebcKWtEzKNjBaQfwcu7mcpdm8eY2
> 
> > Published to k51qzi5uqu5dkkciu33khkzbcmxtyhn376i1e83tya8kuy7z9euedzyr5nhoew: /ipfs/QmaMLRsvmDRCezZe2iebcKWtEzKNjBaQfwcu7mcpdm8eY2
> ```
> 
> `k51...` is the key of your IPFS installation.

The `k51...` bit refers to the key pushed out by `ipfs name publish ...`:

> ```shell
> Published to k51qzi5uqu5dkkciu33khkzbcmxtyhn376i1e83tya8kuy7z9euedzyr5nhoew: /ipfs/QmaMLRsvmDRCezZe2iebcKWtEzKNjBaQfwcu7mcpdm8eY2
> ```

## Tasks

- [ ] Update the IPNS tutorial to make it clearer where the `k51...` key is coming from.

**Comment by kvutien** [comment]
Yes. Thanks a lot.

Allow me a wish from a true beginner. Maybe someone of your team may take some time to go through the docs, specially the ones for beginner, and make sure that the technical terms are consistent and unambiguous. I totally understand that for you guys who are involved since the beginning, using different words for the same concept is OK, or using the same words for different contexts. But for a beginning this is the most confusing.

The word "key" in this case is quite ambiguous. Is there something to do with PKI keys? what means "the key of an installation"? what is an installation here? Anything to do with a local IPFS node?

Keep good work. It's amazing and i'm progressing slowly.

**Comment by johnnymatthews** [comment]
> But for a beginner this is the most confusing.

You're absolutely right. These docs are long in needed of a review and overhaul. Unfortunately, the docs team is spread pretty thin across multiple Protocol Labs projects. Any help we can get from the community would be hugely apprecaited.

**Comment by Annamarie2019** [comment]
I'll start this one, while I wait for answers to other PRs in play.

**Comment by Annamarie2019** [comment]
In progress: This page may be helpful: https://hackernoon.com/a-beginners-guide-to-ipfs-20673fedd3f

**Comment by Annamarie2019** [comment]
See PR #1068
