### ISSUE TITLE
[DOCS ISSUE] (add your title here!)

### ISSUE THREAD

**Issue by Win32netsky** [ipfs/ipfs-docs#809]
Hello
I have Files Error 404 ?
Instruction MSF not works on Hirsute Hippo amd46
This is the new exp. Version

``
marko@marko-desktop:~$ await ipfs.files.mkdir('/example')
bash: Syntaxfehler beim unerwarteten Wort »(«
marko@marko-desktop:~$ 
``
Best Regards

**Comment by johnnymatthews** [comment]
If you're looking for support, you're better off posting your issues on the [IPFS forum](https://discuss.ipfs.io/).
