### ISSUE TITLE
Link a domain

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ipfs/ipfs-docs#862]
Hi,
this page shows dnslink to ipfs/<hash>, but nothing about mutable root with ipns/<hash>
is it intentional?

**Comment by johnnymatthews** [comment]
At the time of writing this tutorial series, DNSLink was the most reliable service, and was also pretty simple to use.

**Comment by ROBERT-MCDOWELL** [comment]
Yes indeed, I learned a lot since 3 days and need to understand and learn more about the logic, especially how to manage permissions and old blocks
