### ISSUE TITLE
Make a new roadmap 2021-2022?

### ISSUE THREAD

**Issue by kmunk1975** [ipfs/ipfs-docs#865]
Make a new roadmap 2021-2022?
There is nowhere to find a roadmap 2021-2022 for ipfs

Missing a new roadmap 2021-2022
![2021-08-23](https://user-images.githubusercontent.com/3010850/130427412-5ceeda38-4d49-48cd-93d4-3caa85f03340.png)

I can't find docs, readme, or links, to a roadmap 2021-2022, either work to do or publish
kmunk1975

**Comment by alexmmueller** [comment]
Hey @kmunk1975! This issue was [raised in the discussion forum](https://discuss.ipfs.io/t/2021-roadmap-for-ipfs-is-this-still-a-thing/10534/5) back in march. Maybe you can add your request / support there?

**Comment by johnnymatthews** [comment]
This isn't _strictly_ a documentation issue. I'm gonna close this one for now, but please keep up the conversation in the [Discussion Forum](https://discuss.ipfs.io/t/2021-roadmap-for-ipfs-is-this-still-a-thing/10534/5). Thanks for linking to that @alexmmueller!
