### ISSUE TITLE
Add output of `pin` commands to `how-to/pin-files`.

### ISSUE THREAD

**Issue by gsaslis** [ipfs/ipfs-docs#874]
Hi folks, 

I think it would be useful to have the output from the commands on this page: https://docs.ipfs.io/how-to/pin-files/#three-kinds-of-pins 

I find that just seeing the commands, without their output, feels a little counter-intuitive.

**Comment by johnnymatthews** [comment]
Marked as `trivial`, but might be slightly more complex if we need to import the fancy code `input/output` block from Filecoin and Web3.Storage docs.

**Comment by johnnymatthews** [comment]
Closed in #896.
