### ISSUE TITLE
Mint an NFT with IPFS

### ISSUE THREAD

**Issue by cj-l** [ipfs/ipfs-docs#879]
Hi,

Is it possible to pin a directory of files, so they all have the same "base CID", and then add new files to that "base CID"?

This is so that the URIs of all my files are consistent.

For example If I had files `1.json`, `2.json` and `3.json`, I'd want them to go to `ipfs://<myCID>/1.json`, `ipfs://<myCID>/2.json` etc. Once these are pinned, I'd then want to be able to pin `4.json` which goes to the same CID so the URI is consistent: `ipfs://<myCID>/4.json`.

Thanks!

**Comment by lidel** [comment]
The CID of parent directory is based on the content of your files, so the short answer is no.
When you add 4.json that will change the CID of your root dir.

For more info see https://docs.ipfs.io/how-to/mint-nfts-with-ipfs/ and reach out at  https://discuss.ipfs.io/ where more people look and will be able to answer your support questions :pray:
