### ISSUE TITLE
How initial dial-up/peer discovery works

### ISSUE THREAD

**Issue by jilleJr** [ipfs/ipfs-docs#885]
Hello! How does IPFS nodes get their initial list of peers on startup?

As long as your node has at least one other node connected, it can provide your node with locations to find other nodes. But when you start up your IPFS node, or start your Brave browser, how does it find any node to begin with? Only solution I can imagine is if the IPFS node comes shipped with some hard-coded nodes to discover, or a centralized location where it can obtain its initial peer list, but I imagine libp2p or IPFS has solved this in a different way?

I feel this is left out in the documentation. Closest I could find was the reference for how libp2p does its dialing (https://docs.ipfs.io/concepts/libp2p/#transport)

Personally I would like such an explanation be placed in https://docs.ipfs.io/concepts/how-ipfs-works/

**Comment by johnnymatthews** [comment]
The search term you're looking for is a _bootstrap node_. These are nodes that are designed to be on all the time, and to help new nodes get set up and find their initial peers. You can find out more about bootstrap nodes and how to modify the nodes your IPFS node talks to in the [Modify the bootstrap list section](https://docs.ipfs.io/how-to/modify-bootstrap-list/)
