### ISSUE TITLE
Remove dead example link.

### ISSUE THREAD

**Issue by piorot** [ipfs/ipfs-docs#886]
This link leads to none existing GH page: 
![image](https://user-images.githubusercontent.com/18365032/134209534-d1e079ea-dd05-4e59-bb2c-33eafb15d852.png)

In other words  [https://github.com/ipfs/js-ipfs/tree/master/examples/explore-ethereum-blockchain](https://github.com/ipfs/js-ipfs/tree/master/examples/explore-ethereum-blockchain) returns 404

**Comment by johnnymatthews** [comment]
Oh no! Looks like that example doesn't exist anymore :( I'll take out that line.
