### ISSUE TITLE
The TokenID of newly minted ERC 1155 could be the IPFS CID RE: Best Practices for Storing NFT Data using IPFS

### ISSUE THREAD

**Issue by soenkeba** [ipfs/ipfs-docs#925]
The problem with current IPFS is that each newly minted ERC 1155 token is that one would have to change the root CID defined at deployment of the ERC 1155 contract... so why not make the TokenID of ERC 1155 the CID?
Here is a description:

https://soenkeba.medium.com/truly-decentralized-nfts-by-erc-1155-b9be28db2aae

**Comment by johnnymatthews** [comment]
Maybe I'm misunderstanding what you're asking here, but this doesn't sound like an IPFS-DOCS issue. If it is, please expand further on what you're expecting to see in the docs.
