### ISSUE TITLE
Consider disabling the email protection in your cloudflare control panel.

### ISSUE THREAD

**Issue by JasonTable** [ipfs/ipfs-docs#934]
I use noscript and when i browse the ipfs docs, i will see [email protected] in place of any emails on the page. For example the "Ways to contribute" page says

> If you're interested in contributing to our research, please reach out to [email protected] or [email protected] for more information.

In my opinion this protection is unnecessary because the emails are still available in the [IPFS version](http://docs.ipfs.io.ipns.localhost:8080/community/contribute/ways-to-contribute/#research) of the page.

**Comment by johnnymatthews** [comment]
That's fair, but it seems like your use-case is pretty niche. I'm gonna close this issue for now as a `no-fix`. But, if more users come forward with the same issue, then we can take another look at disabling email protection through Cloudflare.
