### ISSUE TITLE
[CONTENT REQUEST] add file - insert critical warning

### ISSUE THREAD

**Issue by javabeanz** [ipfs/ipfs-docs#937]
if you add content to ipfs, is not possible to delete it. this is the strength of the system and also its weakiness. If users are not warned about this, important imformation might be stored that was not neamt to be. With a clear warning the risks of this can be reduced..

**Comment by johnnymatthews** [comment]
This issue you're referring to is discussed on the [Privacy and encryption](https://docs.ipfs.io/concepts/privacy-and-encryption/#what-s-public-on-ipfs) and the [Persistence](https://docs.ipfs.io/concepts/persistence/) pages. I'm gonna close this issue for now.

**Comment by javabeanz** [comment]
very disappointed with closing this issue; referring to a documenation file is not a solid and user friendly way to pretect users. this risk for novel users can be easily overlooked when you are fully accustomed to the ipfs-blockchain-pradigm already know how persistent changes are.
