### ISSUE TITLE
dweb-primer Site Unreachable

### ISSUE THREAD

**Issue by scottbourne** [ipfs/ipfs-docs#948]
When trying to go to dweb-primer.ipfs.io, I received the following error:

dweb-primer.ipfs.io uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

this happened form two different PCs (one Windows, one Ubuntu)

**Comment by johnnymatthews** [comment]
I'm getting the same error. I'll look into what's happened. Thanks for raising @scottbourne

**Comment by johnnymatthews** [comment]
It sounds like this website is gone for good :(

**Comment by scottbourne** [comment]
Well, thanks for following up!

**Comment by momack2** [comment]
that site might be, but it's still all online here: https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/
