### ISSUE TITLE
Simplify the `concepts/nodes/` page to make it easier to understand for new IPFS users.

### ISSUE THREAD

**Issue by sorenwagner** [ipfs/ipfs-docs#951]
Could use more context on the details of nodes, if possible. For a semi-technical person, this content is much less accessible than all previous chapters.

**Comment by johnnymatthews** [comment]
Have you taken a look at the [nodes page](https://docs.ipfs.io/concepts/nodes/#implementations)? If you have, and you still found it confusing, what kind of content would you like to see in there? This'll help us define a clear task list for this issue.

**Comment by sorenwagner** [comment]
Hi, thanks for responding!

Yeah the nodes page was what i was referring to. Everything up to that point in the tutorial seemed to build a comprehensive understanding of the concepts from the ground up, but this chapter references a ton of technical terms, which seem like a foreign language at first glance.... QUIC, /ws/, WSS, TLS, etc. And each subsection of Types was quite complicated as well.

I think more written explanation of the concepts, as done in the previous chapters, would be really helpful. As well as some background on some of the terms mentioned above, if possible.

**Comment by johnnymatthews** [comment]
> this chapter references a ton of technical terms

Agreed. This page was actually taken from a HackMD post created by some of the core IPFS engineers to help explains things during hackathons and similar events. But you're absolutely right that this page should be easier to understand.

**Comment by Annamarie2019** [comment]
See [PR #1031](https://github.com/ipfs/ipfs-docs/pull/1031), where a few changes were submitted for usability.

**Comment by Annamarie2019** [comment]
@sorenwagner and @johnnymatthews  While adding the definitions for nodes for issue [#683: List the Multiple Definitions of Node](https://github.com/ipfs/ipfs-docs/issues/683) I also reorganized a bit and did some word smithing. Does this satisfy the need for this issue to simplify the page as well, see: [Nodes](https://docs.ipfs.io/concepts/nodes/#nodes)

**Comment by johnnymatthews** [comment]
> Does this satisfy the need for this issue to simplify the page as well, see: [Nodes](https://docs.ipfs.io/concepts/nodes/#nodes), if so, we can close this PR.

I believe so. Closing.
