### ISSUE TITLE
File systems mv endpoint

### ISSUE THREAD

**Issue by Nortberg** [ipfs/ipfs-docs#974]
Hi.

I'm testing IPFS and now reviewing MFS files endpoints and for eg.
curl -X POST  http://0.0.0.0:5001/api/v0/files/mv?arg=/ipfs/QmPKouHudk3sAtYeU7sxDwa54beWWg9p3UDHUWhzSREuaL&arg=/store

I see that there are two parameters with the same name "arg" in documentation.
In some other/external docs i saw arg and arg2.
anyway whatever I'm trying to do i get 
- argument "dest" is required
that suggests second parameter is not visible for endpoint.

Can You help me to understand how to deal with parameters in that endpoint?

**Comment by johnnymatthews** [comment]
The best place to post support questions is the [Discuss IPFS forums](https://discuss.ipfs.io/). This repo is for IPFS Docs content management.
